### ISSUE TITLE
Placing an order for ticker 'EGY' but the actual order is for 'PE'

### ISSUE THREAD

**Issue by tradinginaction** [tedchou12/webull#101]
I tried debugging, thus I don't know if this is Webull endpoint API issue or if there's a way to improve/workaround in webull.py

**Comment by hfacey** [comment]
ensure you pull the latest version of the module. #98 provided a workaround for this 10 days ago now. Essentially, that symbol search does a match based on ticker and company name. 'PE' is for 'Parsley Egy' so I guess that one was a higher rank for you

**Comment by tradinginaction** [comment]
thanks will do!

**Comment by tradinginaction** [comment]
confirming that the said fix addressed this issue
thanks @tedchou12 @hfacey
