### ISSUE TITLE
TickerId could not be found for stock -- Cryptocurrency

### ISSUE THREAD

**Issue by wyatt-mattas** [tedchou12/webull#103]
API cannot find ticker for certain cryptocurrencies like BTCUSD and ETHUSD as they are CCC. However, it finds BTCEUR is FX and is able to be found.

**Comment by tedchou12** [comment]
@typicalGinger 
Yes, sorry, Cryptocurrency is a new feature out on the webull app this week. I have not yet tried to trade it on the App yet.

If I have some free time soon, I will look into it.

**Comment by typicalGinger** [comment]
@tedchou12 No rush just wanted to make the issue known

**Comment by alexonab** [comment]
@typicalGinger Make sure you have the latest git release installed.  The pip version maybe out of date.

> pip install -U git+https://github.com/tedchou12/webull.git

```
>>> from webull import webull
>>> wb = webull()
>>> wb.get_quote('BTCUSD')
{'tickerId': 913420438, 'exchangeId': 55, 'type': 6, 'name': 'Bitcoin/US Dollar', 'symbol': 'BTCUSD', 'disSymbol': 'BTCUSD', 'disExchangeCode': 'FX', 'exchangeCode': 'CURRENCY', 'listStatus': 1, 'template': 'forex', 'tradeTime': '2020-12-09T21:11:09.000+0000', 'status': 'T', 'close': '18437.6850', 'change': '-236.0750', 'changeRatio': '-0.0126', 'marketValue': '0.0000', 'volume': '179', 'turnoverRate': '0.0000', 'timeZone': 'America/New_York', 'tzName': 'EST', 'preClose': '18673.7600', 'open': '18311.3100', 'high': '18529.3900', 'low': '17640.3300', 'vibrateRatio': '0.0476', 'dealAmount': '0', 'negMarketValue': '0.0000', 'fiftyTwoWkHigh': '19918.0100', 'fiftyTwoWkLow': '4000.0000', 'ntvSize': 0, 'currencyCode': 'USD', 'lotSize': '1'}
>>> wb.get_ticker('BTCUSD')
913420438

```

**Comment by Exovel-Productions** [comment]
I struggled with this for quite a while and eventually tried "Bitcoin" (instead if BTCUSD) as the symbol and that worked.

**Comment by noelnamai** [comment]
Does anyone know how to place the trades on crypto? I don't seem to have my orders sent to the exchange! Thanks.

**Comment by Exovel-Productions** [comment]
@noelnamai I was able to get the Webull API to complete a crypto trade by using 'Bitcoin' as the ticker symbol. I have not tried any other cryptos. I also did not try to place an order by using the ticker id only.

**Comment by mrsmirf** [comment]
Has anyone had success trading crypto?

**Comment by tedchou12** [comment]
there is a special place order function for it.
https://github.com/tedchou12/webull/blob/e16a7e0120ae754254115c7265fcce50a28709c0/webull/webull.py#L622
I think this is resolved.
