### ISSUE TITLE
can't get real webull account information or place order

### ISSUE THREAD

**Issue by IvoryTower800** [tedchou12/webull#104]
I logged in successfully in my webull account and got the trading token(return true).
But I can not do anything about my real account. (everything is ok with my paper account)
eg. 
`wb.get_history_orders('Filled')`
it returns like this:
> {'msg': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Long\'; nested exception is java.lang.NumberFormatException: For input string: "None"',
 'traceId': '5079290334bd4e3f92ba9921510d6b69',
 'code': '400',
 'success': False}

`wb.get_portfolio()`
it returns like this:

> KeyError                                  Traceback (most recent call last)
<ipython-input-11-2d58d826c72c> in <module>
----> 1 wb.get_portfolio()

e:\code\trade\venv\lib\site-packages\webull\webull.py in get_portfolio(self)
    221         data = self.get_account()
    222         output = {}
--> 223         for item in data['accountMembers']:
    224             output[item['key']] = item['value']
    225         return output

KeyError: 'accountMembers'

I've tried to reinstall webull, python and even tried another two computer. It still shows like this.
could anyone help me solve this problem? 
thank you so much!

**Comment by tedchou12** [comment]
Interesting... I see Java type error in your code:
```
{'msg': 'Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "None"',
'traceId': '5079290334bd4e3f92ba9921510d6b69',
'code': '400',
'success': False}
```
can you print(data)
what do you see? **make sure you sensor out some sensitive data like your account ID.**

**Comment by IvoryTower800** [comment]
> Interesting... I see Java type error in your code:
> 
> ```
> {'msg': 'Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "None"',
> 'traceId': '5079290334bd4e3f92ba9921510d6b69',
> 'code': '400',
> 'success': False}
> ```
> 
> can you print(data)
> what do you see? **make sure you sensor out some sensitive data like your account ID.**

yes, I tried to print data as you told.
it returns like this:

`{'msg': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Long\'; nested exception is java.lang.NumberFormatException: For input string: "None"', 'traceId': 'ee67504c4c614b0080a51d08d7b22978', 'code': '400', 'success': False}`

**Comment by tedchou12** [comment]
Thanks,
I think that is the reason you are not seeing any information.
There is still java type error in your code...
could you post your entire code? Including how you initaited the wb variable and how you login? (**Just remove your email and password and trade pin**)

**Comment by IvoryTower800** [comment]
> Thanks,
> I think that is the reason you are not seeing any information.
> There is still java type error in your code...
> could you post your entire code? Including how you initaited the wb variable and how you login? (**Just remove your email and password and trade pin**)

sure, only type these code will return the error, I'm sure I logged in successfully, cuz 'wb.get_detail()' works. Perhaps this might be the only function I can use related to my account.
I tried to use 'pip install webull' or clone codes from github. It returns the same error.
and I tried to log in through MFA. It still didn't work.

I've been using my paper_account for quite a long time. Everyting goes fine. This is the first time I use this project in my real account.

`from webull import webull

wb = webull()
data = wb.login('xxx', 'xxx')
wb.get_trade_token('xxx')
print(wb.get_account())`

> {'msg': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Long\'; nested exception is java.lang.NumberFormatException: For input string: "None"', 'traceId': '5c60e1eb4470400497ff13a20e9402d0', 'code': '400', 'success': False}

**Comment by tedchou12** [comment]
Thanks, I am quite curious where the java type came in.
Thanks for posting the code, it looks exactly the same as mine.

I am guessing you might have some python3 package mismatch on your environment. Unfortunately the information here is not enough.

you mentioned that paper_account works well. So I think there should still be some way to get it to work.

Could you try this and give me the output or the error?
```
data = self.get_account()
print(type(data))
```
Let's see what the return is.

**Comment by IvoryTower800** [comment]
> Thanks, I am quite curious where the java type came in.
> Thanks for posting the code, it looks exactly the same as mine.
> 
> I am guessing you might have some python3 package mismatch on your environment. Unfortunately the information here is not enough.
> 
> you mentioned that paper_account works well. So I think there should still be some way to get it to work.
> 
> Could you try this and give me the output or the error?
> 
> ```
> data = self.get_account()
> print(type(data))
> ```
> 
> Let's see what the return is.

yes, I tried different computers(windows 10 and ubuntu 18.4 server) and it returns the same thing.

I tried your code and it returns a dict and here is the contents in the dict:
`{'msg': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Long\'; nested exception is java.lang.NumberFormatException: For input string: "None"', 'traceId': '6c7b92e7b54c48f1b015f9edf1f162d4', 'code': '400', 'success': False}`

Thank you so much for trying to help me out.

**Comment by tedchou12** [comment]
Thanks for testing the type. Dict looks alright, but the content is entirely off. Since you tried on both computers and the output is the same, I am suspecting this is not the issue of the code or your environment, but related to your account...
Just by the way, are you able to access and login via here?
http://app.webull.com/
Using the web version of webull?

**Comment by IvoryTower800** [comment]
> Thanks for testing the type. Dict looks alright, but the content is entirely off. Since you tried on both computers and the output is the same, I am suspecting this is not the issue of the code or your environment, but related to your account...
> Just by the way, are you able to access and login via here?
> http://app.webull.com/
> Using the web version of webull?

yes, I can log in to use the web version of webull.
well. I might found the reason.
I tried my friend's account. everything works fine. but my account doesn't.
it seems like there are something wrong with my account.
is it beacuse I opened webull HK account several days ago? otherwise, there should be no difference between mine and my friend's account.

so could you tell me what should I do to make it work?

thanks so much!

**Comment by tedchou12** [comment]
I see..
Sorry, I have no experience with an HK account.
This is quite an isolated issue, so the help I can offer is limited. I know they have API support for various regions (you can find places to specify region code in the code).

If you want, I can take a look at it remotely personally. But from the status of the HK account, I suspect I can do much about it.

**Comment by IvoryTower800** [comment]
> I see..
> Sorry, I have no experience with an HK account.
> This is quite an isolated issue, so the help I can offer is limited. I know they have API support for various regions (you can find places to specify region code in the code).
> 
> If you want, I can take a look at it remotely personally. But from the status of the HK account, I suspect I can do much about it.

thanks, I really appreciate your help! If you are willing to remotely help me check it, my wechat is ivorytower123, my skype is niuyulin@live.com

**Comment by tedchou12** [comment]
changing 
``` 
def account_id(self):
        return f'{self.base_trade_url}/account/getSecAccountList/v4'
```
to 
``` 
def account_id(self):
        return f'{self.base_trade_url}/account/getSecAccountList/v5'
```
worked.

**Comment by jfuruness** [comment]
Also having this problem when placing orders

**Comment by jfuruness** [comment]
even with the new account_id endpoint

**Comment by shailesh9r** [comment]
Hello Ted/Others , I recently opened the account and I see same error for my real account. I even added following in webull.py file.

def account_id(self):
        return f'{self.base_trade_url}/account/getSecAccountList/v5'

wb.get_portfolio returns KeyError: 'accountMembers'. Unable to pull out information for account. Any suggestion?

Thanks in advance,

**Comment by shamssheikh** [comment]
@shailesh9r can you please check my comment in defect 157 and see if it resolves the issue.

**Comment by shailesh9r** [comment]
> @shailesh9r can you please check my comment in defect 157 and see if it resolves the issue.

No it does not solve it. I have same comment as cliu (reposting below). Any other suggestion to fix this for new account?

@shamssheikh Thanks for sharing it. I tested it with my new account but it still return 500 when I call account() function. It is so weird that these APIs can only work on an old account rather than a new account

**Comment by shamssheikh** [comment]
@shailesh9r not sure what's the new endpoint. Did you try to inspect the new endpoint via browser.

**Comment by shailesh9r** [comment]
> @shailesh9r not sure what's the new endpoint. Did you try to inspect the new endpoint via browser.

yes, that is what I am going through...sucks that nothing works for real account :(...

**Comment by shailesh9r** [comment]
changed self.base_trade_url = 'https://tradeapi.webullbroker.com/api/trade' to self.base_trade_url = 'https://ustrade.webullfinance.com/api/trade' and to v5 for    def account(self, account_id):
        return f'{self.base_trade_url}/v5/home/{account_id}', but now I get following error : {'msg': 'Your session has expired, please login again.', 'traceId': 'XXX', 'code': 'trade.token.expire', 'data': {}, 'success': False} . Any idea how to fix this now?

**Comment by acelearns** [comment]
> changed self.base_trade_url = 'https://tradeapi.webullbroker.com/api/trade' to self.base_trade_url = 'https://ustrade.webullfinance.com/api/trade' and to v5 for def account(self, account_id): return f'{self.base_trade_url}/v5/home/{account_id}', but now I get following error : {'msg': 'Your session has expired, please login again.', 'traceId': 'XXX', 'code': 'trade.token.expire', 'data': {}, 'success': False} . Any idea how to fix this now?

hey @shailesh9r , im getting exactly same error, did you find a way to fix it? 
does anyone know how to fix that? im using access_token to login
