### ISSUE TITLE
is it possible to support place option order by symbol contract?

### ISSUE THREAD

**Issue by kooyear** [tedchou12/webull#108]
is it possible to support place option order by symbol contract?
like, 
place_option_order('ROKU201218C00460000') ?

**Comment by GuohaiZhou** [comment]
You may add 2 lines to extract the optionid based on stock symbol, expiration date, strike price and option type (call or put) and then call the place_order_option method. For example, 

Options = wb.get_options(stock='SPY', count=-1, includeWeekly=1, direction='all', expireDate='2021-12-31', queryAll=0)

optionid_for_place_order_option = Options[Options.strikePrice=='470'].loc['tickerId'].call.values[0]

wb.place_order_option(optionId=optionid_for_place_order_option , lmtPrice=0.01, action="BUY", orderType='LMT', enforce='DAY', quant=1)
