### ISSUE TITLE
get_options_by_strike_and_expire_date pass wrong parameter to get_options

### ISSUE THREAD

**Issue by kooyear** [tedchou12/webull#109]
https://github.com/tedchou12/webull/blob/master/webull/webull.py#L526

in get_options_by_strike_and_expire_date
opts = self.get_options(stock=stock, expireDate=expireDate, direction=direction, headers=headers)
TypeError: get_options() got an unexpected keyword argument 'headers'\n"

**Comment by alexonab** [comment]
If you update to the latest this should be resolved.

```pip install -U git+https://github.com/tedchou12/webull.git```
