### ISSUE TITLE
login fail with code="app.device.control"

### ISSUE THREAD

**Issue by hopflink** [tedchou12/webull#110]
It worked fine before, but today login failed with the following message.
{'msg': 'login failed.', 'traceId': 'xxx', 'code': 'app.device.control'}
How can I resolve this?

**Comment by Winglights** [comment]
Same to me.

**Comment by alexonab** [comment]
I just checked and login is working fine with the new git update.  Confirm you are on the latest release or provide your login method and error.

```pip install -U git+https://github.com/tedchou12/webull.git```
```
>>> from webull import webull
>>> wb = webull()
>>> wb.get_mfa('xxx@gmail.com')
>>> wb.login('xxx@gmail.com', 'xxx', 'foo', '123')
{'extInfo': {'userPwdFlag': '1', 'equipmentCheck': 'success'},...
>>> wb.get_account_id()
'xxx'
>>> wb.get_trade_token('1234')
True

```

**Comment by Winglights** [comment]
Hi alexonab,
Thank you for your response.
Through wb.get_mfa(''), I got the verification code, and replaced 'foo' value with that code. Then, the login worked. 
Does that mean I have to get the verification code every time manually to login? Or there is another way to make it automatically?
Best reagrds,
Winglights

**Comment by tedchou12** [comment]
@Winglights 
This might answer your question:
https://github.com/tedchou12/webull/wiki/MFA

**Comment by Winglights** [comment]
Thank you tedchou12 for your response!
When I called wb.refresh_login(), I got this:
{'msg': 'AccessToken is expire', 'traceId': '375f98eba8d9476eb66a098c96a47d90', 'code': 'auth.token.expire'}

Then I found the API_login, that worked. Looks like the tokens expire in 3 month for API_login. 
https://github.com/tedchou12/webull/issues/58
