### ISSUE TITLE
{'msg': 'login failed.', 'traceId': '0599980350e34ea3a11209ffd0cfc29d', 'code': 'app.device.control'}

### ISSUE THREAD

**Issue by jsyszh** [tedchou12/webull#116]
When login, return this:
     {'msg': 'login failed.', 'traceId': '0599980350e34ea3a11209ffd0cfc29d', 'code': 'app.device.control'}

**Comment by jsyszh** [comment]
mfa is is needed.

**Comment by bullmind** [comment]
what is mfa ? certication Code ? how to get it ?

**Comment by tedchou12** [comment]
@bullmind 
MFA is Multi-Factor Authentication.
This is probably what you are looking for:
https://github.com/tedchou12/webull/wiki/MFA

**Comment by jsyszh** [comment]
certication Code.
I get it from email, then input manually.
However, logging in is cumbersome.



At 2020-12-20 15:11:32, "bullmind" <notifications@github.com> wrote:

what is mfa ? certication Code ? how to get it ?

**Comment by tedchou12** [comment]
> certication Code.
> I get it from email, then input manually.
> However, logging in is cumbersome.
This should only needed to be done the 1st time from a new device. One you obtained a successful 1st login, you will get a did.bin file and use that udid to login in the future to prevent MFA challenges.

**Comment by jsyszh** [comment]
Got it, thank you!



在 2020-12-21 13:58:33，"Ted" <notifications@github.com> 写道：

certication Code.
I get it from email, then input manually.
However, logging in is cumbersome.

This should only needed to be done the 1st time from a new device. One you obtained a successful 1st login, you will get a did.bin file and use that udid to login in the future to prevent MFA challenges.
