### ISSUE TITLE
How can I place a market order for Option trade?

### ISSUE THREAD

**Issue by kooyear** [tedchou12/webull#117]
When I tried to place a market order for trading Option. I got 
('place_option_order failed', 500, '')
error, 
can you share an example with me?

**Comment by tedchou12** [comment]
Seems like Webull has updated the option trading endpoint. The latest version should support it:
`result = finance_webull.place_option_order(optionId='1017444878', lmtPrice='0.01', action='BUY', quant=1)`
returns `True`

**Comment by kooyear** [comment]
it will trade with market order? not limit order?

**Comment by kooyear** [comment]
or do you mean set  lmtPrice='0.01' will make the trade as market order?

**Comment by kooyear** [comment]
how about sell? how can I sell with market price?

**Comment by tedchou12** [comment]
> it will trade with market order? not limit order?

This is limit order:
```
result = finance_webull.place_option_order(optionId='1017444878', lmtPrice='0.01', action='BUY', quant=1)
```

**Comment by tedchou12** [comment]
> how about sell? how can I sell with market price?

```
result = finance_webull.place_option_order(optionId='1017444878', lmtPrice='0.01', action='SELL', quant=1)
```
will be `sell`

**Comment by tedchou12** [comment]
The documentation is not very well, but this will give you some clue:
https://github.com/tedchou12/webull/blob/9232689d8472df46380faa9809e507d6dd772dba/webull/webull.py#L569

**Comment by Hamze24w** [comment]
I'm having trouble with this too, how can we place a market order? an order that would be placed wherever the price is at the moment and not when it reaches a specific limit or stop price. 

also how can I assign stop loss and take profit target to the order?

**Comment by tedchou12** [comment]
Here:
```
# Market Order
result = finance_webull.place_option_order(optionId='1017444878', action='BUY', orderType='MKT', quant=1)
# STP Loss
result = finance_webull.place_option_order(optionId='1017444878', stpPrice='0.01', action='BUY', orderType='STP', quant=1)
# STP Limit
result = finance_webull.place_option_order(optionId='1017444878', stpPrice='0.01', action='BUY', orderType='STP LMT', quant=1)
```
For STP and STP LMT, I have not tried them myself, please let me know if you find troubles.

**Comment by Hamze24w** [comment]
Thanks Ted, the Ordertype = 'MKT' was new to me, thanks for pointing this out, i'd suggest writing it in the comments where you documented "place_option_order" because it gave me the impression that only "LMT", "STP", and "STP LMT" were possible. 

although I don't think you understood what I meant with the other two, can you point out how you get the endpoints and the data for them? maybe I can help to add some features to this as I'm working on my project. 

also, is there a way to get the Mid price of a stock/option using this api ?

**Comment by tedchou12** [comment]
Thanks, sorry for any confusion.
> although I don't think you understood what I meant with the other two, can you point out how you get the endpoints and the data for them? maybe I can help to add some features to this as I'm working on my project.
You can find them here: https://github.com/tedchou12/webull/wiki
under `How do you find the APIs? Are they official?`
> also, is there a way to get the Mid price of a stock/option using this api ?
Do you mean by just getting the price? If so using the `get_quote` and `get_option_quote` is what you need?
