### ISSUE TITLE
qty / quant

### ISSUE THREAD

**Issue by Exovel-Productions** [tedchou12/webull#119]
When placing an order using paper_webull I need to use "quant=1" but when using webull  or crypto I need "qty=1"

am I doing something wrong?

**Comment by tedchou12** [comment]
No, you are doing alright there. Thanks to many that has been helping to improve this library, but some also needs tidying up to make the variables and arguments more consistent.

**Comment by tedchou12** [comment]
Thank you, this should be fixed in #121
