### ISSUE TITLE
Historical lines?

### ISSUE THREAD

**Issue by prashanth742** [tedchou12/webull#120]
Hi I want to get the rsi of the stocks programmatically. So i am looking for historical line function and couldn't find it. Does any one know how to located it?

**Comment by tedchou12** [comment]
Thanks for the question!
I haven't figure out the rsi yet.

For the region id that you asked in the other issue, you can find the answer here.
https://github.com/tedchou12/webull/wiki/What-is-the-region_id%3F

**Comment by alexonab** [comment]
Use the get_bars method which returns a pandas dataframe of ohlcv.  Then use your TA library to calculate the RSI.  I'd suggest pandas_ta.

```
>>>help (wb.get_bars)
Help on method get_bars in module webull.webull:

get_bars(stock=None, tId=None, interval='m1', count=1, extendTrading=0, timeStamp=None) method of webull.webull.webull instance
    get bars returns a pandas dataframe
    params:
        interval: m1, m5, m15, m30, h1, h2, h4, d1, w1
        count: number of bars to return
        extendTrading: change to 1 for pre-market and afterhours bars
        timeStamp: If epoc timestamp is provided, return bar count up to timestamp. If not set default to current time.
```

**Comment by prashanth742** [comment]
Found it. Thanks a lot for you help.
