### ISSUE TITLE
get account id failed

### ISSUE THREAD

**Issue by xuxinx** [tedchou12/webull#124]
https://github.com/tedchou12/webull/blob/8c41019bc5bf67dae31392ee23416a05cd9da9fa/webull/webull.py#L197 the result here is
```
{'success': False, 'msg': "Table 'wl_trade.wlt_webullhk_register_info' doesn't exist"}
```

**Comment by tedchou12** [comment]
Thanks, looks like your account is an hk account?

Could you try this?
```
wb._region_code = 2
print(wb.get_account_id())
```
What does this give you?

based on the information here:
https://github.com/tedchou12/webull/wiki/What-is-the-region_id%3F

**Comment by xuxinx** [comment]
Still the same result.  
Seems like the `_region_code` is not passed to the `get_account_id` request?

**Comment by tedchou12** [comment]
Ah, I recalled another guy had this issue solved:
#104 
His account was a Chinese account, this worked:
changing
```
def account_id(self):
        return f'{self.base_trade_url}/account/getSecAccountList/v4'
```
to
```
def account_id(self):
        return f'{self.base_trade_url}/account/getSecAccountList/v5'
```

Sorry, could you give this one a try?

**Comment by xuxinx** [comment]
It works. Thx!
