### ISSUE TITLE
Cancelling OTOCO order fails

### ISSUE THREAD

**Issue by felix-halim** [tedchou12/webull#126]
Steps to reproduce:

wb = webull()
wb.login('xxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxx')
wb.get_trade_token('123456')

wb.place_otoco_order(stock='AAPL', price='90.00', stop_loss_price='80.00', limit_profit_price='100.00', time_in_force='GTC', quant=1)

order_id = # find the master order id
wb.cancel_otoco_order(order_id) # this fails to cancel the OTOCO order

**Comment by tedchou12** [comment]
Thanks,
sure, let me look into this!

**Comment by tedchou12** [comment]
@felix-halim 
Hi there.

I have updated the endpoint, it will respond with:
```
{"comboId":"J2I61E3LS9AJASR5QJ6L3MR911","lastSerialId":"5fec5f3934385e00011aeabd"}
```
a comboId,
to retract the otoco order, use this:
```
wb.cancel_order_otoco(combo_id='J2I61E3LS9AJASR5QJ6L3MR911')
```

Let me know if is okay. (**Remember to update the endpoints**)

**Comment by felix-halim** [comment]
It works like charm! Thank you @tedchou12  !
