### ISSUE TITLE
cannot place a stop order; and there is not a way to create stop-limit order

### ISSUE THREAD

**Issue by caven-yang** [tedchou12/webull#129]
issue 1
```
r1 = wb.place_order(
    stock='VGAC',
    price=11.0,
    action='SELL',
    orderType='STP',
    enforce='GTC',
    qty=1,
  )


```
it returned

`{'msg': 'null', 'traceId': '9dc80ffb4e2047ffb4e30f9e555fe9e3', 'code': '200', 'success': False}`

To verify if it is a setup issue, i tried limit order and it worked fine

issue 2
i don't think we can place a stop-limit order since the api
```
    def place_order(self, stock=None, tId=None, price=0, action='BUY', orderType='LMT', enforce='GTC', quant=0, outsideRegularTradingHour=True):
```

only takes 1 price. For a stop-limit order we need the stop price as well as the limit price.

Thank you for working on this API! Happy Holiday!

**Comment by caven-yang** [comment]
https://github.com/tedchou12/webull/blob/master/webull/webull.py#L343


here's the code inside `place_order`


     ```
   data = {
            'action': action,
            'lmtPrice': float(price),
            'orderType': orderType,
            'outsideRegularTradingHour': outsideRegularTradingHour,
            'quantity': int(quant),
            'serialId': str(uuid.uuid4()),
            'tickerId': tId,
            'timeInForce': enforce
        }
```

are we supposed to have a `stpPrice` ?

**Comment by tedchou12** [comment]
Hi there!.

Yes, I think there is a missing price parameter for stpprice, I have created a branch for that,:
https://github.com/tedchou12/webull/tree/stop_order

Could you give this one a try and see if it works?

**Comment by tedchou12** [comment]
You should be able to place order:
```
r1 = wb.place_order(
    stock='VGAC',
    price=11.0,
    stp_price=12,
    action='SELL',
    orderType='STP',
    enforce='GTC',
    qty=1,
  )
```

**Comment by DTLine** [comment]
@tedchou12 , I would like to contact you regarding a wechat project, what's your contact info? thanks

**Comment by tedchou12** [comment]
@DTLine 
You can send an Email to me: ted.chou12@gmail.com
