### ISSUE TITLE
Wrapper for paper Trading 

### ISSUE THREAD

**Issue by peymanrah** [tedchou12/webull#13]
It would be great to add a method for paper trading in the Webull class so one can test their trading strategy without losing money.

**Comment by knurts** [comment]
I'm working on this... here's the basic paper endpoints so far:
acct id: 'https://act.webullbroker.com/webull-paper-center/api/myaccounts/true'
acct info: 'https://act.webullbroker.com/webull-paper-center/api/paper/1/acc/' + str(paper_account_id)
place order: https://act.webullbroker.com/webull-paper-center/api/paper/1/acc/ + str(paper_account_id) +/orderop/place/ + str(stock ticker id)
modify order: https://act.webullbroker.com/webull-paper-center/api/paper/1/acc/ + str(paper_account_id) + /orderop/modify/ + str(order id)
cancel order: https://act.webullbroker.com/webull-paper-center/api/paper/1/acc/ + str(paper_account_id) + /orderop/cancel/ + str(order id)

**Comment by knurts** [comment]
please take a look at https://github.com/tedchou12/webull/pull/20
