### ISSUE TITLE
get_mfa call fails when phone number is input as username

### ISSUE THREAD

**Issue by trey92** [tedchou12/webull#131]
I'm trying to log in to an account I have that can only be logged in via phone number. When I make the `get_mfa` call to authenticate, I just get a 500 code response.

```
webull = webull()
webull.get_mfa("+1-xxxxxxxxxx")

<Response [500]>
```

**Comment by tedchou12** [comment]
Sorry, seems like the old endpoint URL only worked for Email, this one will work for phone as well.

**Comment by trey92** [comment]
> Sorry, seems like the old endpoint URL only worked for Email, this one will work for phone as well.

Yep, that fixed it. Thanks!
