### ISSUE TITLE
Service is not available-can not place order

### ISSUE THREAD

**Issue by bullmind** [tedchou12/webull#135]
```
wb.get_trade_token('xx')
wb.place_order(stock='IRIX',price=4.3,qty=1,action='BUY')
```

{'msg': 'Service is not available,please try again later',
 'traceId': '94e604ba4ef74ddf926cd1c0fa258987',
 'code': '200',
 'data': {},
 'success': False}

手动在webull 的app上可以下单

**Comment by bullmind** [comment]
手动在webull 的app上可以下单

**Comment by bullmind** [comment]
@tedchou12 boss,plz help

**Comment by tedchou12** [comment]
Seems like you are using the old package from pypi?
Could you download the zip from github and do `python setup.py install` instead?
