### ISSUE TITLE
Unable to place option order, error 500

### ISSUE THREAD

**Issue by Hamze24w** [tedchou12/webull#136]
Hi, I'm trying to place option order, but I keep getting Error 500 with no description as to why it's not sending it. 
I pulled the latest version and tried again, same problem, is it something with my code? 

`wb.place_order_option(optionId = optid, lmtPrice= 0.46, stpPrice = 0.41, action = "BUY" , orderType = "LMT", quant = 1)`
I tried the same with "MKT" , no luck. 
I always get this:  
raise Exception('place_option_order failed', response.status_code, response.reason)
Exception: ('place_option_order failed', 500, '')

**Comment by Hamze24w** [comment]
the option id is a string , pulled it from the ['tickerId'] from the 'get_option_by_strike_and_expireDate()' .

**Comment by Hamze24w** [comment]
I also have a small question: how often does webull update/change the endpoints? how frequent has it been ?

**Comment by tedchou12** [comment]
> the option id is a string , pulled it from the ['tickerId'] from the 'get_option_by_strike_and_expireDate()' .

Can you post the `optid` ? 

> I also have a small question: how often does webull update/change the endpoints? how frequent has it been ?

Um, it depends on which endpoints, some are updated more frequently than others, but my experience is roughly 2 times a year.

**Comment by Hamze24w** [comment]
This how I find the option:
`opt = wb.get_options_by_strike_and_expire_date(stock="F",expireDate = "2021-02-19" , strike = "10",direction="call")`
then I use this to get the optionId : 
` optid = opt[0]["call"]['tickerId']`
which gives back an int => 1017805429
I then turn that into str and use it in place option order.

**Comment by Hamze24w** [comment]
Thanks for the answer about endpoints. good thing it's not very frequent. 
a note: I noticed that the account i'm working with still has no balance(it's on it's way being processed by webull) , could that be the issue? isn't supposed to return an "insufficient balance" response?

**Comment by tedchou12** [comment]
@Hamze24w 
I just took a look, I am able to order option:
`result = wb.place_order_option(optionId='1017805429', lmtPrice=0.1, stpPrice=0.1, action="BUY" , orderType="LMT", quant=1)
print(result)`
```
{"comboId":"GRGO3BTTOSGEC9ACIQ44FGQQQ9"}
```

My advice is try to order within 8AM-4PM, as for the "insufficient balance", that might be possible.

**Comment by Hamze24w** [comment]
I did it exactly as you did, no luck. I got error 403 first, remember I didn't have trade token, then did it again got the same 500 error no description.

`>>> trade = wb.place_order_option(optionId='1017805429', lmtPrice=0.1, stpPrice=0.1, action="BUY" , orderType="LMT", quant=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Hamzo\AppData\Local\Programs\Python\Python39\lib\site-packages\webull\webull.py", line 646, in place_order_option
    raise Exception('place_option_order failed', response.status_code, response.reason)
Exception: ('place_option_order failed', 403, '')
>>> wb.get_trade_token('211180')
True
>>> trade = wb.place_order_option(optionId='1017805429', lmtPrice=0.1, stpPrice=0.1, action="BUY" , orderType="LMT", quant=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Hamzo\AppData\Local\Programs\Python\Python39\lib\site-packages\webull\webull.py", line 646, in place_order_option
    raise Exception('place_option_order failed', response.status_code, response.reason)
Exception: ('place_option_order failed', 500, '')
>>>`

**Comment by Hamze24w** [comment]
I did it exactly as you did, no luck. I got error 403 first, remember I didn't have trade token, then did it again got the same 500 error no description.
`>>> trade = wb.place_order_option(optionId='1017805429', lmtPrice=0.1, stpPrice=0.1, action="BUY" , orderType="LMT", quant=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Hamzo\AppData\Local\Programs\Python\Python39\lib\site-packages\webull\webull.py", line 646, in place_order_option
    raise Exception('place_option_order failed', response.status_code, response.reason)
Exception: ('place_option_order failed', 403, '')`

then did it again
`>>> wb.get_trade_token('XXXXX')
True
>>> trade = wb.place_order_option(optionId='1017805429', lmtPrice=0.1, stpPrice=0.1, action="BUY" , orderType="LMT", quant=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Hamzo\AppData\Local\Programs\Python\Python39\lib\site-packages\webull\webull.py", line 646, in place_order_option
    raise Exception('place_option_order failed', response.status_code, response.reason)
Exception: ('place_option_order failed', 500, '')`

**Comment by tedchou12** [comment]
@Hamze24w 
are you able to trade options via:
http://app.webull.com/
?

**Comment by Hamze24w** [comment]
actually no, I get a balance error, but on the code, there's no error description in response. I will wait for the balance to hit the account, then I'll try again. if it fixes the problem, then we'll know one thing that error 500 could be pointing at in the future :D , I'll keep you posted. thanks for baring with us.

**Comment by Hamze24w** [comment]
Hi again, Thanks Ted for you amazing commitment and effort on this api. you're the man! 
I wanted to let you know that once the balance got through to the webull account, I was able to place the trades with no problem. we now know that one the reasons for the 500 error is the balance. 
I will continue to use your amazing api for my project, and I've actually started to learn a thing or two about endpoints, I look forward to being able to contribute and help with this rep.

I do have a small side question if you may:
this function to modify option order
` def modify_order_option(self, order=None, lmtPrice=None, stpPrice=None, enforce=None, quant=0): `
can this be used to set a target and stoploss or this is for before an order gets filled ? 

Thanks again.

**Comment by schustan235** [comment]
Hey there! Amazing work on this API, loving it!

Possibly related to this thread: I read through the methods available for paper trading and did not see anything related to options and am assuming it's only possible with the live account? If that's the case no worries! Is there a way I can help out to make that happen?

If this is not the case, here's some more info:
I am getting the following error when I call place_order_option() after I initialized wb using paper_webull() which has $1,000,000 available:

> Exception: ('place_option_order failed', 405, '')

(Note: I followed both of your recommendations in this thread for formatting arguments)

**Comment by hfacey** [comment]
AFAIK, webull only allows you to paper trade securities (stocks & ETFs) available on the platform. I don't think they allow paper trading derivatives or crypto. Basically, if you couldn't do something on the webull platform, you won't be able to do it with this package either
