### ISSUE TITLE
Streaming Option Lists

### ISSUE THREAD

**Issue by sle7in** [tedchou12/webull#137]
Is there a way to subscribe to a stock option list for option contract changes? It seems the Desktop App has access to an option list stream. Trying subscribe by optionId with any level gets result code 0 and no further updates.

```python
mySym, myDate, myStrike = 'TSLA', '2021-01-15', '830'
all_opts = webull.get_options( stock=mySym, expireDate=myDate )
optionId = [opt['call']['tickerId'] for opt in all_opts if opt['strikePrice'] == myStrike][0]

conn.subscribe( optionId, level=101 ) #level 101-108
#>Connected with result code 0
#further attempts receive response> subscribe accepted with QOS: (0,) with mid: 1
```

**Comment by storrealba09** [comment]
It works for me, I think you need an OPRA subscription and use your access token to connect in order to stream options.

as : 

`conn.connect(wb._did, access_token=wb._access_token)`
