### ISSUE TITLE
Purchasing Data Question

### ISSUE THREAD

**Issue by jjanscode** [tedchou12/webull#138]
Hi Ted, I have really been enjoying the WeBull API you have built! I was wondering if you had any suggestions for how to best access some of the purchasing data displayed in the WeBull mobile app via Python (boxed in red in the below screenshot)
![Screen Shot 2021-01-15 at 9 40 42 PM](https://user-images.githubusercontent.com/76849234/104795197-81308780-577a-11eb-98a5-f7a8ba61cc6c.png)

**Comment by tedchou12** [comment]
I am glad you like them!

There are a few requests of getting additional data from webull. Unfortunately, I don't have the level 2 data on webull myself. 

I was hoping to have a video demonstrating how to look for the apis yourself, if I do finish them, feel free to take a look.

**Comment by jjanscode** [comment]
Ted, that video sounds like it would be very helpful, please let me know when you are able to get it up!

**Comment by tedchou12** [comment]
@jjanscode 
Here it is:
https://www.youtube.com/watch?v=2dz8PTMa8p0
