### ISSUE TITLE
Scraper to extract Webull market information

### ISSUE THREAD

**Issue by peymanrah** [tedchou12/webull#14]
It would be great to add a method to Webull class to extract the various ticks for Movers, gainers, and losers. This way, one can use the market information on Webull website to create a strategy for  their trading rules.

**Comment by b0b5h4rp13** [comment]
See issue #18

**Comment by b0b5h4rp13** [comment]
This can be closed, streaming quotes has been merged in

**Comment by stocknaut** [comment]
> This can be closed, streaming quotes has been merged in

But how do you use them. I'm a nub and am going crosseyed trying to figure it out.

**Comment by gamesover** [comment]
I used stream function to detect order filled. However, I found one issue, after a long time running, wubull will close stream connection from their server side. I don't know how to resolve it.
