### ISSUE TITLE
failed to get account

### ISSUE THREAD

**Issue by zml941116** [tedchou12/webull#141]
Hi, the get_account function returns the following, any idea why?

{'msg': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Long\'; nested exception is java.lang.NumberFormatException: For input string: "None"',
 'traceId': 'd5a0f41485104c8c9d015c287549e5cf',
 'code': '400',
 'success': False}

**Comment by zml941116** [comment]
I reminded myself that I opened a Hongkong market account yesterday under the same email, could that be the reason?

**Comment by jfuruness** [comment]
I have this issue and have yet to find a fix
