### ISSUE TITLE
Modifying existing order

### ISSUE THREAD

**Issue by mrazum** [tedchou12/webull#15]
Hello,
Does anybody tried subj?

When I'm trying:
response = requests.put('https://tradeapi.webulltrade.com/api/trade/order/' + self.account_id + '/modifyStockOrder/' + str(orderId), data=data, headers=headers)

I'm getting:
'Service is not available,please try again later'

Thank you

**Comment by knurts** [comment]
We're you outside the 4am to 8pm ET time allowed for using webulls service?

**Comment by mrazum** [comment]
It doesn't matter when. And manually it works any time.
Thank you.

**Comment by tedchou12** [comment]
@mrazum 
Thank you for the report, let me give this a try.

**Comment by mrazum** [comment]
I understood why.
Must be:
json=data,
Instead of:
data=data,

**Comment by gamesover** [comment]
kindly refer to https://github.com/tedchou12/webull/pull/40
