### ISSUE TITLE
mfa for phone number

### ISSUE THREAD

**Issue by webulldev** [tedchou12/webull#157]
Hi Ted,

I am having issue getting the mfa by using get_mfa with mobile number. I have had a look your other issue, you have mentioned that mfa_update can be used instead. However, I can't locate any function/endpoint called mfa_update.

Could you please kindly advise and provide an example?

Thanks so much. 

Hi Ted again,

Followed by my issue mentioned above, I have managed to get the mfa pin by calling get_mfa. However, when I ran the login method below:

          wb.login(webull_email, webull_password, 'webull login test', '118171')

I received the following error:

           {'msg': 'System error.', 'traceId': 'XXXXXXXXXXXXXXXXXXXXXXXXX', 'code': 'system.error'}

If I run wb.login(webull_email, webull_password), I do get "extInfo" back which contain info such as 'detinationphone', 'email', 'account' etc... I tried the following:

            wb.login(webull_email, webull_password)
            token = wb.get_trade_token('trading pin here')
            print (token)

I received 'False' from get_trade_token

Please note that I am already logged in to the webull website during development , running under Windows and using the latest version of python and idna 2.9. I have tried the get_quote function and it works fine.

Please kindly advise what to do with the Login function.

Thanks.

**Comment by cliu18** [comment]
I have seen the same issue today. If you login your account on a new device via browser, you would noticed that they added a new step which asks a security question after inputting MFA code. I think that is why we can not retrieve the credentials by only sending MFA code to the server. We need to add that new step to this library too.

**Comment by tedchou12** [comment]
Thanks @cliu18 
Yes, I remember that with Email MFA, it was alright. But for Mobile MFA, after you input the 6digits from SMS, you are required to verify your  birthday. 

I recommend to use the Email MFA instead. If I have some time, I will look into the Mobile MFA.

**Comment by webulldev** [comment]
Hi Ted,

Thanks for your reply.

I tried get_mfa with email rather than mobile. I received 6 digits verification code via email. I then use the login function as following:

      wb.login(webull_email, webull_password, 'webull login test', 'verification code')

I recevied the folllowing error:

       {'msg': 'System error.', 'traceId': 'XXXXXXXXXXXXXXXXXXXXXXXXX', 'code': 'system.error'}

Could you please kindly advise how to resolve this issue and could you please kindly provide an example? I am a little stuck with the login at the moment.

Thanks so much and wait to hear from you.

**Comment by tedchou12** [comment]
Interesting...
Are you able to login and use via: http://app.webull.com/
Where did you open your account? Region is US?

Are you using real account? paper account?

Are you able to trade with you account manually?

**Comment by webulldev** [comment]
Hello Ted,

Thanks for your email.

Yes, I can login and trade as normal.

Please kindly advise.

Note: I am currently using the latest version of python.

I have installed your webullmaster by python steup.py install. After that, I use Visual studio.NET to create a python project, I then include your webulllmaster folder in the project. I then managed to get_mfa via email. Once I received the code, I tried the login function as mentioned previously. Pls note that I can call get_quote function without any issue and the right data was returned. 

Thanks. Pls kindly advise.

**Comment by cliu18** [comment]
> Thanks @cliu18
> Yes, I remember that with Email MFA, it was alright. But for Mobile MFA, after you input the 6digits from SMS, you are required to verify your birthday.
> 
> I recommend to use the Email MFA instead. If I have some time, I will look into the Mobile MFA.

Now they would ask for the answer of a security question if you use Email MFA. They just changed it yesterday.

**Comment by tedchou12** [comment]
@cliu18 
Thanks, yes, I didn't realize that, thanks for the update!
Looks like this is the endpoint: `Request URL: https://userapi.webullfintech.com/api/user/risk/checkAnswer`
```
{
account: "email@example.com"
accountType: "2"
answerList: [{questionId: "1001", answer: "XXXX"}]
event: "PRODUCT_LOGIN"
}
```

**Comment by tedchou12** [comment]
What questions do you have? Is it the birthday question? `1001`

**Comment by cliu18** [comment]
They just ask one of the security questions I chose when I setup my account. like 'what is your first pet?' or 'who is your favour teacher?'

**Comment by cliu18** [comment]
you can get the question via this function
`    def get_security_question(self, username):
        u = urllib.parse.quote_plus(username)
        url = f'https://userapi.webullfintech.com/api/user/risk/getSecurityQuestion?account={u}&accountType=2&event=PRODUCT_LOGIN&v={round(time.time()*1000)}'
        response = requests.get(url, headers=self._headers)
        return response.json()`

**Comment by webulldev** [comment]
Sorry for the late reply. Thanks ted and cliu18.

I will give it a try and let you know.

**Comment by tedchou12** [comment]
@webulldev 
I have updated the package, there is already MFA so I am pretty sure is secure enough, but Webull is just starting to make things troublesome with security questions in there:
1. Get MFA and Security Questions
```
wb = webull()
wb.get_mfa('test@example.com')
print(wb.get_security('test@example.com'))
```

> True
> [{'questionId': '1001', 'questionName': "What's your birth month and day?"}]
# the question may be different for you when you setup your account

2. Login
```
cred = wb.login('test@example.com', 'P@ssw0rd!!!!!!', 'testing', 'AAAAAA', '1001', 'XXXX') #AAAAA should be your MFA Code, XXXX should be your security question answer. 1001 should be the questionId.
print(cred)
```
> {'extInfo': {'userPwdFlag': '1'}, 'accessToken': 'dc_us1.188753a38e6-00000000000000000000', 'uuid': '00000000000000000000', 'refreshToken': '188753a38e6-00000000000000000000', 'tokenExpireTime': '2021-04-07T02:44:53.606+0000', 'firstTimeOfThird': False, 'registerAddress': 169, 'settings': {'id': 945512120531417760, 'userId': 311431178, 'regionId': 169, 'language': 'en', 'focusMarketId': '2,3,4,5,6,14', 'theme': 2, 'increDecreColor': 2, 'fontSize': 'M', 'portfolioDisplayMode': 2, 'portfolioNameNewline': 1, 'portfolioHoldingsDisplay': 1, 'portfolioIndexDisplay': 1, 'portfolioBulletin': 1, 'kdata': 1, 'refreshFrequency': 1, 'shock': 0, 'tickerPriceRemind': 1, 'orderDealRemind': 1, 'hotNews': 1, 'chartOption': 2, 'operateTime': '1969-12-31T00:00:00.000+0000', 'languageUpdateTime': '1970-01-01T00:00:00.000+0000', 'createTime': '2018-09-15T05:18:25.000+0000', 'updateTime': '2018-09-15T05:18:25.000+0000'}}

would give you the accessToken and refreshToken like before.

**Comment by webulldev** [comment]
Hi Ted,

Thanks so much. 

i will give it a try over the weekend and will let you know.

**Comment by jfuruness** [comment]
To help out others, if you got the birthday question, you should pass in your birthday as a string in this format. For Example, if your birthday was October 12th: 1012 (NOT: 10/12)

**Comment by webulldev** [comment]
Hi Ted,

I have tried it again. and received the following error:

{'msg': 'Service is not available,please try again later', 'traceId': 'xxxxxxxxxxxxxxxxxxxxxxx', 'code': '500'}

Could you please kindly advise?

thanks.

**Comment by tedchou12** [comment]
@webulldev 
Interesting...
Have you got the latest package installed?
If not, please download it directly from github and do `python3 setup.py install`, I just updated the login function this weekend. 

Are you able to login to app.webull.com ? 
What security question do you see? Are you sure is the birthday question? What answer did you give? as jfuruness mentioned, the format has to be 0101 not 01/01.

If those don't help, I cannot know the reason, I can only take a look at how you login in person.

**Comment by webulldev** [comment]
Thanks for your reply.

I have installed the latest version.

I am able to login webull.com.

I get the following security question
[{'questionId': '1001', 'questionName': "What's your birth month and day?"}]

I have passed the format as 0101.

Thanks and pls kindly advise.

**Comment by tedchou12** [comment]
@webulldev 
Interesting...
unfortnately, I cannot debug...
If you want, you can contact me via my skype account, I can take a look.
I am also interested in what is causing this problem.

**Comment by webulldev** [comment]
Hi Ted,

Thanks for your reply. Sounds good. Could you please send me your skype ID?

**Comment by tedchou12** [comment]
ted.chou12@gmail.com

**Comment by cliu18** [comment]
I don't think this library can work on a new webull account now. I recently create a new account on webull(1 month ago). While this library works very smooth on my old account, I can never get the account info or place an order on my new account. (Yes. I can get the access token and refresh access token on my new account.) I also discovered that my new webull account cannot work on their ubuntu desktop app(I can login, but it would not show account id  either you can not make any order) while my old account can work very well on it. Any new user met the same issue? @webulldev When did you open your webull account?

**Comment by shamssheikh** [comment]
![image](https://user-images.githubusercontent.com/14261211/107859959-1bc3cb00-6dfa-11eb-9d90-e2d90c1e1984.png)

I think its because of the URL change. Base URL has changed?

**Comment by cliu18** [comment]
@shamssheikh Thanks for sharing it. I tested it with my new account but it still return 500 when I call account() function. It is so weird that these APIs can only work on an old account rather than a new account.

**Comment by tedchou12** [comment]
cc @webulldev 
The security question is more complicated than I thought.
I don't have it setup, so I don't face the issue, if you know how to setup, please let me know.

In addition, I am interested to give it a try, if you have a troubled account and you are only using it as a test account, I appreciate if you can lend me the account for testing and debugging, I think it will make debugging a lot easier.

If anyone is interested, please Email me privately. (I am not always very responsive, getting busy lately.)

**Comment by bjacobo20** [comment]
I keep getting the error message below:
 {"msg": "user security question expired", "traceId": "#", "code": "user.security.question.expired"}

my code is:
    wb.get_mfa('email') 
    code = input('Enter MFA Code : ')
    print(wb.get_security('email'))
    loginInfo = wb.login('email', 'password', 'test',code, '1001','answer to security question') 
    f = open("token.txt", "w")
    f.write(json.dumps(loginInfo))
    f.close()

I get the birthday question and I made sure to put the correct format. For example, 0205 (for 2/5). 

Any help would be appreciated.

**Comment by jfuruness** [comment]
I would imagine you are answering the question too slowly (thus, the expired).

**Comment by tedchou12** [comment]
I don't have a new account (which seems to be the only case that is having login issues).

If you are interested to place orders or check your portfolio positions, I recommend going without the login procedure.

https://github.com/tedchou12/webull/wiki/Workaround-for-Login

**Comment by bjacobo20** [comment]
@tedchou12 I tried doing that method but the response box is empty. Do I need to go to a specific page on webull?

**Comment by haddadianhamed1** [comment]
+1 workaround account response is empty. and security question is not working for me either

**Comment by PageMastr** [comment]
https://github.com/tedchou12/webull/pull/186

This should resolve the issues.
