### ISSUE TITLE
place_order returns json decoder error

### ISSUE THREAD

**Issue by Intradyne** [tedchou12/webull#158]
```
wb.place_order(qty=1, price=10.0, action='buy', tId=913254559)

C:\ProgramData\Anaconda3\lib\site-packages\webull\webull.py in place_order(self, stock, tId, price, action, orderType, enforce, qty, outsideRegularTradingHour)
    332 
    333         response = requests.post(self._urls.place_orders(self._account_id), json=data, headers=headers)
--> 334         return response.json()
    335 
    336     def place_order_crypto(self, stock=None, tId=None, price=0, action='BUY',

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    896                     # used.
    897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
    899 
    900     @property

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    355             parse_int is None and parse_float is None and
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:
    359         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Intradyne** [comment]
I was getting this error starting maybe a month ago but gave up on it for a while, just did a fresh install of windows and still cant get this to work, 

any more information I can provide?

**Comment by tedchou12** [comment]
```
wb.place_order(qty=1, price=10.0, action='buy', tId=913254559)
```
We have updated from quant to qty, how did you get the package installed? pip install?

I haven't update the pypi for a while, may be downloading straight off from Github and do `python3 setup.py install` would be better. 
Seems like the output isn't in Json, after you get the updated install, let me know again.

**Comment by Intradyne** [comment]
I did install from pip, would appreciate it if you could update taht pypi package but I will be sure to install from the repo

**Comment by tedchou12** [comment]
@Intradyne Thanks. I updated the package eariler today, you can try pip install again, I think the newest updates should be there.

**Comment by Intradyne** [comment]
now running 0.3.3 as installed via pip

wb.place_order(quant=1, price=10.0, action='buy', tId=913254559)
`
wb.place_order(quant=1, price=10.0, action='buy', tId=913254559)
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-10-76d0fb5613e2> in <module>
----> 1 wb.place_order(quant=1, price=10.0, action='buy', tId=913254559)

C:\ProgramData\Anaconda3\lib\site-packages\webull\webull.py in place_order(self, stock, tId, price, action, orderType, enforce, quant, outsideRegularTradingHour, stpPrice, trial_value, trial_type)
    432 
    433         response = requests.post(self._urls.place_orders(self._account_id), json=data, headers=headers)
--> 434         return response.json()
    435 
    436     def modify_order(self, order=None, price=0, action=None, orderType=None, enforce=None, quant=0, outsideRegularTradingHour=None):

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    896                     # used.
    897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
    899 
    900     @property

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    355             parse_int is None and parse_float is None and
    356             parse_constant is None and object_pairs_hook is None and not kw):
--> 357         return _default_decoder.decode(s)
    358     if cls is None:
    359         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by tedchou12** [comment]
@Intradyne 
Do you have enough cash in the account to place the trade?
Are you able to place trades with app.webull.com Web interface?

**Comment by darkmarauder0** [comment]
I'm experiencing the same issue. Tried 4 separate machines. All different operating systems, Raspberian, Mac Mojave, Windows 10, and Ubuntu. I've also tried pip install and git clone install. Unfortunately, I haven't been able to figure this one out. Plenty of cash to trade. I'm also able to make trades via app.webull.com. Any pointers would be greatly appreciated.

>>> wb.place_order(stock=ticker_input, price=ask, quant=Quantity)
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/webull-0.3.3-py3.7.egg/webull/webull.py", line 442, in place_order
    return response.json()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

>>> wb.place_order(stock=ticker_input, price=ask, quant=41)
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/webull-0.3.3-py3.7.egg/webull/webull.py", line 442, in place_order
    return response.json()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

>>> wb.place_order(stock=ticker_input, price=1.19, quant=41)
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/webull-0.3.3-py3.7.egg/webull/webull.py", line 442, in place_order
    return response.json()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

>>> wb.place_order(stock='NAKD', price=1.19, quant=41)
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/webull-0.3.3-py3.7.egg/webull/webull.py", line 442, in place_order
    return response.json()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

>>> wb.place_order(stock='NAKD', price='1.19', quant='41')
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/webull-0.3.3-py3.7.egg/webull/webull.py", line 442, in place_order
    return response.json()
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>>

**Comment by darkmarauder0** [comment]
I was able to resolve my issue. I believe this issue is related to issue #177. After trying a few basic operations like get_account, etc, I realized I wasn't logged in. Browsed the other issues and found that #177 was my problem. I changed my login procedure to use the session token and I set the account id in my code. All seems well after those changes. 

wb = webull()
fh = open('webull_credentials.json', 'r')
credential_data = json.load(fh)
fh.close()

wb._refresh_token = credential_data['refreshToken']
wb._access_token = credential_data['accessToken']
wb._token_expire = credential_data['tokenExpireTime']
wb._uuid = credential_data['uuid']

n_data = wb.refresh_login()

credential_data['refreshToken'] = n_data['refreshToken']
credential_data['accessToken'] = n_data['accessToken']
credential_data['tokenExpireTime'] = n_data['tokenExpireTime']

file = open('webull_credentials.json', 'w')
json.dump(credential_data, file)
file.close()

wb._account_id = ********
