### ISSUE TITLE
'AccessToken is expire' when making API call 5 seconds after logging in

### ISSUE THREAD

**Issue by epalcu** [tedchou12/webull#159]
So I'm coming across an error when using the paper account. Below are my steps:

- Log into Webull with username and password
- Wait for 5 seconds
- Make an API call, i.e. get_account()
- Get error: {'msg': 'AccessToken is expire', 'traceId': '97fa2cd73aff4ee998f42ca42e6e770e', 'code': 'auth.token.expire', 'success': False}

Below is my code:
```
if __name__ == '__main__': 
    wb = paper_webull()
    wb.login('<username>', '<password>')
    time.sleep(5)
    
    for d in wb.get_account()['accountMembers']:
        if (d['key'] == 'usableCash'):
            print(float(d['value']))
```

Any idea why it is failing? This consistently happens when I try to make API calls after logging in. If I don't make the calls fast enough, they all fail.

**Comment by epalcu** [comment]
Hmm, I received emails from Webull locking my account for some time. It looks like they lock the account if you log in too many times - al the more reason to leverage the refresh tokens. I'll update in a few hours if this is the actual.

**Comment by tedchou12** [comment]
Yes, it is recommended that you save the refreshtoken and use that: https://github.com/tedchou12/webull/wiki/MFA
As for waiting for 5 seconds... I suspect waiting 5 seconds would change anything, is kind of weird for any service not able to process but only after waiting 5 seconds.

**Comment by epalcu** [comment]
I was just using 5 seconds as a test, but most of my following requests were performed sooner than that and would still fail. But I just verified that it was because my account was locked that it kept failing after logging in - also, refresh tokens saved the day.
