### ISSUE TITLE
are there any docs for webull api?

### ISSUE THREAD

**Issue by 0xYasser** [tedchou12/webull#16]
I want to help building this repo, but I could't find any docs for webull API, can anyone link me?

**Comment by knurts** [comment]
I have not found any. I use browser developer tools to export an http archive file (.har) and then use https://github.com/JustusW/harparser to dump out the requesting url, the request headers, and request data. I can make a public version of this if interested. Then I use a dictionary walker to learn the response's content text structure. 
Like Ted says in the README, none of these are officially supported by Webull. :/

**Comment by knurts** [comment]
something like this... wish they would just have an official API!
https://github.com/knurts/har_parse_requests
