### ISSUE TITLE
Get Quote not working

### ISSUE THREAD

**Issue by prague2020** [tedchou12/webull#160]
Your API is awesome and I am truly grateful you took the time to write it. I will definitely buy you a coffee. One challenge I am having is getting a valid stock quote back.

print(wb.get_quote(stock='AAPL'))

Results in the following error:

ValueError                                Traceback (most recent call last)
<ipython-input-21-fdacabab4f5c> in <module>
----> 1 print(wb.get_quote(stock='AAPL'))

C:\Anaconda\lib\site-packages\webull\webull.py in get_quote(self, stock, tId)
    445                 tId = str(self.get_ticker(stock))
    446             except ValueError as _e:
--> 447                 raise ValueError("Could not find ticker for stock {}".format(stock))
    448         response = requests.get(self._urls.quotes(tId))
    449         result = response.json()

Any ideas?

**Comment by tedchou12** [comment]
Thank you for liking the project!

It seems like `get_ticker(stock)` didn't respond a valid json.

Could you try calling:
`print(wb.get_ticker('AAPL'))`

And we can take a look at the output?

**Comment by prague2020** [comment]
Same result


#result = wb.get_quote('Bitcoin')

result = wb.get_ticker('AAPL')

print(result)

---------------------------------------------------------------------------ValueError
                               Traceback (most recent call
last)<ipython-input-10-6f4a514b6bc6> in <module>      1 #result =
wb.get_quote('Bitcoin')----> 2 result = wb.get_ticker('AAPL')      3
print(result)
C:\Anaconda\lib\site-packages\webull\webull.py in get_ticker(self,
stock)    267             result = response.json()    268
if result['hasMore'] == False:--> 269                 raise
ValueError('TickerId could not be found for stock {}'.format(stock))
 270             elif result['list']:    271                 for item
in result['list']: # implies multiple tickers, but only assigns last
one?
ValueError: TickerId could not be found for stock AAPL

**Comment by hfacey** [comment]
you need  to update to the latest version of this package. based on the code referenced in the error (`if result['hasMore'] == False`) you're running a version that hasn't been updated since July last year.

**Comment by tedchou12** [comment]
@hfacey 
Thank you for pointing that out! Yes, I need to update the package on pypi.

@prague2020 
Yes, sorry, I haven't been updating the pypi package very frequently, can you download the package in github and do this install instead: `python3 setup.py install`?

**Comment by prague2020** [comment]
Yes it worked fantastically. Thanks Ted!
