### ISSUE TITLE
Webull is not remembering my device after MFA authentication 

### ISSUE THREAD

**Issue by TreborNamor** [tedchou12/webull#162]
hello, I am having trouble staying logged in my webull account. My login attempt fails when I use this command.

Attempt 1:
```
wb = webull()
login_attempt = wb.login('test@test.com', 'pa$$w0rd')
print(login_attempt)

output: {'msg': 'login failed.', 'traceId': '62bb81743a047a95c73daf5', 'code': 'app.device.control'}
```

I can only login webull by doing MFA with auth code but the auth code only last 30 minutes. It seems to me when I use the auth code it will login but doesn't remember the device. So when I go and try the first attempt again it fails. Even though I already authenticated myself.

Attempt 2:
`wb.get_mfa('test@test.com')`

then typing,

```
wb = webull()
login_attempt = wb.login('test@test.com', 'pa$$w0rd', 'my_computer', 'auth_code_here')
print(login_attempt)

output: {'msg': 'login success.'}
```

**Comment by tedchou12** [comment]
I see. 
I am guessing is part of Webull's API specification.
After some trial and errors, I recommend to keep the AccessToken and RefreshToken saved and use those to access your account later, RefreshToken will be refreshed if you use the API within 90 days, so ideally you will never need to login again.

**Comment by TreborNamor** [comment]
90 days of not logging in sounds good to me. Can you give me a small template to follow when using this RefreshToken function?

**Comment by tedchou12** [comment]
`credentials_webull.json` should contain the credential data that you first login from `wb.login()`, and you should save new refresh token to `credentials_webull.json` after you successfully call `refresh_login()`


```
file = open('credentials_webull.json', 'r')
data = json.load(file)
file.close()

webull._refresh_token = data['refreshToken']
webull._access_token = data['accessToken']
webull._token_expire = data['tokenExpireTime']
webull._uuid = data['uuid']

n_data = webull.refresh_login()
data['refreshToken'] = n_data['refreshToken']
data['accessToken'] = n_data['accessToken']
data['tokenExpireTime'] = n_data['tokenExpireTime']

file = open('credentials_webull.json', 'w')
json.dump(data, file)
file.close()

webull.get_account_id()
webull.get_trade_token(webull_token)
webull._account_id = webull.get_account_id()

account = webull.get_account()
```

**Comment by zhujiacn** [comment]
When I call get_security, I receive:
[{'questionId': '1001', 'questionName': "What's your birth month and day?"}]

But then I receive the following response from login after adding security question id and answer:
{'msg': 'user security question expired', 'traceId': '7f2720b72b81406194f65993d9b8e0a0', 'code': 'user.security.question.expired'}

**Comment by tedchou12** [comment]
@zhujiacn 
Hi there, can you give this a try?

`print(check_security(username='', question_id='1001', question_answer='0101'))  #change username to your username, 0101 to your birthday`

What does this give you?
If you login to app.webull.com from a new computer, what security question do you get?

**Comment by zhujiacn** [comment]
I figured it out. using the following endpoint will get me correct security question:

    def get_security(self, username, account_type, region_code, event) :
        return f'{self.base_userfintech_url}/user/risk/getSecurityQuestion?account={username}&accountType={account_type}&event={event}&v={datetime.now().timestamp()*1000}'

**Comment by tedchou12** [comment]
thank you! Interesting... I don't see the v variable in my account.
Let me monitor more.

**Comment by tedchou12** [comment]
merged
https://github.com/tedchou12/webull/pull/165
