### ISSUE TITLE
Can't get account info or place orders

### ISSUE THREAD

**Issue by jfuruness** [tedchou12/webull#167]
I login as normal with the new security question and it seems to work. I get this:

```
{'extInfo': {'userPwdFlag': '1'}, 'accessToken': 'dc_us1.177833646f6-9b9ad0696c6c44ba95b3f96ced06219e', 'uuid': '171e1e7d3471186772a60084e37bb5aca0c565436b1', 'refreshToken': '177833646f6-239870958919481
6b5d817f7e525a76e', 'tokenExpireTime': '2021-04-09T19:55:08.406+0000', 'firstTimeOfThird': False, 'registerAddress': 6, 'settings': {'id': 311163117675753472, 'userId': 302227079, 'regionId': 6, 'languag
e': 'en', 'focusMarketId': '2,3,4,5,6,14', 'theme': 2, 'increDecreColor': 2, 'fontSize': 'M', 'portfolioDisplayMode': 2, 'portfolioNameNewline': 1, 'portfolioHoldingsDisplay': 1, 'portfolioIndexDisplay':
 1, 'portfolioBulletin': 1, 'kdata': 1, 'refreshFrequency': 1, 'shock': 0, 'tickerPriceRemind': 1, 'orderDealRemind': 1, 'hotNews': 1, 'chartOption': 2, 'operateTime': '1969-12-31T00:00:00.000+0000', 'la
nguageUpdateTime': '1970-01-01T00:00:00.000+0000', 'createTime': '2020-05-04T22:56:38.000+0000', 'updateTime': '2020-05-04T22:56:38.000+0000', 'listStyle': 1}}
```
I then get my trade token, which returns as True.
However, when I try to get my account info this error occurs:
```
{'msg': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Long\'; nested exception is java.lang.NumberFormatException: For input string: "None"', 'traceId': '86f055c3ee11
4c0783e1cb896f66c3af', 'code': '400', 'success': False}  
```
Any help would be greatly appreciated. I'm using the 0.3.3 version of the repo.

**Comment by jfuruness** [comment]
Interestingly, this error only seems to occur on the paper account (but not on the normal account). Please advise.

**Comment by jfuruness** [comment]
it appears that the paper_place_order is getting the account id of None

**Comment by jfuruness** [comment]
it seems to be in this function:
```
    def get_account_id(self):
        ''' Get paper account id: call this before paper account actions'''

        headers = self.build_req_headers()
        response = requests.get(self._urls.paper_account_id(), headers=headers)
        result = response.json()
        if result is not None and 0 in result:
            id = result[0]['id']
            self._account_id = id
            return id
        else:
            return None
```

It looks like the if statement should not have the: 0 in result. The result returns just fine, but it doesn't have a 0 in it because it is a list.

**Comment by jfuruness** [comment]
can't seem to figure out how to fork or anything like that but that's the fix whenever you want to make it

**Comment by tedchou12** [comment]
sure, I will add that .

**Comment by jfuruness** [comment]
thnx

**Comment by tedchou12** [comment]
Interesting...
https://github.com/tedchou12/webull/pull/164
Seems like is been referenced here. Anyways, I will check again tonight.

**Comment by hfacey** [comment]
hey @jfuruness. 
- It's bad form to post your access token, even if expired
- That code snippet of the function, did you get that from your local version of webull that ran, or from the remote here on github? I submitted #164 after the version was last updated to `0.3.3`, so you may not be running the latest locally.
- The code with zero is fine once the request was successful because this is what a successful response looks like for paper:
```
 [
    {
        "id": 1234567,
        "paperId": 1,
        "status": 0,
        "paperType": 0,
        "paperName": "Paper Trading",
        "paperTickerPoolCode": "wb_week",
        "currency": "USD",
        "currencyId": 247,
        "supportOutsideRth": true,
        "timeInForces": [
            "DAY",
            "GTC"
        ],
        "orderTypes": [
            "MKT",
            "LMT"
        ]
    }
]
```
So python converts it to a list of dict, with only one element in the list, hence the `result[0]`.
- It seems though that the request itself was unsuccessful as your code returned a `400` error

**Comment by hfacey** [comment]
i see the issue. Will fix right away
