### ISSUE TITLE
Logging in with 2 python codes to the same account on the same computer

### ISSUE THREAD

**Issue by Hamze24w** [tedchou12/webull#172]
Hi, I have a Trader bot and a Closer Bot that are supposed to work independantly. 
but whenever they are both running, one of them is logged out of webull and gets unauthorized user error. 
is there a way to fix this ?

**Comment by tedchou12** [comment]
To my knowledge and experience, that hasn't happened to me before.
But I am not 100% sure of the specification of webull so I can't guarantee you that it shouldn't happen.

Do you want to try giving two scripts **two** did.bin and executing them simultaneously? Perhaps webull might think is two separate devices.

**Comment by Hamze24w** [comment]
Hi again, I tried giving it 2 did.bin by using get_did on 2 different locations and it created one for each. still having the problem. 
are you aware if webull has a rule of maximum logins at the same time ? 
I tried making the device name different as well ( the 3rd parameter of the login) , no luck.

**Comment by PageMastr** [comment]
> Hi again, I tried giving it 2 did.bin by using get_did on 2 different locations and it created one for each. still having the problem.
> are you aware if webull has a rule of maximum logins at the same time ?
> I tried making the device name different as well ( the 3rd parameter of the login) , no luck.

1 login per device at a time. It overwrites the previous logged in bot Auth Tokens, so when that bot goes to update its token, it gets logged out, because it thinks the device already re-authed. I would reccomend, making your bots share one login instance, and routing their requests through it so you can use multiple bots. Unfortunately theres no other way to bypass this restriction as there is no official API, so we cant communicate to webull that they are two different applications and should thus have their own tokens.

**Comment by Hamze24w** [comment]
> > Hi again, I tried giving it 2 did.bin by using get_did on 2 different locations and it created one for each. still having the problem.
> > are you aware if webull has a rule of maximum logins at the same time ?
> > I tried making the device name different as well ( the 3rd parameter of the login) , no luck.
> 
> 1 login per device at a time. It overwrites the previous logged in bot Auth Tokens, so when that bot goes to update its token, it gets logged out, because it thinks the device already re-authed. I would reccomend, making your bots share one login instance, and routing their requests through it so you can use multiple bots. Unfortunately theres no other way to bypass this restriction as there is no official API, so we cant communicate to webull that they are two different applications and should thus have their own tokens.

Correct, either that or put each on it's own VPS if you got VPSs to spare :D. 
Thanks.

**Comment by PageMastr** [comment]
Closing Issue as it does not fall within the possible scope of the API at this time.
