### ISSUE TITLE
Level 2 data - get live data?

### ISSUE THREAD

**Issue by r1997mysm** [tedchou12/webull#174]
Hi. Just wondering if you guys have tried getting level 2 data from webull api? - suppose that my account is subscribed to webull level 2 data package. I would think that getting historical level 2 data is impossible, but any chance I could record it live and build my own dataset for that?

**Comment by hfacey** [comment]
[get_quote](https://github.com/tedchou12/webull/blob/a30593fe4670a18e86da47a2e9d933277e594d86/webull/webull.py#L378) should return level 2 data is your account is subscribed
