### ISSUE TITLE
Share Webull Rest API Documentation 

### ISSUE THREAD

**Issue by nerkka** [tedchou12/webull#175]
It will be nice if you can share the raw Webull REST API documentations so that we can build our own Webull API client in different languages.

**Comment by hfacey** [comment]
:sweat_smile: that would be great. but remember that webull is closed source. This is **_not_** an official API. Every API call in this library is the result of someone just looking at the network calls that webull app/frontend makes to their servers and mimicking the behavior. Webull can, and does change their APIs as they see fit (and we've seen that happen a lot recently).

**Comment by tedchou12** [comment]
Thanks for the comment. As hfacey mentioned. If we start maintaining the REST API, we would need to maintain two separate locations. It would be double the work. In addition, you will need to update your client accordingly after we update the documents here, the lead time is unthinkable.

If you really want, you can setup this package and making the outputs from your client to the inputs of this package, if this package updates, just update the package on your machine without much changes to your client.

**Comment by nerkka** [comment]
@tedchou12 @hfacey 
Your comments make sense, but if you like to make this repo more powerful, I'd suggest to take a look at OpenAPI spec (such as Swagger). You write API specs in yaml, and they have tools to generate code in different languages, so both API spec and code can be maintained in a single place. 

Just a recommendation, but this repo is very helpful for me to develop my own Webull API Client in Java.

**Comment by hfacey** [comment]
No, I get it. I wrote my own version for GoLang and I thought of writing a swagger spec as well to make it easy on myself and just autogenerate the client. But going thru the webull API was a mess. Their APIs are really muddled. They use different domains (and subdomains) for different APIs in a way that doesn't make sense to me, APIs require very different headers (ranging from no auth needed, to auth, to auth + security token), and sometimes the same API returns different results on success. It's hard to write a swagger spec when you're reverse engineering an API. I became convinced that anything I came up being broken so I just wrote the Go client myself. But please, if you have time, please try it - it would help a lot.

**Comment by nerkka** [comment]
Thanks for your clarification.

**Comment by friksa** [comment]
I would love to write an Angular app that provides advanced features for your WeBull account... so it would be nice if there was a rest api that can be used.

**Comment by TwilightTime7734** [comment]
@nerkka I am also trying to write the API's for Java, specifically for an Android apk I wrote, I am currently using TD Ameritrade's API's which took me awhile to figure out. TDA is killing me with their "MANDATORY REORGANIZATION FEE" fees and I would really love to move over to Webull. Any help or insite you could provide me would be appreciated. If I get it figured and could help you I will for sure. Thanks

**Comment by aggelako** [comment]
Is there any documentation for the login API? Also did anyone manage to get it working with Java? Im trying to "translate" but the requests wont work and i cant really debug what's wrong with the request with no Docs
