### ISSUE TITLE
Error Fetching account info 'secAccountID'

### ISSUE THREAD

**Issue by PageMastr** [tedchou12/webull#177]
Im at a complete loss here, have no clue whats going on as im using the default example.

My Code:
```
from webull import webull
from webull import paper_webull

#global variables
islive = 0
ver = '0.01'

#Login 
wb = webull()
wb.login('email@email.com', 'password')
wb.get_trade_token('123456')
wb.get_account_id()_
```
ERROR Message:
```
 D:\Users\thepa\source\repos\WeBot Trade Tool>python WeBot_Trade_Tool.py
Traceback (most recent call last):
  File "D:\Users\thepa\source\repos\WeBot Trade Tool\WeBot_Trade_Tool.py", line 25, in <module>
    wb.get_account_id()
  File "C:\Users\thepa\AppData\Local\Programs\Python\Python39\lib\site-packages\webull\webull.py", line 263, in get_account_id
    id = str(result['data'][0]['secAccountId'])
KeyError: 'secAccountId'
```

**Comment by tedchou12** [comment]
@PageMastr 
Is likely that the login is not successful.

```
from webull import webull
from webull import paper_webull

#global variables
islive = 0
ver = '0.01'

#Login 
wb = webull()
cred = wb.login('email@email.com', 'password')
print(cred)
```

Try this and see the cred output to see what is the result of login.

**Comment by PageMastr** [comment]
![6](https://user-images.githubusercontent.com/9737536/108473989-5c856f00-7254-11eb-8381-d3108986b92b.PNG)
@tedchou12  looks succesful to me, its definitley my info.

**Comment by PageMastr** [comment]
ok So tried changing the password so it was incorrect to see what a failed login looked like, and it gave the same response with my plain text phone number and plain text email.

**Comment by PageMastr** [comment]
Potentially found the issue, I also have an IRA, so i guess i have Two accounts, How do i Select the proper one in the code?
![Capture](https://user-images.githubusercontent.com/9737536/108476695-f7cc1380-7257-11eb-8965-55bf7f3fd794.PNG)

**Comment by tedchou12** [comment]
Interesting!

You can do 
wb._account_id = ....

**Comment by tedchou12** [comment]
Is your account a new account?

**Comment by PageMastr** [comment]
erm define new, its a couple weeks to a month old, im not 100% sure how
long ive had it.

**Comment by PageMastr** [comment]
wb._account_id = ....

This solved the issue
