### ISSUE TITLE
Real account cannot grab account details (paper works)

### ISSUE THREAD

**Issue by shailesh9r** [tedchou12/webull#178]
Hi I recently created the account, and realized endpoint url needs update. Somehow I see for people, old account works still fine (mysterious). Here is what I did 

changed self.base_trade_url = 'https://tradeapi.webullbroker.com/api/trade' to self.base_trade_url = 'https://ustrade.webullfinance.com/api/trade' and 
to v5 for 
def account(self, account_id):
return f'{self.base_trade_url}/v5/home/{account_id}', 
but now I get following error : {'msg': 'Your session has expired, please login again.', 'traceId': 'XXX', 'code': 'trade.token.expire', 'data': {}, 'success': False} . 
Any idea how to fix this now?

Appreciate any help!

**Comment by tedchou12** [comment]
If you are having trouble for login, you can directly get the accesstoken and refreshtoken without login.
https://github.com/tedchou12/webull/wiki/Workaround-for-Login

**Comment by shailesh9r** [comment]
> If you are having trouble for login, you can directly get the accesstoken and refreshtoken without login.
> https://github.com/tedchou12/webull/wiki/Workaround-for-Login

There is no issue with login. Modules are executing properly where account details are not needed (example account activities). But get_account is not working. 

I saw people saying new accounts have these issues while old ones are still working...any ideas?

**Comment by shailesh9r** [comment]
I tried directly using the token from website and work without logging in. Again, paper account worked (it could fetch account details), but real account gave same error:

{'msg': 'Your session has expired, please login again.', 'traceId': 'XXX', 'code': 'trade.token.expire', 'data': {}, 'success': False} .

Stuck here :(

**Comment by Avinashkn** [comment]
@tedchou12 It works after changing 
def account(self, account_id):
        return f'{self.base_trade_url}/**v3**/home/{account_id}'

**Comment by Avinashkn** [comment]
@tedchou12 Is there a way to get the endpoints for all the actions? Like place order, check orders, oco etc...

**Comment by tedchou12** [comment]
> @tedchou12 Is there a way to get the endpoints for all the actions? Like place order, check orders, oco etc...

@Avinashkn 
What do you mean? Can you elaborate?

**Comment by PageMastr** [comment]
This can be closed, it is resolved with #185  and expanded with full api V5 update in pull #186

**Comment by shailesh9r** [comment]
solved after @avinaskn fix, already pulled in. Thx!
