### ISSUE TITLE
Orders Showing as Success w/ OrderID generated but not showing up in WeBull Account

### ISSUE THREAD

**Issue by mitchsanders13** [tedchou12/webull#179]
I am placing orders following the [video](https://www.youtube.com/watch?v=3w3ZNQniSbU&t=25s). When printing result I see "{'success': True, 'data': {'orderId': XXXXXXXXXXXX}}" but I don't see the order in my WeBull account. Any thoughts as to why this would be happening?

Executing this line: wb.place_order(stock='AAPL', price=130, quant=1, action='BUY')

**Comment by tedchou12** [comment]
Seems like the place_order should be successful from the return code.
Do you get anything if you run `print(wb.get_positions())`

**Comment by shailesh9r** [comment]
> Seems like the place_order should be successful from the return code.
> Do you get anything if you run `print(wb.get_positions())`

Got same issues, nothing comes out for wb.get_positions() as there is no order. Is there way to lookup order details using orderId that gets generated?

**Comment by jameschanx** [comment]
I am getting same error.  I noticed the endpoint being used on my webull account is the base_ustrade_url but the place_order method uses the base_trade_url.  I tried to swap out the base_trade_url to the base_ustrade_url but it leads to 405 error.  

In addition I get 500 error when calling wb.get_account() without any other helpful message.  My account is in the US if that makes any difference :-S

**Comment by cliu18** [comment]
@mitchsanders13 If you created your account recently, you would see this issue. I can not fix this issue either

**Comment by shailesh9r** [comment]
@tedchou12 @PageMastr any further insight into this problem?

**Comment by PageMastr** [comment]
@shailesh9r  pull #186  solves these issues as it updates the api completely to V5

**Comment by shailesh9r** [comment]
@PageMastr order not getting through is still a problem. even with fix for V5 (and V3 change in URL to get account info). I get {'success': True, 'data': {'orderId': XXXX}} but dont see any order placed. Also, do you know a way to search using order id? Order history API doesn't grab it, as it was never placed.

**Comment by shailesh9r** [comment]
Is there any other URL for API below that we can try? 

def place_orders(self, account_id):
        return f'{self.base_ustrade_url}/trade/order/{account_id}/placeStockOrder'

self.base_ustrade_url = 'https://ustrade.webullfinance.com/api'

**Comment by tedchou12** [comment]
note to myself.

1. URL changed to `https://ustrade.webullfinance.com/api/trade/order/15091957/placeStockOrder`

2. add `lzone`: `dc_core_r001` to headers.

**Comment by cliu18** [comment]
@tedchou12 Thanks. I tested it with my new account. It can place order by this library now.

**Comment by shailesh9r** [comment]
@tedchou12 @cliu18 where to add lzone?

**Comment by cliu18** [comment]
@shailesh9r https://github.com/tedchou12/webull/blob/master/webull/webull.py#L73 you can add it here

**Comment by cliu18** [comment]
@tedchou12 the lzone id is also in the response when you call get_account_id. You can find it in `result['data'][0]['rzone']`

**Comment by tedchou12** [comment]
Thanks.
I am working during the weekdays, let me update during the weekends.

**Comment by tedchou12** [comment]
Thanks, but is not the same:
`dc_core1`

**Comment by tedchou12** [comment]
sorry, @cliu18 you are right.
Is just I had two different strings for different types of accounts.

Since is already merged, I hope everyone here could test it and if anything is still causing trouble, let me know.

(Sorry, is taking a lot of time. If you like the project, feel free to be the first to support me here. https://www.buymeacoffee.com/tedchou12)

**Comment by itsjafer** [comment]
I'm on the latest version of the repo, and logging in with an account that was made somewhat recently, and getting a keyerror from this line:
`            self.zone_var = str(result['data'][0]['rzone'])
`
More specifically, `rzone` is not in the data object for me. Any ideas on what the issue might be?

**Comment by PageMastr** [comment]
> I'm on the latest version of the repo, and logging in with an account that was made somewhat recently, and getting a keyerror from this line:
> ` self.zone_var = str(result['data'][0]['rzone'])`
> More specifically, `rzone` is not in the data object for me. Any ideas on what the issue might be?
> 
> Edit: for anyone who sees this down the line, the issue arises when you use the api_login function, and use old or incorrect access tokens (or some combination of this). I fixed it by manually setting the access token properties (as shown in the login workaround page) as well as fixing the value of the access token I was using.

add print(str(result)) to your code before your trying to read the result data, so it dumps whats in result.

99% of the time I encounter errors with missing data objects, its almost always because of unsuccesful logins. You probably failed verification too many times, and got locked out.
