### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by archae0pteryx** [tedchou12/webull#180]
Still looking? Are you open to suggestions / refactors?

**Comment by tedchou12** [comment]
@archae0pteryx 
Yeah, if you want, feel free to contribute to the codes here! Webull does update a lot and things are breaking more than I can handle lately.

Feel free to fork and do pull requests.

Thanks

**Comment by archae0pteryx** [comment]
@tedchou12 is there a particular reason for ignoring your `.gitignore`? and not saving a lock file?

**Comment by tedchou12** [comment]
Thank you for the help.
actually, I think gitignore is added to the file by accident, I think it can be removed.

What lock file do you mean?

**Comment by archae0pteryx** [comment]
Well, the .gitignore file is important to leave tracked in git as it will properly exclude files that shouldn't be tracked. The lock file (which shouldn't be excluded) makes sure that all the dependencies stay the same across development envs - if your env is using package 2.x.x than I should have that same version as well. This file is added automatically when using virtual envs (generally) it can be generated using pip as well (i think, python isn't my most proficient language) I also noticed that the requirements file is missing dependencies that you should be sure to freeze into the file so everyone gets all required packages when they install.

**Comment by hfacey** [comment]
you typically don't need a  lock file here as the requirements file specifies a version

**Comment by zenhorace** [comment]
contributions always welcomed 🙂. Feel free to send PRs. There are a few of us that can review
