### ISSUE TITLE
Using Refresh Token resulting in 500 Response

### ISSUE THREAD

**Issue by PageMastr** [tedchou12/webull#184]
Im trying to login using my refresh token grabbed from chrome and the example from the wiki, but insteading of returning my account info im getting a code 500, am i doing something wrong here?
my code:

        wb = webull()
        fh = open("webull_credentials.json", "r")
        credential_data = json.load(fh)
        fh.close()
        print('refresh token: ' + credential_data['refreshToken'])
        print('access token: ' + credential_data['accessToken'])
        print('expire time of token: ' + credential_data['tokenExpireTime'])
        print('uuid: ' + credential_data['uuid'])
        wb._refresh_token = credential_data['refreshToken']
        wb._access_token = credential_data['accessToken']
        wb._token_expire = credential_data['tokenExpireTime']
        wb._uuid = credential_data['uuid']
        
        n_data = wb.refresh_login()
        print(n_data)
        credential_data['refreshToken'] = n_data['refreshToken']
        credential_data['accessToken'] = n_data['accessToken']
        credential_data['tokenExpireTime'] = n_data['tokenExpireTime']

        file = open('webull_credentials.json', 'w')
        json.dump(credential_data, file)
        file.close()
        wb.get_account_id()
        wb.get_trade_token('123456')
        print(str(wb.get_account()))

And here is the result i am getting:
![af2f2f2f](https://user-images.githubusercontent.com/9737536/108769619-db153180-751e-11eb-9c41-ca21cd0765fa.png)

**Comment by shailesh9r** [comment]
check issue#178...is this account opened recently? then try following version

def account(self, account_id):
return f'{self.base_trade_url}/v3/home/{account_id}'

good luck!

**Comment by PageMastr** [comment]
> check issue#178...is this account opened recently? then try following version
> 
> def account(self, account_id):
> return f'{self.base_trade_url}/v3/home/{account_id}'
> 
> good luck!

Can Confirm this did work.

**Comment by tedchou12** [comment]
Looks like is working for my account. I am not sure if it does fix for newer accounts.
