### ISSUE TITLE
Getting Chart Data for Options?

### ISSUE THREAD

**Issue by rhowardstone** [tedchou12/webull#189]
This library is fantastic! It would be very nice to be able to get past pricing data for options, like the get_bars() method does for stocks. When I try to use the _option's_ tickerId/symbol, as the tId/stock parameter in the get_bars function, I'm given an error. Is this possible to do?

**Comment by hfacey** [comment]
options historical data is not freely available like stock data is (for example, getting a year of options data on just SPY would cost ~$100) and webull doesn't provide historical options data

**Comment by rhowardstone** [comment]
It's certainly hard to find, yes! However, when I go to the Webull app on my phone, I'm able to see chart data for options after clicking on them. The data goes back months in some cases, probably back to when they were issued. I was just wondering if there was a way to download this data using this library, or how hard it would be to alter to do so? My account is subscribed to the OPRA data feed, perhaps that is why I can view it on my phone?

**Comment by hfacey** [comment]
can you screenshot an example of data going back months? I'm also subscribed to OPRA real-time feed and I've never seen historical options data. if they do provide it, we can get it 👍🏽

**Comment by rhowardstone** [comment]
Here you go. Thanks! 
![Screenshot_20210225-145210](https://user-images.githubusercontent.com/19674552/109209147-317dac80-7779-11eb-81fc-db43c68de75f.png)

**Comment by hfacey** [comment]
omg. I just found that screen in the app. didn't even know it was there. Will look if I can access it on the web. If I can, can probably have a way to access it via this api by end of weekend. if not, will be a bit harder to add, but still doable. Thanks for showing this!

**Comment by rhowardstone** [comment]
No problem, thank you so much!

**Comment by boonyeow** [comment]
Nice find! 

I explored on their desktop application and found that you can access its option data through this endpoint:
`https://quotes-gw.webullfintech.com/api/quote/option/chart/query?count={count}&derivativeId={derivativeId}&type={interval}`

I've added the endpoint and created a new function to retrieve charting data in my pull request (#191)

**Comment by rhowardstone** [comment]
You are absolutely fantastic!!! Thank you so much!

**Comment by hfacey** [comment]
Thanks for coding this up! I found the APIs on the desktop client last night as well lol. I've added a couple of comments to the PR
