### ISSUE TITLE
Wrong modify order endpoint

### ISSUE THREAD

**Issue by xuxinx** [tedchou12/webull#197]
https://github.com/tedchou12/webull/blob/0973babc43e64d44a667a3c2fd23540106425e48/webull/endpoints.py#L155-L156

{self.base_trade_url}/trade/order/xxx
=>
https://tradeapi.webullbroker.com/api/trade/trade/order/xxx  
duplicate `/trade` path  

@tedchou12 I guess it should be `base_ustrade_url` here ?

**Comment by tedchou12** [comment]
Thanks!

I was investigating this endpoint last weekend. But is a bit complicated because you need to submit the order_id, so I wasn't successful.

At the moment, I recommend to cancel the order and place the order again to be more confident.

Anyways, let me take some time to look into this.
