### ISSUE TITLE
where did you find the account id

### ISSUE THREAD

**Issue by duanlian0903** [tedchou12/webull#2]
When I try to get the account details by response = requests.get('https://tradeapi.webulltrade.com/api/trade/v2/home/10129689', headers=headers), I get the message that "This account does not belong to this user". How can you find the id 10129689 in your account?

**Comment by tedchou12** [comment]
@duanlian0903 
Thank you! Indeed. Sorry, I only tested my account, I nearly thought is an api version.
I have added the 
`webull.get_account_id()` function.
The readme has also been updated, please have a try and let me know.
Ted

**Comment by duanlian0903** [comment]
It is working now. Thank you very much!

**Comment by hz2018tv** [comment]
what is the password in get_trade_token()? In the readme, it says
webull.login('test@test.com', 'pa$$w0rd')
webull.get_trade_token('123456')
the username has 4 letters, password has 8 letters, get_trade_token has 6 letters....
