### ISSUE TITLE
Workaround for login issue

### ISSUE THREAD

**Issue by Shomari** [tedchou12/webull#207]
I did the work around for login everything seemed to work however I still couldn't place an order.  Played around some with suggestions based on past issues and eventually tried to check my account  info with wb.get_account(), only to get a weird json error.  eventually tried wb.get_account_id() which did return my account id.  I was then able to successfully call wb.get_account() and then I as able to successfully play my order with wb.place_order().

Mostly posting this as info for you all.  It appears work around method isn't getting the needed account id (or I could of just been doing something horribly wrong)

Also, second note:  In the documentation on the home page for place_order, it has the quantity param listed as qty, when looking at the code it should be quant.  :)

**Comment by tedchou12** [comment]
@Shomari 
Sorry, you are correct, the workaround wiki missed this:
`wb.get_account_id()`

Thanks for the advice, I added it to the wiki page!
