### ISSUE TITLE
Workaround Not Working

### ISSUE THREAD

**Issue by cchuster** [tedchou12/webull#208]
Hello! I am trying to use the workaround method for login. I open an incognito tab in Chrome, sign in to my Webull, Inspect, and go to Network. The issue is there is no "account" on the side bar so I can not access the necessary info. Thanks!

**Comment by manojjenago** [comment]
> Hello! I am trying to use the workaround method for login. I open an incognito tab in Chrome, sign in to my Webull, Inspect, and go to Network. The issue is there is no "account" on the side bar so I can not access the necessary info. Thanks!

Hi, I think I had that issue as well. After doing some research , I see that once you are in Network tab, log out and re-log in. Then I think it grabs the account in the network tab. Not sure why ... Hope this might help you..
Thanks ,
manoj

**Comment by cchuster** [comment]
Hi! It now shows up but does not show me the correct information. When I go to response it just shows me HTML instead of proper json format. Thanks!

**Comment by manojjenago** [comment]
Are you loggin  to the Trade tab again , as that one will give you the JSON details.

**Comment by cchuster** [comment]
When I go into the trade tab "account" does not appear at all even after logging out and back in.

**Comment by cchuster** [comment]
I was able to get it to work. Now I am facing an issue where when I run the script again, it gives me this error: 

credential_data['refreshToken'] = n_data['refreshToken']
KeyError: 'refreshToken'

**Comment by manojjenago** [comment]
> I was able to get it to work. Now I am facing an issue where when I run the script again, it gives me this error:
> 
> credential_data['refreshToken'] = n_data['refreshToken']
> KeyError: 'refreshToken'

That means your json file has not captured all the things that is required, I think if you will search for refreshToken , it wont be there in your JSON file . do once again log in and try to capture the account JSON that has all the values ..

**Comment by cchuster** [comment]
The refreshToken is in my JSON file.

**Comment by manojjenago** [comment]
Then it should not give that error , as I was getting that error as my file was not having refresh token, once I capture that my issue for refresh token is gone. ..

**Comment by nothingbutbacon** [comment]
Can you post your redacted json file?

**Comment by cchuster** [comment]
```
{
	"extInfo": {
		"userPwdFlag": "1"
	},
	"accessToken": "",
	"uuid": "",
	"refreshToken": "",
	"tokenExpireTime": "2021-03-21T02:48:24.040+0000",
	"firstTimeOfThird": false,
	"registerAddress": 6,
	"settings": {
		"id": 0,
		"userId": 0,
		"regionId": 6,
		"language": "en",
		"focusMarketId": "2,3,4,5,6,14",
		"theme": 2,
		"increDecreColor": 2,
		"fontSize": "M",
		"portfolioDisplayMode": 2,
		"portfolioNameNewline": 1,
		"portfolioHoldingsDisplay": 1,
		"portfolioIndexDisplay": 1,
		"portfolioBulletin": 1,
		"kdata": 1,
		"refreshFrequency": 1,
		"shock": 0,
		"tickerPriceRemind": 1,
		"orderDealRemind": 1,
		"hotNews": 1,
		"chartOption": 2,
		"operateTime": "1969-12-31T00:00:00.000+0000",
		"languageUpdateTime": "1970-01-01T00:00:00.000+0000",
		"createTime": "2021-01-10T23:32:12.000+0000",
		"updateTime": "2021-01-10T23:32:12.000+0000",
		"listStyle": 1
	}
}
```

**Comment by nothingbutbacon** [comment]
You clearly have the `refreshToken` in the file and should be able to read it without problems. The trouble is probably with `n_data = wb.refresh_login()`.  See if the refresh login is returning the correct data.
