### ISSUE TITLE
not Getting the Security Code 

### ISSUE THREAD

**Issue by manojjenago** [tedchou12/webull#209]
Hi,

I am not getting the security code in the Email , where as I am getting the MFA Code in the same email. 

`wb.get_security(webull_email)` #get your security question. 

Thanks,
Manoj

**Comment by tedchou12** [comment]
@manojjenago 
Hi there.

For the security, you don't get a code in the Email, you will get the question immediately in the response of the code. And you should use that response to answer the question.

https://github.com/tedchou12/webull/wiki/MFA-&-Security

**Comment by manojjenago** [comment]
> @manojjenago
> Hi there.
> 
> For the security, you don't get a code in the Email, you will get the question immediately in the response of the code. And you should use that response to answer the question.
> 
> https://github.com/tedchou12/webull/wiki/MFA-&-Security

Thanks for your guidance , sorry I was thinking that the same way the MFA is sent , the security question and id will be sent to the mail too. I got it you just have to capture the response and then use that for log in. Thanks again ..

Thanks,
Manoj
