### ISSUE TITLE
API for live data 

### ISSUE THREAD

**Issue by manojjenago** [tedchou12/webull#210]
Hi ,

Do we have any API to get live data other than live streaming. I am thinking I will store 1min data for more than 1 tickers at same time , in pandas dataframe or in SQL and calcualte the SMA , VWAP and other indicators and place orders based on some criteria.
Also I see some kind of delay data in my streaming compare to other brokers ... Is that I have to do some setting in webull??
Please guide..

Thanks,
Manoj

**Comment by tedchou12** [comment]
@manojjenago 
I don't recommend it.
https://github.com/tedchou12/webull/issues/202#issuecomment-795650152

If you are looking for data, you might as well buy it from data providers that already support API.
