### ISSUE TITLE
Premarket and aftermarket orders are failing

### ISSUE THREAD

**Issue by pushap2020** [tedchou12/webull#211]
Any orders place in the premarket or after hours are failing. Regular hours works fine.
I am using place_order function and the limit, GTC, extended hours=true are set so all the parameters are correct. WeBull receives the order and shows correct parameters in desktop app but it always fails.

**Comment by tedchou12** [comment]
@pushap2020 
I remember you can only order between 8am-4pm (even if extended hours are okay). What time are you trying to place the order?

**Comment by pushap2020** [comment]
> @pushap2020
> I remember you can only order between 8am-4pm (even if extended hours are okay). What time are you trying to place the order?

At 4:40am. I'll test to see if it works after 8am. Thanks.
