### ISSUE TITLE
Issue with Paper fucntions

### ISSUE THREAD

**Issue by MHassanNajafi** [tedchou12/webull#212]
I used paper trading a few months ago but I'm not able to use it now for an unknown reason. I receive the following error message when sending wb.get_account or wb.place_order commands.

{'msg': 'account(4295355) not in paper(1)', 'traceId': 'd0ea6750899e4826b25c974377e6a188', 'code': '400', 'success': False}

Any idea where the problem might be? Anyone faced the same issue?

**Comment by tedchou12** [comment]
Sorry, I didn't see the issue earlier.

Are you able to login correctly?

does `print(wb.get_account())` or `print(wb.get_account_id())` give you anything?

**Comment by MHassanNajafi** [comment]
This is what I get with these commands:

print(wb.get_account_id())
   output: 4295355

print(wb.get_account())
   output: {'msg': 'account(4295355) not in paper(1)', 'traceId': 'e04308e93b214a378626a484f298d05c', 'code': '400', 'success': False}

So, I believe I'm logged in, but cannot get my paper account information. I have no issue with printing my live account information. But cannot print account information or submit orders with the paper account.

**Comment by tedchou12** [comment]
> So, I believe I'm logged in, but cannot get my paper account information. I have no issue with printing my live account information. But cannot print account information or submit orders with the paper account.

You are planning to trade with Paper or Live account?

> output: {'msg': 'account(4295355) not in paper(1)', 'traceId': 'e04308e93b214a378626a484f298d05c', 'code': '400', 'success': False}

Doesn't look right to me. Probably login failed.

**Comment by MHassanNajafi** [comment]
I want to do both Paper and Live trading, each in a different script. I have no problem with Live trading and it's working fine. But when I want to use my Paper account I face this issue. 

I'm using the following for my live account:
      from webull import webull
      wb = webull()
and using the following for my paper account:
      from webull import paper_webull
      wb = paper_webull()

Then I use the following to login which totally works for my live trading.
ACCESS_TOKEN=XXXXX
REFRESH_TOKEN=XXXXXX
TOKEN_EXPIRE=XXXXXX
UUID=XXXXXX
wb.api_login(access_token=ACCESS_TOKEN, refresh_token=REFRESH_TOKEN,token_expire=TOKEN_EXPIRE, uuid=UUID)

The account number is being printed with print(wb.get_account_id()) in the paper account. This means I have logged in successfully. Right? Am I doing something wrong or there is a problem with the API?

**Comment by MHassanNajafi** [comment]
@tedchou12 
Yes, I'm using the same credentials to login to paper. I even tried using a new set of credentials but still no success. Live account works fine but the paper does not.

**Comment by tedchou12** [comment]
@MHassanNajafi 
I cannot know what is wrong from the code you've given.
If you are keen to debug, add me on skype. The email is written in here:
https://github.com/tedchou12/webull/blob/master/setup.py

**Comment by thesupershan** [comment]
If using the workaround code be sure to replace the WB object with a webull_paper object
