### ISSUE TITLE
Screen Runner doesn't seem to work for me

### ISSUE THREAD

**Issue by yingdi1** [tedchou12/webull#215]
```
wb.run_screener( price_lte=.10, price_gte=5, pct_chg_lte=.035, pct_chg_gte=51)
```
Why does it scan for `price less than or equal to 0.1` and at the same time it is `greater or equal to 5`? There shouldn **NOT** be such stock.

But the result return a list of such stock.

I also check the code, it will only take price_lte only if it has price_gte. It is confusing to me.

**Comment by hfacey** [comment]
think of it as a filter. it excludes prices less than 0.1 and greater than 5

**Comment by hfacey** [comment]
you're right. it is silly. should be a simple enough bug fix but anyone using it with the current functionality would have their code broken if we change the behavior. For now you can consider price gte and lte as exclusionary filters. So it will exclude prices less than 0.1 and greater than 5
