### ISSUE TITLE
get_bars on hour range

### ISSUE THREAD

**Issue by thesupershan** [tedchou12/webull#217]
I’m able to get_bars on all the minute ranges, and day range, but the hour ranges don’t seem to work. Attempted with TSLA requesting 10 counts but only 1 was returned and it had a strange time stamp.

Results for query of '1h':
```
bars: 
                            open   high     low  close      volume  vwap
timestamp                                                               
2021-04-26 00:00:00-04:00  741.0  749.3  732.61  738.2  31038502.0   0.0
```

**Comment by boonyeow** [comment]
Looks like they changed the parameter name for hourly range. Try using [m60, m120, m180](https://quoteapi.webullbroker.com/api/quote/tickerChartDatas/v5/913255598?type=m60&count=5&extendTrading=1) instead of h1, h2, h4.
