### ISSUE TITLE
Login/Refresh token issue

### ISSUE THREAD

**Issue by riteshkohad** [tedchou12/webull#229]
After following the MFA, Security Questions, Login goes successful but the return value (a Json data) of the login is different than the "Refresh Token" we used to get it earlier. 

I believe they have changed the login and refresh login process. I can't seem to find the "original" login token (which used to have a login and refresh token) anymore. In fact, my Saturday's login token is no more valid. "refresh_login" method is throwing an error. 

The new return value from Login():
{
   "extInfo":{
      "desensitizedPhone":"+1-123****123",
      "phone":"+1-11234566123",
      "accountType":"1",
      "desensitizedEmail":"abc****@emailprovider.com",
      "equipmentCheck":"send",
      "email":"emailaddress@emailprovider.com",
      "account":"+1-1234566123"
   },
   "firstTimeOfThird":false
}

**Comment by Hamze24w** [comment]
I had a similliar issue, I deleted all did.bin files and used security question and mfa to login (with IDLE) then it worked.

**Comment by riteshkohad** [comment]
> I had a similliar issue, I deleted all did.bin files and used security question and mfa to login (with IDLE) then it worked.

Interesting!! I will try and get back. thank you!!

**Comment by riteshkohad** [comment]
Just realize that while I was using MFA security, I forgot to pass MFA code to the "login()". once I delete the did.bin (as suggested by @Hamze24w ) I started receiving token and refresh token. 

I am closing this issue.
