### ISSUE TITLE
unexpected keyword argument in PAPER account 

### ISSUE THREAD

**Issue by riteshkohad** [tedchou12/webull#233]
If I try to pass any of these values [outsideRegularTradingHour, stpPrice, trial_value, trial_type] for "place_order()" method, in "PAPER" account it throws following error:

TypeError: place_order() got an unexpected keyword argument 'stpPrice'

Note: keyword argument will be substituted by the first argument I pass out of the above mentioned

**Comment by tedchou12** [comment]
@riteshkohad 
paper account doesn't support stop price:
https://github.com/tedchou12/webull/blob/71914c82161bd5a60064f1c3b465e5fe443eea19/webull/webull.py#L1221
