### ISSUE TITLE
get_bars() - 800 limit?

### ISSUE THREAD

**Issue by bpkum** [tedchou12/webull#234]
Hi,

I have been using the get_bars function and I am trying to get candlestick data on 1 min timeframe for SPY ticker... I wanted to get the last 1500 candlesticks, but looks like the get_bars has a limit of 800 candles? Just wanted to confirm before I complicate my code...

**Comment by hfacey** [comment]
correct - there's an 800 limit per request

**Comment by bpkum** [comment]
Ah got it... thnaks!

**Comment by LukeWang01** [comment]
Update:

I just test today, and list the max count bars for each interval:

max_count:
m1:     1200
m5:     1200
m15:    1200
m30:    1049

d1:     1200

Also, h1, h2, h4 intervals are not working for me.

BTW, if any call just gets one-row data, please call the API a few seconds later.
