### ISSUE TITLE
Order submission error on live account

### ISSUE THREAD

**Issue by MHassanNajafi** [tedchou12/webull#240]
Hi,

My account shows a strange error today when I'm trying to submit a limit sell order for a 'MU' stock:
{'success': False, 'code': 'trade.webull.UNFILLED_SELL_ORDER_IN_MARGIN_ACCOUNT', 'msg': 'This order would result in a short sell due to an existing open sell order. However, this stock is currently not supported for short selling.', 'data'

I had no problem with submitting sell orders last week but today it gives me this strange error.
Does anyone face the same issue?

Thanks.

**Comment by hfacey** [comment]
just read the error. it sounds like u already had a sell order in progress and you tried to do another but the stock isn't currently shortable
