### ISSUE TITLE
Option Order doesnot work.

### ISSUE THREAD

**Issue by shamssheikh** [tedchou12/webull#25]
Option Order doesn't work. I am able to find it and added below code to my local copy. Still need formatting.

**_I just changed for first one, lmtPrice is string, at least that how portal works._**
        if orderType == 'LMT' and lmtPrice:
            data['lmtPrice'] = lmtPrice    **_#removed float_**
        if orderType == 'STP' and stpPrice:
            data['auxPrice'] = float(stpPrice)
        if orderType == 'STP LMT' and lmtPrice and stpPrice:
            data['lmtPrice'] = float(lmtPrice)
            data['auxPrice'] = float(stpPrice)

**_Made few changes...._**
        response = requests.post(self.urls.place_option_orders(self.account_id), json=data, headers=headers)
        data1 = json.loads(response.content) _**# reading response in json; This is to capture order message 8:00 AM to 4:00PM.**_
        if response.status_code != 200 or not data1["forward"]: **_# added a check to see if its success; you will see status code 200 but there will no order placed after 4:00 PM so we need to capture that._**
            raise Exception('place_option_order failed', response.status_code, response.reason,
                            data1["checkResultList"][0]["msg"]) **_#Added message here_**
        response = requests.post(self.urls.place_option_orders1(self.account_id), json=data, headers=headers) **_# this is the actual trade url; just placed URL under endpoints.py_**
        return True

endpoint.py

    def place_option_orders(self, account_id):
        return f'{self.base_trade_url}/v2/option/checkOrder/{account_id}'
# Added below code
    def place_option_orders1(self, account_id):
        return f'{self.base_trade_url}/v2/option/placeOrder/{account_id}'

**Comment by alexonab** [comment]
The option order code works as expected here.  It could be you are passing a limit price with more than two decimal places.   If you don't provide the error you encounter then no one can confirm your issue.

**Comment by shamssheikh** [comment]
I will execute this tomorrow during market hour tomorrow but when i ran now, i started getting error500(500 Internal Server Error).
Please find the results.

![Screenshot_16](https://user-images.githubusercontent.com/14261211/77029237-5c039a80-6958-11ea-9c2d-361c6ff0cf05.png)

below results from my modified code:- my code has both checkOrder and place order. I am executing check order first to see if any errors or exceptions and then based on the result I am calling Place order with same json data.

![Screenshot_17](https://user-images.githubusercontent.com/14261211/77029249-632aa880-6958-11ea-8ec0-9e9d5e983bc2.png)

I will review limit price with string and float during market hours tomorrow and let you know the outcome.

**Comment by b0b5h4rp13** [comment]
I just want to jump on on the return true thing, it not helpful if your writing a trading bit, because you need the order id returned, in order to check on it.  Best to return the json response and check it in your code for success or failure

**Comment by shamssheikh** [comment]
Yes, i agree. and I confirm that your code works during market hours.
