### ISSUE TITLE
Workaround Showing HTML instead of JSON

### ISSUE THREAD

**Issue by cchuster** [tedchou12/webull#251]
Once I go into my Network tab in a private tab and press "account", the resulting preview is of HTML and not JSON. Thanks!

**Comment by tedchou12** [comment]
@cchuster 
Sorry for the delayed reply.

You will need to search for the correct endpoints, Webull should **usually** reutrn you with the JSON for updating information, but HTML is returned for some endtpoints (especially at the beginning of the page load) to render the UI.

**_I believe you need to look for the correct one._**
