### ISSUE TITLE
[Question] Crypto orders / Streaming API

### ISSUE THREAD

**Issue by meltdown03** [tedchou12/webull#252]
Does the `on_order_message` for the `StreamConn` provide real-time order info? Like if I send an order, will the streamer show the details as soon as I send it, or only after it fills, or not at all (Not sure if that's its purpose)?  Also, do crypto orders show up with with the streamer running? I tried but got nothing when I had `conn.run_blocking_loop()` running.

**Comment by meltdown03** [comment]
Ok thank you. I was looking for my specific orders and fills, but in real-time so I can process them with another library.

**Comment by meltdown03** [comment]
Are you sure on_order_message isn't what I am looking for?
https://github.com/tedchou12/webull/blob/e63c267803b07d2b118dd7cc25b2ae4631833e7c/webull/streamconn.py#L64-L65
shows that the information recieved has the orderId, orderStatus and filled quantity etc.
I still don't get any of this when I set the `debug_flg=True` and/or use a `order_func` that prints the info

**Comment by tedchou12** [comment]
`on_order_message`
Sorry, you are right. If it returns orderID and the order details, it might be what you are looking for.

Go ahead and try it!

(sorry, I didn't add the streamconn module and I only checked it for 1-2 times, I am not very familiar with this part of the code.)

**Comment by meltdown03** [comment]
> `on_order_message`
> Sorry, you are right. If it returns orderID and the order details, it might be what you are looking for.
> 
> Go ahead and try it!
> 
> (sorry, I didn't add the streamconn module and I only checked it for 1-2 times, I am not very familiar with this part of the code.)

Yeah, It doesn't work. I tried watching the websockets data on the Webull webapp (using Chrome developer tools) and nothing is received there either when an order is placed. It may be because the market is closed though. The streaming MQTT endpoints I see in the chrome developer tools are `wspush.webullfintech.com/mqtt` and `platpush.webullfintech.com/mqtt` also. The StreamConn is set to use `*.webullbroker.com`, changing them didn't help, must just be an alternative.

**Comment by meltdown03** [comment]
I found out that is working only when I use my live (Real money) account. I get the fills and cancelled orders on stocks and crypto. Even if I use the paper_webull class, the streamer shows activity from the live account only.
