### ISSUE TITLE
`get_option_quote` stops working 

### ISSUE THREAD

**Issue by kaizeng** [tedchou12/webull#253]
`get_option_quote` stops working. It looks that webull changed its API (single option quote disappears from web GUI either). If other people can confirm they are having the same issue, I am thinking of adding a fix by calling the batch query API. Thanks!

**Comment by hfacey** [comment]
hmm... worked for me up to a few hours ago...
make sure you're not trying to get options that expired today - they disappear after midnight EST.

**Comment by kaizeng** [comment]
thanks for checking. let me give it another try and see if it works for me. If it is working, I am going to close the issue.

**Comment by kaizeng** [comment]
it's a WeBull issue where it only happens to one ticker `VXX`. The issue is resolved by the WeBull
