### ISSUE TITLE
Option Info

### ISSUE THREAD

**Issue by alvarozamora** [tedchou12/webull#257]
Hi, sorry if this is not the correct place for it, but how can I get the information about the exact option position (e.g. strike, expiration). Currently, I only see this:

```
 'position': '-1',
 'assetType': 'OPTION',
 'cost': '-155.00',
 'costPrice': '1.550',
 'currency': 'USD',
 'lastPrice': '1.575',
 'marketValue': '-157.50',
 ```
 
 which doesn't tell me what the strike is or when it expires (or whether it's a put or call).

**Comment by tedchou12** [comment]
@alvarozamora 
First use get_options() to get the option chain, then using the option chain's optionid to place the order with  place_order_option().

I believe this should help you, https://www.youtube.com/watch?v=3w3ZNQniSbU&t=846s

**Comment by shalli2** [comment]
> Hi, sorry if this is not the correct place for it, but how can I get the information about the exact option position (e.g. strike, expiration). Currently, I only see this:
> 
> ```
>  'position': '-1',
>  'assetType': 'OPTION',
>  'cost': '-155.00',
>  'costPrice': '1.550',
>  'currency': 'USD',
>  'lastPrice': '1.575',
>  'marketValue': '-157.50',
> ```
> 
> which doesn't tell me what the strike is or when it expires (or whether it's a put or call).

Were you able to get this working?

**Comment by mrazum** [comment]
shalli2, try this:
   response = requests.get('https://tradeapi.webullbroker.com/api/trade/v4/home/' + self.account_id , headers=headers)
   result = response.json()
   print result['positions2']
