### ISSUE TITLE
Can't refresh tokens

### ISSUE THREAD

**Issue by Alanavai** [tedchou12/webull#260]
My access and refresh tokens finally ran out and I tried to repeat the steps to refresh them.
Every time I run this code, I get an error. What could be the issue?

Code:
![Webull_API_Login](https://user-images.githubusercontent.com/49327726/130146673-e3379fc4-d67f-4f17-b802-fcb04e64f36e.png)

Output:
![Webull_API_Output](https://user-images.githubusercontent.com/49327726/130146691-f78ceca3-2ed1-45a2-b2cb-623da1ca199c.png)

**Comment by tedchou12** [comment]
try this one:
https://github.com/tedchou12/webull/wiki/Workaround-for-Login

**Comment by Alanavai** [comment]
@tedchou12 Hi Ted, I see the instructions on your link but what page do we have to access to see "account" under the Network tab to see the tokens. I don't see any such name when I go to app.webull.com/watch.

**Comment by tedchou12** [comment]
@Alanavai 
You would need to logout **then** login again, to find the account in the network tab.
Try using ctrl + f for search, it might be a lot easier to find.

**Comment by Alanavai** [comment]
@tedchou12 That worked, thanks!
