### ISSUE TITLE
DT/ON Leverage

### ISSUE THREAD

**Issue by r1997mysm** [tedchou12/webull#263]
Hi.. Is there a way to programmatically find out if the stock is marginable or leveraged at 4x, 2x, 1x, 0.333x, etc for Long/Short, Day trade/Overnight? I want to research the impact of leverage on price fluctuations for a university project.

**Comment by zenhorace** [comment]
For some of those questions, the answer is "yes". Sorry, about the late reply. If it's still relevant for your project, reply here and I can spend a few minutes helping you look through the API for the info you'd like. If not, I'll close this in a week or so.
