### ISSUE TITLE
Webull API Stopped Working

### ISSUE THREAD

**Issue by ajeetsingh78** [tedchou12/webull#266]
Hi All,

Webull API was working earlier but stopped working on 09/05/21, I was using the wf = wb.get_news(stock, Id=0, items=10) for getting the news but its not working now. Any idea or solution would be helpful on it

**Comment by mnvarfol** [comment]
+1

**Comment by joshehren** [comment]
Does this issue relate to the endpoints not working?  I'm not able to see/visit most of the urls provided in the endpoints.py file:

        self.base_info_url = 'https://infoapi.webull.com/api'
        self.base_options_url = 'https://quoteapi.webullbroker.com/api'
        self.base_options_gw_url = 'https://quotes-gw.webullbroker.com/api'
        self.base_paper_url = 'https://act.webullbroker.com/webull-paper-center/api'
        self.base_quote_url = 'https://quoteapi.webullbroker.com/api'
        self.base_securities_url = 'https://securitiesapi.webullbroker.com/api'
        self.base_trade_url = 'https://tradeapi.webullbroker.com/api/trade'
        self.base_user_url = 'https://userapi.webull.com/api'
        self.base_userbroker_url = 'https://userapi.webullbroker.com/api'
        self.base_ustrade_url = 'https://ustrade.webullfinance.com/api'
        self.base_paperfintech_url = 'https://act.webullfintech.com/webull-paper-center/api'
        self.base_fintech_gw_url = 'https://quotes-gw.webullfintech.com/api'
        self.base_userfintech_url = 'https://userapi.webullfintech.com/api'
        self.base_new_trade_url = 'https://trade.webullfintech.com/api'

**Comment by ajeetsingh78** [comment]
Thanks @joshehren 

Yes , It seems above URLs are not working.

I am using below code, Not sure if any solution until URLs start working

from webull import webull

wb = webull()

wf = wb.get_news(stock, Id=0, items=10)

print("Stock-->",wf)

Response:
Stock--> []
Stock--> Empty DataFrame

**Comment by ajeetsingh78** [comment]
I am able to fetch the new after News Fix #268, Closing the issue.
