### ISSUE TITLE
Webull Comments

### ISSUE THREAD

**Issue by omarc1492** [tedchou12/webull#269]
I have been unable to figure out the requests to Webull “Comments” using Wireshark. Does there exist an API to post comments?

**Comment by zenhorace** [comment]
yeah - seems the community/comments section isn't in the web interface and I deleted the desktop app and wireshark so I can't inspect. Maybe someone else will. but what's the use case? why would you want to programmatically post comments, except to spam the community?

**Comment by omarc1492** [comment]
I wanted to be able to post a comment on a scheduled basis, instead of doing it manually.

There's certain cryptos on Webull that are not available to buy on Webull and half the comments posted are from people trying to figure out how to buy it. 

My post/comment would contain information on exchanges available to buy from.

> yeah - seems the community/comments section isn't in the web interface and I deleted the desktop app and wireshark so I can't inspect. Maybe someone else will. but what's the use case? why would you want to programmatically post comments, except to spam the community?

**Comment by zenhorace** [comment]
I don't know for sure but I suspect it may be against community guidelines to promote other exchanges on their platform. Also, if you automatically reply to posts complaining about not being able to buy some cryptocurrency, promoting another platform, that will quickly get flagged as spam.

I'm not trying to be be annoying, but it's the responsibility of everyone using this library and ones like it to make sure they do it in a way that won't annoy webull into blocking these unofficial API libraries (like robinhood started doing)

**Comment by omarc1492** [comment]
> I don't know for sure but I suspect it may be against community guidelines to promote other exchanges on their platform. Also, if you automatically reply to posts complaining about not being able to buy some cryptocurrency, promoting another platform, that will quickly get flagged as spam.
> 
> 
> 
> I'm not trying to be be annoying, but it's the responsibility of everyone using this library and ones like it to make sure they do it in a way that won't annoy webull into blocking these unofficial API libraries (like robinhood started doing)

That's a good point, my intention is just to post a message, I have no desire to reply to specific messages.

I could try setting up a MITM attack on my smartphone... Wireshark and Webull desktop app led me nowhere. I might be able to see more by unencrypting SSL traffic.

**Comment by zenhorace** [comment]
Closing as it's out of the scope for the goals of this library. If you do find a way to do this, feel free share with us 🙂
