### ISSUE TITLE
get_account() issue when using a paper trading account

### ISSUE THREAD

**Issue by 39xdgy** [tedchou12/webull#270]
{'timestamp': '2021-09-28T00:19:13.186+0000', 'status': 404, 'error': 'Not Found', 'message': 'No message available', 'path': '/webull-paper-center/api/paper/1/acc/'}

I am getting this error when I try to get account information for my paper account. It worked for the first time.After I switch it to my actually account and then switch it back to paper account, it is not working. I was trying to search though the issue and someone solve the issue by [resetting the paper trading account] #232 , which I can not do for now. Any help would be great. Thank you so much!

**Comment by alexonab** [comment]
Be sure you have installed the latest via git.  Pypi is not always up-to-date.

```
pip install -U git+https://github.com/tedchou12/webull.git
```

**Comment by 39xdgy** [comment]
I updated with the commend above and it did not change anything. Also for more information if that helps, the get_detail for the paper account would work but not for the get_account still.

**Comment by alexonab** [comment]
To reset via a browser, click on Paper Trading, click on the Paper Account tab on the top right, then look for the reset link in the Paper Account Details widget.

**Comment by 39xdgy** [comment]
I am testing on my program by using the Paper Trading account, So in general I do not want to reset my paper trading account. If there is no other way around, I would love to know at least why it is doing this. Thank you so much.

**Comment by zenhorace** [comment]
do you remember when (the dates) you switched from paper to the real account and when you switched back?

**Comment by tedchou12** [comment]
Ah, you need to run the get_account_id() before get_account().
