### ISSUE TITLE
wb.place_order_otoco needs additional error check.... for PAPER_TRADE account.

### ISSUE THREAD

**Issue by tlh45342** [tedchou12/webull#275]
FROM (or about 523) if I print "result1" I get

{'msg': 'Inner server error', 'traceId': '7d3e987458fc4fbda6aadb481050ee15', 'code': 'trade.secAcct.mismatch.with.user', 'data': {}, 'success': False}

This is from my call as follows

Traceback (most recent call last):
  File "/opt/tradinghook/test2.py", line 14, in <module>
    a = wb.place_order_otoco(stock='AAPL', price=90.0, quant=2, limit_profit_price=100.0, stop_loss_price=80.0)
  File "/usr/local/lib/python3.9/dist-packages/webull/webull.py", line 523, in place_order_otoco
    if result1['forward'] :

result1 did not come back with key "forward" which I guess was expected.

Crap.. I see the light now.  I am betting I did this on the webull_papertrade account... and I am betting webull won't let you do a OTOCO on the paper trade account.

I would call this low hanging fruit ... but just so you know dumb people like me might try a stunt like this.

**Comment by tedchou12** [comment]
> Crap.. I see the light now. I am betting I did this on the webull_papertrade account... and I am betting webull won't let you do a OTOCO on the paper trade account.

Yes. Webull doesn't let you do otoco and limit with paper trade I believe.
