### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by Zihanouk** [tedchou12/webull#28]
i am very new to this im not sure how to install and get it running

**Comment by b0b5h4rp13** [comment]
Have you used python before?  if not time to learn how to code in it first; otherwise use the big green down button and download a zip file, extract it to a directory and start coding your trading script

**Comment by Zihanouk** [comment]
I have used python before, I used to use the alpaca API (a brokerage with an API built-in).  but I have no idea how to set one up downloaded from GitHub.

**Comment by Zihanouk** [comment]
I'm not sure what directory to extract too and get it up and running.

**Comment by gamesover** [comment]
Please refer to the below strucuture. You may download and extract the project to your targeted folder as `webull`
```
.
|
+-- webull
|         |
|         +-- webull.py
|         +-- streamconn.py
|         +-- endpoints.py
|         +-- ...    
+-- my-trading-file.py
```
In `my-trading-file.py` under the root of project folder, you can write something like https://github.com/tedchou12/webull/wiki/For-Developers-Contributors
```python
from webull.webull import webull
from webull.streamconn import StreamConn
from pytz import timezone

webull = webull()
webull.login('ted_chou@example.com', 'pa$$w0rd')
webull.get_trade_token('000000')

nyc = timezone('America/New_York')
def on_price_message(topic, data):
    print (data)
    print(f"Ticker: {topic['tickerId']}, Price: {data['deal']['price']}, Volume: {data['deal']['volume']}", end='', sep='')
    if 'tradeTime' in data:
        print(', tradeTime: ', data['tradeTime'])
    else:
        tradetime = data['deal']['tradeTime']
        current_dt = datetime.today().astimezone(nyc)
        ts = current_dt.replace(hour=int(tradetime[:2]), minute=int(tradetime[3:5]), second=0, microsecond=0)
        print(', tradeTime: ', ts)

def on_order_message(topic, data):
    print(data)
```

Ideally, the project shall be packed as a pip lib

**Comment by Calrider** [comment]
@Zihanouk webull is now available on PyPI. You can install with below:

`pip install webull`
