### ISSUE TITLE
trade_token expired

### ISSUE THREAD

**Issue by hz2018tv** [tedchou12/webull#29]
hi, got trade_token expired sometimes. Is there a way to refresh it gracefully? I assume we can call get_trade_token(password) periodically.

**Comment by tedchou12** [comment]
Hi there!
Indeed, seems like the trade_token expires after a few hours.
I believe that the expire time should be the same as what you expect in the App.

I imagine that it might be difficult to refresh it through any other ways than to submit the PIN again, but I will keep an eye on it.

**Comment by alexonab** [comment]
I have been using the below to refresh the login.  I call it before any operation that requires a trade token.  It adds an extra request but it has resolved my issues with the token expiring.

```
def refresh_login():
    if webull.refresh_login():
        return True
    else:
        return webull.login(Settings.webull_user, Settings.webull_password)
```

**Comment by qwertzguy** [comment]
Seems like it also requires refreshing the trade token, so I do this before every trade:
```
def refresh_login():
  webull.refresh_login()
  webull.get_trade_token('123456')
```

I guess it expires after a certain time, but it also expires immediately if from a web browser you enter the code for any actions that needs it, like making a trade or accessing the account documents.
