### ISSUE TITLE
place_order_otoco() result1['forward'] key error after JSON call

### ISSUE THREAD

**Issue by matthyatt15** [tedchou12/webull#298]
Hi all,

When I try to call place_order_otoco(), I get an error saying "result1['forward'] keyerror 'forward'" (error 500 too). I tried changing the function arguments but those requests failed. My thought is that the endpoint has been changed; has anyone else experienced this error?

https://github.com/tedchou12/webull/blob/0125e51d6fe097cb66e18f9ee05eb917d8782e9c/webull/webull.py#L549

**Comment by tedchou12** [comment]
Thank you for the coffee! ❤️

I took a look at the script and it is very likely that the endpoint itself has been updated.
I am trying to find OTOCO order on webull web interface on desktop, but seems like there is no such option. Are you able to find the OTOCO order placement on the desktop UI?

**Comment by tedchou12** [comment]
@matthyatt15 
I tried the function with the latest version just now. Seems like the order was placed successfully and the response is correct.
`{'comboId': 'BCJS0RH2C12312312313LQEONAB', 'lastSerialId': '61f9324fda901231001b1a1ce'}`
