### ISSUE TITLE
Can you add the function for getting the instant quote information?

### ISSUE THREAD

**Issue by duanlian0903** [tedchou12/webull#3]
I want to get the instant bid and ask price to determine the order. Thank you very much!

**Comment by tedchou12** [comment]
Thanks for the request.
Try this one: `get_quote()`.
Example response:
```
$bash>:quant ted_chou12$ python3 webull.py 
{'tickerId': 913243251, 'derivativeSupport': 1, 'tradeTime': '2019-06-21T15:33:17.658+0000', 'status': 'T', 'close': '295.01', 'change': '0.58', 'changeRatio': '0.0020', 'netAsset': '265282403904.00', 'totalAsset': '267597254767.63', 'timeZone': 'America/New_York', 'tzName': 'EDT', 'preClose': '294.43', 'open': '294.14', 'high': '295.52', 'low': '293.76', 'vibrateRatio': '0.0060', 'avgVol10D': '65542345', 'avgVol3M': '71372976', 'volume': '29478020', 'pe': '0.0000', 'peTtm': '0.0000', 'eps': '0.0000', 'epsTtm': '0.0000', 'fiftyTwoWkHigh': '296.31', 'fiftyTwoWkLow': '233.76', 'dividend': '5.42', 'yield': '0.0184', 'baSize': 0, 'returnThisYear': '0.1891', 'rating': 4, 'inceptionDate': '1993-01-22', 'beta3Y': '1', 'currencyCode': 'USD', 'lotSize': '1'}
```

**Comment by duanlian0903** [comment]
Thank you very much. It is working! I am just curious how can you get the api link. Did webull release it in some place or you figure it out in a different way?

**Comment by tedchou12** [comment]
You are welcome.
Actually, the endpoints are retrieved from the browser Request and Response information. Hash part was gotten from the JavaScripts. =)

**Comment by hz2018tv** [comment]
any way to get batch quotes like a list of tickers separated by comma at one shot?

**Comment by tedchou12** [comment]
Let me take a look at this one. I am not sure if webull accepts this format in their server.
