### ISSUE TITLE
get_watchlist 500 error

### ISSUE THREAD

**Issue by dnapier** [tedchou12/webull#301]
Will update with error and details tomorrow. Leaving this as a placeholder reminder but it seems the endpoint has changed.

**Comment by dnapier** [comment]
![image](https://user-images.githubusercontent.com/19673339/155004445-3c6bcf83-b4a3-4948-b460-6b0d1db60687.png)
![image](https://user-images.githubusercontent.com/19673339/155004492-ae0d1655-6922-4545-b89f-c7aaa3658efd.png)

**Comment by dnapier** [comment]
Just for further detail, I believe the API has changed and this component is now being handled by client side JavaScript. Have not been able to confirm though

**Comment by dnapier** [comment]
Have researched it some, looks like that data is stored in the IndexedDB and controlled by a couple of the many `.js` files imported from `wbstatic.webullfintech.com/v1/webquotes-g/..`. That's as far as I'm going with it. Reading symbol stripped JavaScript is too painful.

**Comment by ssheikh098** [comment]
dnapier,

the error code 401 triggers when we have authorization issue. Make sure to set access token before calling the get_watchlist. 

Thanks

**Comment by ssheikh098** [comment]
401 error seems to be authorization issue. Its working fine for me.

![image](https://user-images.githubusercontent.com/14261211/155053710-bc4020f9-bc16-4a0f-90b8-d47899441ce3.png)

**Comment by dnapier** [comment]
Thank you for verifying. I won't be able to confirm until Wednesday, but the raw output matches that described in the wiki, so you very likely are correct.

**Comment by dnapier** [comment]
Hmm.. doesn't seem to be that. I am successfully logged in and get the same result.

![image](https://user-images.githubusercontent.com/19673339/155406156-b6edb207-1f61-434c-8dc4-6605afebb7f9.png)
![image](https://user-images.githubusercontent.com/19673339/155406271-f61e7b6a-c461-45f6-a796-99f7215ad3ee.png)

**Comment by ssheikh098** [comment]
Can you check header - from this point to see if it has access token

![image](https://user-images.githubusercontent.com/14261211/155407740-de42d44d-0f92-4ec9-86dd-6373e08a11e4.png)

**Comment by dnapier** [comment]
Indeed, it does.
![image](https://user-images.githubusercontent.com/19673339/155409374-0c8e41bf-1994-40c7-a603-86b3cf74802c.png)

I removed it from the request screenshot above as sensitive information.
