### ISSUE TITLE
get_positions for option ticker

### ISSUE THREAD

**Issue by shalli2** [tedchou12/webull#303]
How do I get the strike price and expiry for the option ticker in account positions? The current feature seems to return only the underlying symbol.

**Comment by mrazum** [comment]
shalli2, try this:
  response = requests.get('https://tradeapi.webullbroker.com/api/trade/v4/home/' + self.account_id , headers=headers)
  result = response.json()
  print result['positions2']

**Comment by shalli2** [comment]
How to use this request while I use the python version of webull. In other words, what should be the headers and account_id and how to reuse the MFA, secret questions, etc.. that is currently working with python webull in my case.

> shalli2, try this: response = requests.get('https://tradeapi.webullbroker.com/api/trade/v4/home/' + self.account_id , headers=headers) result = response.json() print result['positions2']

**Comment by shalli2** [comment]
> shalli2, try this: response = requests.get('https://tradeapi.webullbroker.com/api/trade/v4/home/' + self.account_id , headers=headers) result = response.json() print result['positions2']

How to use this request while I use the python version of webull. In other words, what should be the headers and account_id and how to reuse the MFA, secret questions, etc.. that is currently working with python webull in my case.

**Comment by mrazum** [comment]
the same way as you using get_account(). Headers and account_id are the same.

**Comment by shalli2** [comment]
> the same way as you using get_account(). Headers and account_id are the same.

Thank you so much.. it worked.
