### ISSUE TITLE
Does this API still work?

### ISSUE THREAD

**Issue by phillypro** [tedchou12/webull#304]
like does this api still login successfully, place orders and such?
just checking as i know webull has changed alot and even requires a captcha on their web login

**Comment by tedchou12** [comment]
@phillypro 
Yes, the majority part of it is still working.
I do realize that Webull added the captcha during login some time ago, so using the API alone to login might become increasingly difficult.
But I advise using the Chrome inspect method to get the tokens and save it for the long term, as mentioned in here:
https://github.com/tedchou12/webull/wiki/Workaround-for-Login

I have just tried the flow again and it works perfectly!
