### ISSUE TITLE
get_options has stopped working today, returns a json error

### ISSUE THREAD

**Issue by dovega** [tedchou12/webull#305]
Hello,

Looks like the endpoint for get_options has stopped working today. It now returns this json error when trying to unpack the response using json():
`requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0`

The response code itself is 200, so it seems like it's getting something back. Also, the other endpoints work just fine still(at least the ones I've tried). Has this one changed at all?

The specific endpoint that is causing trouble is this one:
`def options(self, stock):
    return f'{self.base_options_url}/quote/option/{stock}/list'` 

Can anyone else verify that the endpoint is not working as expected?

**Comment by grm083** [comment]
I opened and closed issue 306 as I've also encountered this.  I've noticed that the API call is returning a success code of 200 but the content is empty.  I believe this may be an issue with the endpoint itself, they may have updated or deprecated it.

**Comment by ryanblenis** [comment]
API endpoints have been updated in various places. They've also enabled cert pinning in their apps, making it harder to find the calls to update

**Comment by grm083** [comment]
It does appear that they're routing them through https://quotes-gw.webullfintech.com/api/quote/option/strategy/list instead, with a payload of:

* Ticker Id (obtained through the get_ticker call)
* Count (Number of options to return in the call)
* Direction
* expireCycle (this one may need some deciphering, looks like it requires a list of integers)
* Type (0, making an assumption that this will be defaulted to 0)
* quoteMultiplier (100, how many shares are obtained when the contract is redeemed)

I can probably play with this a little later and see if I can make any headway.

**Comment by dovega** [comment]
> It does appear that they POST them through https://quotes-gw.webullfintech.com/api/quote/option/strategy/list instead, with a payload of:
> 
> * Ticker Id (obtained through the get_ticker call)
> * Count (Number of options to return in the call)
> * Direction
> * expireCycle (this one may need some deciphering, looks like it requires a list of integers)
> * Type (0, making an assumption that this will be defaulted to 0)
> * quoteMultiplier (100, how many shares are obtained when the contract is redeemed)
> 
> I can probably play with this a little later and see if I can make any headway.

Been fiddling with this using the following params:
`params = {'tickerId': self.get_ticker(stock),
                  'count': count,
                  'direction': 'all',
                  'expireCycle': [3, 2, 4], #this is what defaulted when I used the web browser to find the option chain.
                  'quoteMultiplier': 100,
                  'type': 0}`

Getting an error message though, ''Parameters type miss match'. Hmm.

**Comment by fredflynn** [comment]
I am getting the same.  I hope they are not checking for a referer: https://app.webull.com/ on the call to block automated requests.  With the params all matching what I see going out from the desktop app that is certainly my hunch though.  

this was my code to test:
ticker_id = wb.get_ticker("AAPL")
headers = wb.build_req_headers()
data = {"tickerId": ticker_id, "count": -1, "direction": "all", "expireCycle": [3, 2, 4], "type": 0, "quoteMultiplier": 100}
target = "https://quotes-gw.webullfintech.com/api/quote/option/strategy/list/"
response = requests.get(target, params=data, headers=headers)

**Comment by jjqqkk** [comment]
I have got some workaround.

1. Query option list. (POST)

curl -XPOST https://quotes-gw.webullfintech.com/api/quote/option/strategy/list -H "content-type:application/json" -d '{"tickerId":913244796,"count":-1,"direction":"all","expireCycle":[3,2,4],"type":0,"quoteMultiplier":100}'

The result is a HUGE json in which we can find the complete option expire date list and each option's tickerID. We need the tickerID in the next HTTPS request. 

{
            "strikePrice": "27",
            "volume": "0",
            "latestPriceVol": "0",
            "expireDate": "2022-06-03",
            "tickerId": 1032363507,
            "belongTickerId": 913244796,
            "activeLevel": 27,
            "cycle": 2,
            "weekly": 1,
            "executionType": "A",
            "direction": "call",
            "derivativeStatus": 0,
            "currencyId": 247,
            "regionId": 6,
            "exchangeId": 189,
            "symbol": "SQQQ220603C00027000",
            "unSymbol": "SQQQ",
            "quoteMultiplier": 100,
            "quoteLotSize": 100
        }


2. Get the option quotes. (GET)
 
GET this endpoint with a list of option ticker IDs.

curl "https://quotes-gw.webullfintech.com/api/quote/option/quotes/queryBatch?derivativeIds=1032283511,1032363508,1032363507"

**Comment by grm083** [comment]
Awesome stuff!  I saw the batch query string as well but the derivative I'd was eluding me.  I'll give this a shot this morning as well!  You should be able to control the size of the response by specifying count as well.  If you're tracking a ticker like SPY where there are hundreds it could be alot to sift through, but I would imagine a count of 10 would account for 5 above and 5 below the current trading price.

**Comment by dovega** [comment]
Just to update, cURL gets the data just fine. Still having no luck with httpx.

**Comment by BobLiu20** [comment]
It is working well for me.

`
import requests
json_data = {
    'tickerId': 913244796,
    'count': 1,
    'direction': 'all',
    'expireCycle': [
        3,
        2,
        4,
    ],
    'type': 0,
    'quoteMultiplier': 100,
}

response = requests.post('https://quotes-gw.webullfintech.com/api/quote/option/strategy/list', json=json_data)
print(response.json())
`

**Comment by dovega** [comment]
That's working for me too. I think I was missing the "json" field and that's why it was failing. Thanks BobLiu20, jjqqkk, and grm083.

**Comment by jjqqkk** [comment]
Verified, thank every one working on this issue.

**Comment by dovega** [comment]
Closing this since we've found a workaround.

**Comment by zenhorace** [comment]
Thanks everyone for the work done here. I'm reopening this until the fix is integrated into this package and doesn't require a custom workaround by users of the package.

**Comment by fredflynn** [comment]
Anyone else having trouble with the work around?  It worked for me yesterday and is now returning an empty response.

**Comment by gbtota** [comment]
Yep, same issue with POST request now "200" OK but no body content; was working yesterday.

**Comment by grm083** [comment]
Oh jeeze sorry!  An additional important note.  It does seem that this query is all or nothing.  If you try to specify a count parameter as anything other than -1 it seems to break.  So depending on the ticker you could be getting a really big payload as a response.

There is a mismatch between what you'd see on the UI and what you see in the payload (UI selection + 10), but modifying based on selections made there doesn't seem to make much of a difference.

![image](https://user-images.githubusercontent.com/72616030/165850065-7dc15efd-e8b1-4ddc-8c35-11a41f646d1f.png)

**Comment by Jakezheng** [comment]
https://chat.whatsapp.com/BdYPQv7yJwtEL7AiteceL0   guys join the group we share idea faster

**Comment by mrazum** [comment]
> https://chat.whatsapp.com/BdYPQv7yJwtEL7AiteceL0 guys join the group we share idea faster

Do you have similar group in Telegram?

**Comment by dovega** [comment]
I can confirm that this has stopped working for me as well. Here's my code. It was working yesterday.

```
params = {'tickerId': webull.get_ticker(self, 'AAPL'),
          'count': -1,
          'direction': 'all',
          'expireCycle': [3, 2, 4],
          'type': 0,
          'quoteMultiplier': 100}

import httpx
client = httpx.Client(http2=True)

response = client.post('https://quotes-gw.webullfintech.com/api/quote/option/strategy/list', json=params)
```

Gives a json decode error:

`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Jakezheng** [comment]
telegram group guys join up and help each other
https://t.me/+tXp2V59FAIUyYzkx

**Comment by gbtota** [comment]
ok solved, you need almost all of the headers in the request device-type,os,ph,hl,platform,reqid,osv all of there are required now

**Comment by Jakezheng** [comment]
> ok solved, you need almost all of the headers in the request device-type,os,ph,hl,platform,reqid,osv all of there are required now

yeah man , i copy everything from the chrome devtool lol

**Comment by dovega** [comment]
> yeah, my firefox version, update webull.py
> 
> ```
> self._headers = {
>             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0',
>             'Accept': '*/*',
>             'Accept-Encoding': 'gzip, deflate',
>             'Accept-Language': 'en-US,en;q=0.5',
>             'Content-Type': 'application/json',
>             'platform': 'web',
>             'hl': 'en',
>             'os': 'web',
>             'osv': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0',
>             'app': 'global',
>             'appid': 'webull-webapp',
>             'ver': '3.39.18',
>             'lzone': 'dc_core_r001',
>             'ph': 'MacOS Firefox',
>             'locale': 'eng',
>             'did': self._get_did()
>         }
> ```

Unfortunately, this is not working for me. Still using httpx with http2. Maybe I'll play around with those things and see if your header changes start to work.

**Comment by jjqqkk** [comment]
Try this one:

```
self._headers = {
            'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0',
            'Accept': '*/*',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'en-US,en;q=0.5',
            'Content-Type': 'application/json',
            'platform': 'web',
            'hl': 'en',
            'os': 'web',
            'osv': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0',
            'app': 'global',
            'appid': 'webull-webapp',
            'ver': '3.39.18',
            'lzone': 'dc_core_r001',
            'ph': 'MacOS Firefox',
            'locale': 'eng',
            'reqid': 'feb46a9524574a59b8f121c8eab62023',
            'device-type': 'Web',
            'did': self._get_did()
        }
```

You may change reqid to any 32-byte random hash value.

More testing needed in today's trading session, lets see.

**Comment by dovega** [comment]
> Try this one:
> 
> ```
> self._headers = {
>             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0',
>             'Accept': '*/*',
>             'Accept-Encoding': 'gzip, deflate',
>             'Accept-Language': 'en-US,en;q=0.5',
>             'Content-Type': 'application/json',
>             'platform': 'web',
>             'hl': 'en',
>             'os': 'web',
>             'osv': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0',
>             'app': 'global',
>             'appid': 'webull-webapp',
>             'ver': '3.39.18',
>             'lzone': 'dc_core_r001',
>             'ph': 'MacOS Firefox',
>             'locale': 'eng',
>             'reqid': 'feb46a9524574a59b8f121c8eab62023',
>             'device-type': 'Web',
>             'did': self._get_did()
>         }
> ```
> 
> You may change reqid to any 32-byte random hash value.
> 
> More testing needed in today's trading session, lets see.

This returns an unauthorized user error:

`'msg': 'unauthorized user', 'code': '417'`

XD

**Comment by tedchou12** [comment]
Sorry about the ignorance. The random reqid does fix the issue. It seems like Webull is demanding the headers as well.
I think the package has been updated, and pushed to pypi as well.
Thank you for the investigation!

**Comment by nirmalc83** [comment]
@tedchou12  Still doesnt seem to work, getting the same error after upgrading the package. Any thoughts?

**Comment by JonECG** [comment]
I'm still getting this issue... sometimes...

I feel like its 50:50

Half the time, after the update, get_options works as expected, the other time I get an OK in the response, but it's empty. Causing the original decode exception when trying to parse it as JSON.

**Comment by JonECG** [comment]
@tedchou12 

Could you try running
``` Python
for lp in range(100):
    options = wb.get_options("MMM")
    print(len(options))
    time.sleep(1) # maybe rate limiting? idk
```

and see if you get through a good chunk? I can't get past 5 or 10 before getting an exception

**Comment by JonECG** [comment]
After further testing, it _seems_ it's not related to reqid. Fixing it to a specific reqid can work for a bit, but then it will eventually fail.

**Comment by JonECG** [comment]
It looks like it also happens in `get_options_expiration_dates`

**Comment by JonECG** [comment]
On the bright side, it looks like get_options_bars works flawlessly. So, I've just been silently retrying the other two functions until I get the tickers I need as a workaround:
``` python
def get_options_s(stock=None, count=-1, includeWeekly=1, direction='all', expireDate=None, queryAll=0):
    result = None
    while result is None:
        try:
            result = wb.get_options(stock, count, includeWeekly, direction, expireDate, queryAll)
        except:
            print("get_options failed, retrying")
    return result
    
def get_options_expiration_dates_s(stock=None, count=-1):
    result = None
    while result is None:
        try:
            result = wb.get_options_expiration_dates(stock, count)
        except:
            print("get_options_expiration_dates failed, retrying")
    return result
```

**Comment by tedchou12** [comment]
you are right, it is very intermittent. 🤔
There are two possibilities
- Webull's server error, may be they have a bug somewhere? (less likely, as it is working some times?)
- Webull is trying to do some rate limiting? (more likely, but that should affect the web app as well)

**Comment by grm083** [comment]
The updated endpoint doesn't use immediate refresh or streaming, it seems to update at set intervals (every 3 seconds for example) 

When wrapping the callout in a try/catch loop, I've noticed it usually doesn't error out more than 2 times before succeeding.  On the source side you may consider a while loop, not to exceed 10 retries, to combat it.  Otherwise handling this client side isn't a huge effort.

**Comment by grm083** [comment]
> On the bright side, it looks like get_options_bars works flawlessly. So, I've just been silently retrying the other two functions until I get the tickers I need as a workaround:

I added an iterator, not to exceed count 10, just to ensure it doesn't get stuck if something changes again in the near future.

**Comment by tedchou12** [comment]
I gave it a try:
```
200
Success
200
Success
200

Failed
200
Success
200
Success
200
Success
200
Success
200
Success
200
Success
200

Failed
200
Success
200
Success
200
Success
200

Failed
200
Success
200

Failed
200
Success
200
Success
200
Success
200
Success
200

Failed
200
Success
200
Success
200

Failed
200
Success
200
Success
```
The response code is always 200, but the result is empty compared to 60000+bytes of json string.

@grm083 
That's one work around, but it makes the code a bit more messy, we can try that temporarily.

I am pretty sure this would affect Webull's own WebApp, so there might be other ways to make this work.

**Comment by tedchou12** [comment]
Dear All.

Thanks for the discussion here.

After some time investigating, I realized that the webapp endpoint for option is updated. This is probably a good reason for intermittent success on the old endpoint. My guess is that they did not stop it completely, but some servers have it stopped working, so with some load balancing, if you are responded by servers that have deprecated the endpoint would result in the empty response or the json error.

It is likely that the old endpoint will be stopped completely, so I updated the endpoint. The response is not completely the same some some variables have been changed. I tried to respond it in the same format so the code might look a bit messy. I tried calling the new endpoint 30+ times and found it working 100%. The new endpoint is a bit fat though, so it's taking webull's server a bit longer for each request.

I am happy it's solved. Sorry for the delayed response. I am a bit busy with job interviews and I try to shy away from my investing recently since the market is doing so bad. Thanks to Yashwant who has been encouraging me on LinkedIn and on the buymecoffee app. If you like I do, you can post some kind words to me too. 😂🙏🙏🙏
