### ISSUE TITLE
Getting "code":"trade.webull.DAY_BUYING_POWER_INSUFFICIENT"

### ISSUE THREAD

**Issue by Peddineni** [tedchou12/webull#31]
I am getting below response when i am trying to place order.. Did you see error like below, your input would be appreciated.

**<200,{"success":false,"code":"trade.webull.DAY_BUYING_POWER_INSUFFICIENT","msg":"Buying power is insufficient, please cancel open buy orders(if there is any) and try again**

right now I don't have 25k in my account . Is it because of that ??.. Just FYI I am able to place order from mobile app.

Thanks

**Comment by b0b5h4rp13** [comment]
nope, doing more than 3 day trades per 5 business days in a margin account would cause your account to be locked for 90 days, so would be a different mesage

**Comment by Peddineni** [comment]
Then i am not sure why i am receiving that error.. Do u think if i reach webul support they can help ??
There is no other information why i am not able to place order..

**Comment by b0b5h4rp13** [comment]
Webull won't support this 3rd party api. You should check what your trying to order to make sure the ticker, qty and lmt price are correct in your code. Be aware there is no guarantee that this api will work correctly, so use at your own risk of loss/error messages.

**Comment by tedchou12** [comment]
@Peddineni 
Do you have enough funds in your account? Could you trade with the webull app?
I would give that a try first.
`DAY_BUYING_POWER_INSUFFICIENT` seems like you are not having enough funds in your account.
As mentioned by Bob too, make sure your qty and ticker are correct.
If you can keep us posted about the answers above? We will look into more.

**Comment by Peddineni** [comment]
> @Peddineni
> Do you have enough funds in your account? Could you trade with the webull app?
> I would give that a try first.
> `DAY_BUYING_POWER_INSUFFICIENT` seems like you are not having enough funds in your account.
> As mentioned by Bob too, make sure your qty and ticker are correct.
> If you can keep us posted about the answers above? We will look int

**Comment by Peddineni** [comment]
Yes i tried with webull app for the same ticker and it is working fine. Actually i created Java client equivalent to your python program, everything seems to be good and working fine..
