### ISSUE TITLE
does anyone know how to trading options of SPX

### ISSUE THREAD

**Issue by BobLiu20** [tedchou12/webull#313]
I don't konw how to get option Id for SPX option. In my experience, other brokers generally use SPXW as symbol. But seems not working in webull api.

**Comment by jeevanpillai** [comment]
Here's the tickerId for SPXW

`{
        "name": "S&P 500",
        "symbol": "SPX",
        "tickerId": 913354362
}`

You can get the list of SPXW options using the following Python code:

`
url = "https://quotes-gw.webullfintech.com/api/quote/option/strategy/list"
payload = {"tickerId":913354362,"count":-1,"direction":"all","expireCycle":[3,2,4],"type":0,"quoteMultiplier":100}
data = r.post(url=url, json=payload, headers=req_hdrs)
`
* note: include your access_token in the `req_hdrs` dict


Here's the full list as of 30 June, 2022 along with a Python script to regenerate it.
[Link to GitHub Gist](https://gist.github.com/jeevanpillai/f16e5169b79404c5c0ef6f6a023b5444)
