### ISSUE TITLE
Active Gainers / Losers List 

### ISSUE THREAD

**Issue by TestyTesties** [tedchou12/webull#32]
Hey guys,

Great job so far on all of the work that's been done here. I've been able to connect up and place an order using this API so far and it's been rather painless.

One of my objectives here is to be able to pull out the active gainers / losers lists that are on webull's app (market section) to use for further analysis. When pulling this info using get_active_gainers_losers(), I get a list of names (about 20 long). However, this list does not match up with the gainers list (1-day) when comparing to the app.

My question is: Is there a option to choose the time frame of the list (i.e. 5-minute, 1-day, pre-market, after-hours, etc.) of the list that's being produced?
To build further, is there an option to choose the length of the list being returned (it seems the Webull lists have no limit)?

Let me know when you get the chance. Looking forward to helping out any way I can.

Thanks!

**Comment by b0b5h4rp13** [comment]
enhance it,  and share back with the ted... look at the web developer item on your browser menu and pick network to open the network tracker look at the link that the app uses when you click the button. you can get to webull via https://app.webull.com/trade
