### ISSUE TITLE
How to download *multiple* tickers in one request?

### ISSUE THREAD

**Issue by alexh0101** [tedchou12/webull#327]
Trying to do a get_bar() for multiple tickers.

Is there a built-in way for doing that?

Or should I do some kind of async/multithreading?
If so, how should I go about it (which package)?

**Comment by ICANTFINDAUSERNAMEATALL** [comment]
you can just run a for loop with all the bars. multicoring doesn't work for me but multithreading might.

**Comment by tedchou12** [comment]
@alexh0101 
You can take a look at this one:
https://realpython.com/intro-to-python-threading/

But unless is necessary, I don't recommend it. I use it myself because the download IO requests doesn't take up CPU, so running APIs reaches IO bottleneck.
