### ISSUE TITLE
not callable

### ISSUE THREAD

**Issue by Zihanouk** [tedchou12/webull#33]
so right now all i have is:

```
import pytest
import webull
webull = webull()
webull.login('************', '*********')
webull.get_account_id()
webull.get_trade_token('123456')
print(webull.get_account())
```

and all I'm getting right now is:

```
    webull = webull()
TypeError: 'module' object is not callable
```

how do I fix this

**Comment by b0b5h4rp13** [comment]
I see you're taking your first steps in python..  
either use:
from webull import webull
webull = webull()
----------or -----------
import webull
webull = webull.webull()

**Comment by knurts** [comment]
This is a great point. would one of you mind updating the readme to include the import line in the examples? I'd be happy to review and merge the request.  Then it won't be too unclear for others in the future
