### ISSUE TITLE
are there any callbacks for webull ? 

### ISSUE THREAD

**Issue by mzaeemnasir** [tedchou12/webull#332]
Basically, I want to place a Sell order (on options ) once my Order is Fulfilled and I am looking for a callback for orders filled!

**Comment by tedchou12** [comment]
@mzaeemnasir 
using websocket on_order should work. the websocket will receive a push signal whenever an order is filled.
https://github.com/tedchou12/webull/wiki/How-to-use-Streaming-Quotes%3F

**Comment by mzaeemnasir** [comment]
Got It Thanks @tedchou12
