### ISSUE TITLE
Any way to convert this library to C++ or another multi-threaded language?

### ISSUE THREAD

**Issue by Alanavai** [tedchou12/webull#335]
Python's GIL effectively limits CPU-bound operations to a single thread, which can be quite slow. Is there any way to convert this library's code (i.e. how it interacts with Webull's API) to a language like C++ or Java?

**Comment by tedchou12** [comment]
Actually, there are GPU accelerators with numba, you can achieve quite similar results.
In addition, you can rewrite the api in C++ or Java yourself, this code is inherently just communicating with webull apis, there is nothing preventing you from doing it with another programming language.

**Comment by Alanavai** [comment]
@tedchou12 Yeah rewriting would work, just need to figure out how to emulate all the authentication and other actions. Thanks.
