### ISSUE TITLE
Fractional shares

### ISSUE THREAD

**Issue by kasbah512** [tedchou12/webull#348]
Getting failure upon submitting fractional order for stocks with place_order()
the order placed was for more than $10, but less than one share of a stock. 
error message: 
{'success': False,
 'code': 'trade.system.exception',
 'msg': 'The system is busy',
 'data': {'lastSerialId': 'XXXXXXXXXXXXXXXXXX}}

**Comment by kasbah512** [comment]
*** Correction, fractional shares are only available via mobile application.

**Comment by tedchou12** [comment]
If that is the case, is difficult to to include it into the apis.
