### ISSUE TITLE
option orders giving a 403

### ISSUE THREAD

**Issue by mzupan** [tedchou12/webull#35]
I have the following option from a `webull.get_options(stock="JCP", expireDate="2020-05-01")`

```
{'strikePrice': '2.00', 'call': {'tickerId': 1014438795, 'close': '0.0100', 'change': '0.000', 'changeRatio': '0.0000', 'volume': '12', 'preClose': '0.0100', 'open': '0.0100', 'high': '0.0100', 'low': '0.0100', 'askList': [{'price': '0.0100', 'volume': '6'}, {}, {}, {}, {}, {}, {}, {}, {}, {}], 'bidList': [{'price': '0.0000', 'volume': '0'}, {}, {}, {}, {}, {}, {}, {}, {}, {}], 'strikePrice': '2.00', 'direction': 'call', 'expireDate': '2020-05-01', 'openInterest': 11, 'openIntChange': 0, 'impVol': '8.4971', 'gamma': '0.0000', 'theta': '0.0000', 'vega': '0.0000', 'rho': '0.0000', 'delta': '0.0000', 'activeLevel': 4, 'weekly': 1, 'quoteMultiplier': 100, 'unSymbol': 'JCP'}, 'put': {'tickerId': 1014438799, 'close': '1.960', 'change': '0.210', 'changeRatio': '0.1200', 'volume': '18', 'preClose': '1.750', 'open': '1.580', 'high': '1.960', 'low': '1.580', 'askList': [{'price': '1.960', 'volume': '9'}, {}, {}, {}, {}, {}, {}, {}, {}, {}], 'bidList': [{'price': '1.310', 'volume': '1'}, {}, {}, {}, {}, {}, {}, {}, {}, {}], 'strikePrice': '2.00', 'direction': 'put', 'expireDate': '2020-05-01', 'openInterest': 1, 'openIntChange': 0, 'gamma': '0.0000', 'theta': '0.0000', 'vega': '0.0000', 'rho': '0.0000', 'delta': '-1.0000', 'activeLevel': 4, 'weekly': 1, 'quoteMultiplier': 100, 'unSymbol': 'JCP'}}
```

I'm using the `tickerId` as the optionId which seems to be the same as the webull client is going on network inspecting

I'm trying this

```
webull.place_option_order(optionId="1014438795", lmtPrice=0.01, action='BUY', orderType='LMT', enforce='DAY', quant=1)
```

I'm getting a 403

```
Traceback (most recent call last):
  File "./main.py", line 19, in <module>
    webull.place_option_order(optionId=1014438795, lmtPrice="0.01", action='BUY', orderType='LMT', enforce='DAY', quant=1)
  File "/Users/mzupan/mz/option-trader/webull.py", line 443, in place_option_order
    raise Exception('place_option_order failed', response.status_code, response.reason)
Exception: ('place_option_order failed', 403, 'Forbidden')
```

Is this because of the issue of not being able to trade options on webull over the weekend? The web client does a 200 but my guess is the endpoint might be different.

**Comment by abhifc720** [comment]
I am getting the same error.? Market is open, but still same error while buying an option.

**Comment by zenhorace** [comment]
Did you supply your trade token as well? Please detail the steps you took to produce this issue (hiding credentials & tokens)

**Comment by abhifc720** [comment]
Yes, I am using the Credentials file to supply tokens to the webull wrapper. I tried the Place_Order function and It is working without an issue.

But yesterday, I was trying to use the place_option_order function and It showed me the below error. I am just trying to create a Limit Option order.

Exception: ('place_option_order failed', 403, 'Forbidden')

**Comment by abhifc720** [comment]
Steps:-
1.) I searched in the Option by using this API function "get_options_by_strike_and_expire_date", It provided me the TickerId for the option, I needed.
2.) When I got the TickerId, Then I tried to place Order by using the API function "place_option_order". By following params:-

wblClient.place_order_option(optionId="{tickerId}", lmtPrice=0.50, action='BUY', quant=1)

And It throws the exception stated in this ticket/Issue.
Exception: ('place_option_order failed', 403, 'Forbidden')


Note:- place_order function works perfectly, Only Option Order has this issue.

**Comment by bulletbeall** [comment]
Just to piggyback on it with another aspect.

place order with:
wb.place_order_option(optionId=1021054034,lmtPrice=14.05,stpPrice=None,action="BUY",orderType="LMT",enforce="GTC",quant=1)
Exception: ('place_option_order failed', 403, '')

Maybe the endpoint changed? who knows

**Comment by tedchou12** [comment]
Sorry, let me take a look at it this weekend!

**Comment by tedchou12** [comment]
@bulletbeall 
I had no problems.
```
wb.get_trade_token('123456') #did you do this before you place the order?
print(wb.place_order_option(optionId='1021054034', lmtPrice='0.1', action="BUY" , orderType="LMT", enforce='GTC', quant=1))
```
response
```
{'orderId': 515064137747791872, 'comboId': '9BGI04PJ28VB2914NFG6G9MSF9'}
```

**Comment by bulletbeall** [comment]
Tried again today and it works. No idea why, nothing changed except the wifi im on. Sorry to bother...
