### ISSUE TITLE
Having Issues with login

### ISSUE THREAD

**Issue by tsuyosi81** [tedchou12/webull#351]
I attempted to login into WeBull and it was working fine until I tried to login with wrong inputs. Now I'm getting an error that says "too many failed verification attempts." Is there anything I can do about it or should I just contact with WeBull customers services to resolve this? I still can login through my mobile app but not through my codes.

Here is the error:

`'msg': 'Unavailable because of too many failed verification attempts. Please contact us if you need help.', 'traceId': 'd9a480d9337a4e0b932bb39454670a88', 'code': 'user.answer.error.max.times'`

**Comment by tedchou12** [comment]
Sorry, I don't think I have experienced it. What if you wait for a day? If not, may be contacting the support might be needed.

**Comment by tedchou12** [comment]
Btw, I don't recommend using the login function. I recommend the work around for login page method.

**Comment by AdriandLiu** [comment]
@tsuyosi81 I saw this before, I contacted Webull customer service and asked them to allow me to reset my security question. After resetting, use your new questions and answers, it should work fine
