### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by mdlivingston** [tedchou12/webull#353]
Hello I am receiving the error when attempting to login:

 {'success': False, 'code': 'account.version.upgrade', 'msg': 'You are using an outdated version of Webull Desktop. Please update your application by visiting www.webull.com/introduce.'}

Any any to fix this?

**Comment by ICANTFINDAUSERNAMEATALL** [comment]
I get the same error as well. I think this api may be a bit outdated :(

**Comment by joecat808** [comment]
Same issue here, same error message as above.

(Login still works if I use the MFA with a security code sent through email)

**Comment by ICANTFINDAUSERNAMEATALL** [comment]
Really? let me try. Did all the functions work after you completed the login or are you saying something else?

 I noticed that the version that webull web is 3.39.24, not 3.39.18. There are also tons of missing headers in the requests but idk which ones are needed and which ones are optional. 
![image](https://user-images.githubusercontent.com/55333717/203361039-cb295dc0-4a5a-4ecb-9fcf-a73de21dd2b5.png)
![image](https://user-images.githubusercontent.com/55333717/203361107-090fa1e0-0ca7-4171-ae9d-4d233ff63a9e.png)

**Comment by ICANTFINDAUSERNAMEATALL** [comment]
Ok I think I fixed the login problem. You got to switch the endpoints base user url to this:

self.base_user_url = 'https://u1suser.webullfintech.com/' # https://userapi.webull.com/api this is the old one

and also change the login function to this:

return f'{self.base_user_url}/api/user/v1/login/account/v2' # f'{self.base_user_url}/passport/login/v5/account' old base url

after modifying these, it seems to work but other functions like refresh login probally won't work.

**Comment by AdriandLiu** [comment]
Thanks for @ICANTFINDAUSERNAMEATALL 's investigation, the URL indeed works!

However, I'm having another issue. It seems after switching to the new login url, all new login requires image verification, which is not possible through the API call, anyone got any ideas.

**Comment by AdriandLiu** [comment]
Okay I found an alternative. Here are the steps:

1. On homepage of Web Webull, right-click to open _Inspect_ -> _Network_ (on the top)
2. Login with your credentials, first-time login will trigger image verification
3. At the same time, _Network_ will print many traffic logs, among them, go to _Name_ and select _v2_ from the first one to the end until you find, **_deviceId_** and **_deviceName_** from _Payload_ -> _Request Payload_. 
4. Copy and paste them in your code, **deviceId = self._did** & **deviceName = device_name in login method**
5. Try to login again

Hope this helps

**Comment by cmay10** [comment]
I'm having this problem also.

**Comment by anthony-hobson** [comment]
@AdriandLiu I tried that same and still no cigar. When you get the response back, are you still getting the accessToken json?

Access Token, Refresh Token, UUID, and Token Expire? If so, were you able to use the api login from there?

**Comment by ICANTFINDAUSERNAMEATALL** [comment]
Once you login once with the webull api, you should be able to just login with the .login function. For me, the access token thing hasn't worked for me.

**Comment by TheWakandaMamba** [comment]
@ICANTFINDAUSERNAMEATALL Correct. I am not able to grab the access token information to be able to use the login.

**Comment by ICANTFINDAUSERNAMEATALL** [comment]
just use the original login function:

wb.login(email, pw, whatever else)

once you login the first time, you won't need to reverify each time.

**Comment by TheWakandaMamba** [comment]
@ICANTFINDAUSERNAMEATALL Not sure what was happening the other day but I was having trouble with that. Probably because I hadn't changed the URL. I am good now. Thank you for the quick responses!

**Comment by TheWakandaMamba** [comment]
Just a heads up guys, I finally realized why I was having trouble just using the wb.login function. I started a new python project that was using a new "did.bin" file and like mentioned above, you will get the "Fail to verify image verification code".

I have not had a chance to look through everything that is getting stored, but the "did.bin" file was my issue. I had an older python project utilizing the stored file and I was able to utilize the function to get back the token info that was needed. 

I would not alter, delete, or change that did.bin file if you are currently utilizing it.

**Comment by BScib** [comment]
@AdriandLiu :: Can you provide they syntax of the code snippit you are referring to? I tried this but am not finding success.

Assuming it is something like this:

`wb.login('EMAIL', 'PASSWORD', deviceId = 'IS THIS JUST THE DEVICEID STRING [NUMBERS] FROM PAYLOAD TAB?', deviceName = 'IS THIS JUST THE DEVICENAME STRING [LETTERS] FROM PAYLOAD TAB?")`

**Comment by AdriandLiu** [comment]
@BScib 
Two approaches:

1. Replace the string inside your **did.bin** file, which usually could be found from the dir you run your script, with device id from payload, then do
```
import pickle
with open("did.bin", "wb") as f:
    pickle.dump("device id from payload", f)

wb.login(
    email,
    password,
    device_name = "Your device name from browser payload tab, e.g. MacOS Chrome in my case",
    ...
)
```
2. Copy the device id from payload and assign to **self._did**
```
wb._did = "device id from payload"
wb.login(
    email,
    password,
    device_name = "Your device name from browser payload tab",
    ...
)
```

**Comment by WilliaNorth** [comment]
Hi,

I stumbled on the same image verification error _"Fail to verify image verification code"_ even after updating _did.bin_ file with deviceId from v2 like @AdriandLiu mentioned. This is a new Python project and I don't have an older one.

Also, I can't find deviceName in v2 - using Chrome for login and Inspect, can anyone help me with the header name?.
Anything else need to be updated in webull.py and endpoints.py?

Thanks for everyone's contribution.

Thanks,
Will

**Comment by BScib** [comment]
> If I am understanding option 1 correctly, I use the same "device id from payload" in two places: the did.bin file in the directory where the script is saved (not where the python library is saved), and in the pickle.dump() call, correct?

I am getting this message:
`{'success': False, 'code': 'account.version.upgrade', 'msg': 'You are using an outdated version of Webull Desktop. Please update your application by visiting www.webull.com/introduce.'}`

 I tried both options, and option 2 is not working either (understanding that I might need a new  "device id from payload" after ever login, correct? Scratching my head

**Comment by AdriandLiu** [comment]
@BScib Have you followed this step in setting up the latest URL? https://github.com/tedchou12/webull/issues/353#issuecomment-1324209081

**Comment by AdriandLiu** [comment]
@BScib  yes, it's the package library. There is a file named "endpoints.py" inside your local webull library, find and replace the specific URL by the instruction above. You can also setup a separate folder inside your project directory and customize it.

**Comment by rakesh433jntu** [comment]
@AdriandLiu  @BScib is there finalized work around to overcome login bug ??

**Comment by BScib** [comment]
@AdriandLiu  :: Your steps worked for me. Thanks for the help.

**Comment by rakesh433jntu** [comment]
@BScib  Hi mate ,, can you add one more timesteps you followed to get it worked  to below.
its big conversation. Not sure which one to follow

**Comment by BScib** [comment]
- This step: https://github.com/tedchou12/webull/issues/353#issuecomment-1324209081
- This is context to that step: https://github.com/tedchou12/webull/issues/353#issuecomment-1338315551

- Then this step: https://github.com/tedchou12/webull/issues/353#issuecomment-1334476914

**Comment by BScib** [comment]
My issue has returned, and now I am getting the image verification failure issue again. Wondering if this is something to do with the did.bin file.

**Comment by tedchou12** [comment]
It seems like the new endpoint (https://u1suser.webullfintech.com/) doesnt work for me.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: C6x_kmNd4jrjyM1eeKkylcK34oCdUsKJvCGd6e19o84czInFq3QeXw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
False
```

**Comment by ICANTFINDAUSERNAMEATALL** [comment]
I think webull only changed the original login endpoint(I didn't realizes or check if it was still working with the other functions, I just assumed webull moved their entire api domain to the new endpoint path(or whatever its called)). 

You want to update the login function's endpoint to this: `https://u1suser.webullfintech.com/api/user/v1/login/account/v2`

I don't think you need to update anything else but I'm not sure because I only use this one.

**Comment by tedchou12** [comment]
Thanks! I believe it should be fixed now!
