### ISSUE TITLE
No package for this project?

### ISSUE THREAD

**Issue by gamesover** [tedchou12/webull#36]
I cannot `pip install webull`

**Comment by tedchou12** [comment]
Sorry, yes, I recommend downloading.
Seems like uploading to PyPI is required for pip to work.

**Comment by Calrider** [comment]
@tedchou12 I uploaded this project to PyPI as 'webull'.  Please let me know what your PyPI username is so I can transfer ownership. I'd be happy to be a maintainer going forward if you'd like.

**Comment by tedchou12** [comment]
great! Thanks for uploading! Please feel free to be keep the ownership.
I would love to join the project:
https://pypi.org/user/ted_chou12/
Any others are welcome to join!! =)
