### ISSUE TITLE
get_mfa not working with new version 0.5.6

### ISSUE THREAD

**Issue by aoyarceLenio** [tedchou12/webull#362]
When using this code:

`username = "user@gmail.com"
    wb = paper_webull()
    mfa = wb.get_mfa(username)
    print(f"Results: {mfa}")`

I always get "False" as return value. 
But if change "base_userfintech_url" from this: "https://u1suser.webullfintech.com" to this: "https://userapi.webull.com", it work again, and I received the email with the mfa code.

**Comment by aoyarceLenio** [comment]
the full URL is this:
`https://userapi.webull.com/api/user/v1/verificationCode/send/v2`

**Comment by tedchou12** [comment]
Yes, sorry, I think I have the same case with you. Let me check with other guys.

**Comment by tedchou12** [comment]
Thanks, the 0.5.8 should work!
