### ISSUE TITLE
Not able to make MKT trades

### ISSUE THREAD

**Issue by smr0056** [tedchou12/webull#368]
Hello,

I am unable to make MKT trades using the API. I get the below exception.
{'success': False, 'code': 'trade.system.exception', 'msg': 'The system is busy', 'data': {'lastSerialId': '***'}}

I am able to make KMT trades though. I tried with different sticks and different amounts.
I did some digging on the browser network tracing since I could make MKT trades through the browser. In the browser, the API endpoint looks a little different than what's present in this github repo.

![image](https://user-images.githubusercontent.com/107905192/209687040-0f4a5cd7-9647-4d11-8c6d-19eee27d232e.png)
![image](https://user-images.githubusercontent.com/107905192/209686928-3cc47623-6950-44b0-9aa4-22350e7b455a.png)
![image](https://user-images.githubusercontent.com/107905192/209686874-830155eb-4a86-44fe-bfee-c436953f1a2c.png)

Is anyone else facing this issue and can the different endpoint be the reason for my issue?
Any help would be appreciated. TIA

**Comment by smr0056** [comment]
I was able to solve this once I compared my python API call to the webull browser app API call. I cannot believe I wasted so much time and the issue was just a case-sensitive keyword.

Expected: enforce='DAY'
What I was doing: enforce='Day'

**Comment by tedchou12** [comment]
Thank you for the coffee! I am glad you are able to solve it!
