### ISSUE TITLE
How to help contribute to the wiki?

### ISSUE THREAD

**Issue by jasonrush** [tedchou12/webull#381]
Hello,

I'm starting to play around with your webull module and have found a bunch of stuff in the wiki that seems like it could use updating or clarifications. I'd like to contribute to updating the documentation, but I don't see any options to edit, suggest edits, and the "Clone this wiki locally" link w/i GitHub seems broken. Is there any way I can contribute to the wiki?

Thank you,
Jason Rush

**Comment by brycen-l** [comment]
I believe that you have to fork the entire branch, edit it on branch, and then send a push or pull request.

**Comment by tedchou12** [comment]
Thank you! Yes, I think you need collaborator permission to edit the wiki articles.
I have invited @jasonrush and @ICANTFINDAUSERNAMEATALL to the collaborators! Feel free to update where you find relevant.

**Comment by jasonrush** [comment]
@tedchou12 So... I didn't realize it was an invite I had to manually accept and it's expired. Could I get you to re-invite me when you get a free minute? I'll make sure to accept it as soon as I see it this time. Thanks!

**Comment by tedchou12** [comment]
@jasonrush 
Hi! I just invited again!

**Comment by jasonrush** [comment]
@tedchou12 Accepted, and much appreciated! I'll try to start updating a few things over the next week or so as I have free time here and there.

**Comment by tedchou12** [comment]
Thank you!!!
