### ISSUE TITLE
Issue to access Webull Roth IRA Account

### ISSUE THREAD

**Issue by emsensing** [tedchou12/webull#387]
I have two accounts (one regular, one roth IRA) associated with one login username and password.
With this API, I login with the username and password and try getting account information, it only shows the regular account, not showing roth IRA. 
Question: Is there a way to use API place order for roth IRA?

**Comment by 0ld0n3** [comment]
Hi! I'm running into a similar issue where I can't access my roth IRA. How did you solve this?

**Comment by emsensing** [comment]
> Hi! I'm running into a similar issue where I can't access my roth IRA. How did you solve this?

Very simply, after you log in, you just need to specify the account_id:

wb=webull()
wb.login('username','password')
wb._account_id='xxxx'

The account id can be found using the same method as you check the 'did'. 
This method works for my account. But it failed for my friend account. He recently opened roth IRA accounts and the API can't log in. Let me know how it goes.
