### ISSUE TITLE
place_order_option not working.   Exception: ('place_option_order failed', 500, '')

### ISSUE THREAD

**Issue by nawihu** [tedchou12/webull#389]
On a paper account, but have tried both.  My regular orders go thru fine, so I don't think its an auth problem.  Is my syntax correct? Any other ideas?  I have also explored using prices that are closer to the bid/ask, in case that was the error.  Any help is greatly appreciated.

![image](https://user-images.githubusercontent.com/109669915/228035488-a0952e52-dac9-479d-add0-26c9b0aa82af.png)

**Comment by DouGrimaldi** [comment]
I'm having the exact same problem right now, I want to paper trade options but this error is getting in the way. Could it be an Internal Server Error? If so, I'm not sure if this could be fixed.

**Comment by nawihu** [comment]
I did a little digging, and it seems paper options trading is somewhat new;  I think I saw Ted discussing it back in January;  this leads me to wonder if it just isn't supported with this API yet.  I need to deposit some money and see if I can get it to work with real money perhaps.

**Comment by DouGrimaldi** [comment]
i think your theory is correct, i just ordered options normally with the same code. Unfortunate.

**Comment by brycen-l** [comment]
> 

You can't paper trade options. This package pretty much connects to webull via the "web interface" and since you can't papertrade options on the web interface, papertrading options won't work.

**Comment by brycen-l** [comment]
> 

use the keyword "ticker" instead of "stock"
