### ISSUE TITLE
How to place an fractional shares trading order?

### ISSUE THREAD

**Issue by yphjtn** [tedchou12/webull#390]
I can successfully place market orders with integer quantities. 
I don't know how to place a market order with dollars (exp $10), then I place a fractional share (exp 0.5) order, but the Webull system response is 'The system is busy'. 

Could the API place a fractional shares trading order?

thanks
4/3/2023

**Comment by brycen-l** [comment]
Can you place fractional shares on webull web(the one you run from a browser)?

**Comment by yphjtn** [comment]
Yes, I can.
Later I solved it following tedchou12's way:
[tedchou12](https://github.com/tedchou12) commented [on Sep 12, 2022](https://github.com/tedchou12/webull/issues/333#issuecomment-1244426024)
https://github.com/tedchou12/webull/pull/338

**Comment by yphjtn** [comment]
Fractional Share Purchase by 'MKT' place_order #333
