### ISSUE TITLE
endpoints for historicals

### ISSUE THREAD

**Issue by hz2018tv** [tedchou12/webull#4]
hi, came across this repo. Looking really neat. any way to get historicals? Thanks

**Comment by tedchou12** [comment]
@hz2018tv 
Thank you for the feedback.
Actually, I think to support these data, it requries a server to be setup just for this purpose. If you are looking for past historical data. I recommend this:
https://financialmodelingprep.com/developer/docs/

**Comment by hz2018tv** [comment]
Thanks. I think it is a good idea to keep this API as simple and straightforward as possible and leave tasks like historicals to other modules.
