### ISSUE TITLE
Paper Options Trading

### ISSUE THREAD

**Issue by kiikoh** [tedchou12/webull#41]
I want to test my strategies on a paper account before trying it with real money. Ideally every function in the webull class should be identical to the paper class to have the easiest migration.

**Comment by kiikoh** [comment]
I have found why this is not currently implemented as webull does not support this yet... please ignore

**Comment by gamesover** [comment]
In webull, paper trading api is diff from real trading api. Not an ideal system design.

**Comment by ahsalem** [comment]
@kiikoh I'm using alpaca to test my strategies, I guess all what you would need to implement differently is your orders functions(buy,sell,modify,etc), https://alpaca.markets/docs/about-us/
