### ISSUE TITLE
is run_screener working?

### ISSUE THREAD

**Issue by ggang88** [tedchou12/webull#413]
For some reason, run_screener is not working from today. it returns somewhat below.
{'code': 'system.error', 'msg': 'Service Not Found', 'traceId': 'xxx'}

Anyone had any idea about this?

Thanks so much.

**Comment by tallestsun** [comment]
Hi @ggang88, I just tried using run_screener, and it is still returning 'Service Not Found'. Did you find a fix to this issue, or is the screener unusable now?
