### ISSUE TITLE
get_bars() no longer working?

### ISSUE THREAD

**Issue by alexh0101** [tedchou12/webull#415]
get_bars(), has always worked before, but now the response I get is this:

{'code': 'system.error', 'msg': 'Service Not Found', 'traceId': '09191e472......57b71f86'}

Did they change the endpoint?
Did anyone figure out the new one?

**Comment by alexh0101** [comment]
endpoint has changed to:

https://quotes-gw.webullfintech.com/api/quote/charts/query?tickerIds=

**Comment by M1NL1TE** [comment]
> endpoint has changed to:
> 
> 
> 
> https://quotes-gw.webullfintech.com/api/quote/charts/query?tickerIds=

What did you use to find the new endpoint ?

**Comment by alexh0101** [comment]
I used Chrome's Inspector. In "Network", "Headers", then you monitor the HTTP requests

**Comment by M1NL1TE** [comment]
> I used Chrome's Inspector. In "Network", "Headers", then you monitor the HTTP requests

Thank you. Do you know how to find all of the other endpoints? Like for paper trading options and orders? The web version doesn't have options for paper trading so there's nothing to see in the network tab. I've tried using wireshark with the desktop application but couldn't find the http requests to the server that way :(

**Comment by alexh0101** [comment]
I don't know if there is a way to know anything that is not in the browser version.
As for Wireshark, by the time the requests reach it, they are already encrypted, so I don't think you can get them with WS
