### ISSUE TITLE
Is it still working ??

### ISSUE THREAD

**Issue by mzaeemnasir** [tedchou12/webull#421]
Is it still working ??

**Comment by CoalMiner122113** [comment]
I dont think so. Neither login method 1 or 2 have worked for me because of the CAPTCHA.

**Comment by LukeWang01** [comment]
> Is it still working ??

It's working, but need to relogin to get the latest access_token weekly.

**Comment by AlanTkachuk** [comment]
@LukeWang01 Hey Luke, I'm glad this is working for you. Can you tell me the basic steps of what you're doing to get a successful connection to the API? It's been a while, but I remember logging into Webull, going to the Trade tab, and inspecting the v2 request in the Network tab to get the credentials, which I would then feed into my local credentials json file to use in the request. I remember this stopped working a few months back. When I try it now, I no longer see the "v2" request with the credentials in the network tab. I see one that just has general information, and another which has an empty response. Thanks

**Comment by LukeWang01** [comment]
@AlanTkachuk , Hi, it's still working. Try to search `access_token`  in the network tab

**Comment by AlanTkachuk** [comment]
@LukeWang01 Ah I found it, it's in the Headers tab now. Thanks!

**Comment by brycen-l** [comment]
https://github.com/tedchou12/webull/wiki/Workaround-for-Login-%E2%80%90-Method-2

You just need to verify it on your own browser, inspect and get the did(device id) of your browser, and then manually set that as the did in the webull object before you use the login. This way, webull will think that you are logging in from the verified browser. Look around in Method 1/2 if you need help getting the did. You can ignore everything else(I think).
