### ISSUE TITLE
Getting Account ID's for multiple accounts

### ISSUE THREAD

**Issue by 0ld0n3** [tedchou12/webull#437]
Hi! I'm a complete noob when it comes to coding, but wanted to ask a question about an issue that I am facing. I currently have 7 webull accounts (1 margin, 1 cash, 1 roth IRA, 1 trad IRA, 1 futures account [not funded], 1 rollover IRA [not funded], and a robo-Advisors account). I was playing around using the following code (after successfully logging in) and adding integers in the get_account_id( ) to get my different account id's for each account. 

 wb = webull()
    
wb._set_did(did)

wb.login(email, pw)
wb.get_trade_token(code)
   
id = wb.get_account_id(__)
print(id)
wb.logout()

0 gets me to my margin account, and 1 gets me to my cash account, but when I try 2, 3 and other integers, I get the following error: 

File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webull/webull.py", line 326, in get_account_id
    self._account_id = str(result['data'][int(id)]['secAccountId'])
                           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'secAccountId'


I can access the account IDs for my margin and cash (using integers 0 and 1), but cannot do so for my other accounts. Is there a way to fix this?


Thank you for your help in advance!

**Comment by emsensing** [comment]
I got the same issue. API can't access the ID for roth IRA. It can only access the individual account.  
How did you fix it?
