### ISSUE TITLE
get_account throws json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Calrider** [tedchou12/webull#44]
webull.get_account gets 404 response and raises the following error: 
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes

**Comment by Calrider** [comment]
webull.get_account requires webull.get_account_id to be called first so that self.account_id gets assigned. We should find a place to call get_account_id somewhere in the login process so that get_account_id doesn't have to be called manually

**Comment by gamesover** [comment]
Agree. Ideally, user does not need to know `account_id` to do anything. It could be a private variable in other language.

**Comment by Calrider** [comment]
Agreed
