### ISSUE TITLE
Any Advice on getting streaming to work in node/typescript

### ISSUE THREAD

**Issue by phillypro** [tedchou12/webull#443]
been banging my head on a wall trying to use traditional MQTT in node/typescript to recreate the streaming functionality in this python library

and every time its just a connection timeout....is paho-mqtt python doing something truly that unique?

**Comment by phillypro** [comment]
so ive tried two solutions....

one solution i compiled a C++ paho mqtt and have a wrapper and everything

im able to connect....i think...but i dont receive any confirmation message for connecting or subscribing just my own logs

same thing with using the "javascript client"

very very hard

**Comment by phillypro** [comment]
i got it down

**Comment by andrewoodleyjr** [comment]
> i got it down

Hey @phillypro can you share how you did it
