### ISSUE TITLE
get_bars method is not calling the right api ?

### ISSUE THREAD

**Issue by muralissa** [tedchou12/webull#46]
I am getting the below as result for the method. Is the api changed ?

{'msg': 'Failed to convert value of type \'java.lang.String\' to required type \'java.util.Set\'; nested exception is java.lang.NumberFormatException: For input string: "AAPL"', 'traceId': 'd104228cfba340d0b8c986fda5a4f263', 'code': '400'}

I found the below api but it has different structure

'https://quoteapi.webullbroker.com/api/quote/tickerRealTimes/v5?tickerIds=913256135%2C913256135%2C913255598%2C913243251%2C925299128'

**Comment by gamesover** [comment]
I tried
```python
api.get_bars('AAPL')
```
It seems good to me.

You may also look at `api.get_quote('AAPL')`?
