### ISSUE TITLE
login fails with {'success': False, 'msg': 'deviceId=null'}

### ISSUE THREAD

**Issue by xeicoco** [tedchou12/webull#47]
login would fail and returns:
{'success': False, 'msg': 'deviceId=null'}

it seems 2FA has been enforce by webull, and 2FA is not yet supported by the python login.

**Comment by tedchou12** [comment]
I just tested, indeed.
<img width="410" alt="Screen Shot 2020-05-27 at 21 21 10" src="https://user-images.githubusercontent.com/10494709/83018380-29fd6b80-a060-11ea-95b7-265f7dcb884b.png">
Need to see how we can handle Email MFA..

**Comment by tedchou12** [comment]
I see, it seems like MFA will only be needed for the first time if you login from a new device, if the device is trusted, then is not required again. So you need to obtain the device id of your computer the first time and use that id to login for your script.

**Comment by tedchou12** [comment]
@xeicoco 
Hi! I think 
https://github.com/tedchou12/webull/pull/48

should fix it, I have tested it myself. By default the mfa code should be received by Email.

**Comment by mzupan** [comment]
Not sure if this has anything to do with this but getting 404's when hitting

```
    def account(self, account_id):
        return f'{self.base_trade_url}/v3/home/{account_id}'

```

if i change v2 -> v3 I know get a 403

**Comment by mzupan** [comment]
To add to this.. looks like it's not grabbing my `account_id` which is why it's 403ing

**Comment by tedchou12** [comment]
@mzupan 
Hi Mike, I took a look at the endpoint, is okay for the account endpoint to stay at v2:
```
webull.login(webull_email, webull_pass, 'MacOS Chrome', '850001')
webull.get_trade_token(webull_token)
account = webull.get_account()
print(account)
```
```
def account(self, account_id):
        return f'{self.base_trade_url}/v2/home/{account_id}'
```
the old endpoint works fine.

**Comment by mzupan** [comment]
what about if MFA isn't setup? I don't have it setup and i get a 404 when logging in

**Comment by alexonab** [comment]
Where does the code '123456' come from?  Is it the system generated code that is sent via email or SMS?

**Comment by mzupan** [comment]
odd.. it seems mfa is enabled in my account which i can't turn off in the client

**Comment by alexonab** [comment]
It looks like the initial login check needs to be modified for a multi-step process.
1) identify mfa by checking login response for "extInfo" 
2) generate new temp code via sendCode request
3) new code from email or sms is read in by getpass.getpass prompt
4) 2nd login sent with mfa extInfo header and verificationCode

I see the PR request has get_mfa but it is not called.

**Comment by tedchou12** [comment]
@alexonab 
Sorry, it should be:
```
webull.get_mfa(webull_email) #this line will send you the mfa code
webull.login(webull_email, webull_pass, 'MacOS Chrome', '123456')
webull.get_trade_token(webull_token)
account = webull.get_account()
print(account)
```

**Comment by tedchou12** [comment]
> Where does the code '123456' come from? Is it the system generated code that is sent via email or SMS?
I think it will be determined by the accountType, if you are using Email, is email, if you are using phone number, you get the SMS.
> what about if MFA isn't setup? I don't have it setup and i get a 404 when logging in
I think it is setup by default, I have never recall setting it up, but is required as of today.

**Comment by spencerrojahn** [comment]
I'm not sure what is happening with the get_trade_token() function. I have been locked out of my account due to too many failed trading password verifications. The only parameter to the get_trade_token() function should be my Webull password correct?

**Comment by muralissa** [comment]
No, for get_trade_token, it will not be your webull password. It will be your passcode which will be digit upto 6 I guess. You should have used a trade PIN while signing in, that should be the password you should use for that method. I think, it is better to change the params to PIN rather calling it as password in get_trade_token. May be that is the reason for confusion.

**Comment by spencerrojahn** [comment]
Thank you. Yes, the parameters for the login and get_trade_token functions both contain a password parameter, that confused me. Thanks again though.

**Comment by lqin1** [comment]
I still facing the same error, with the latest version.
webull.get_mfa(webull_email) #this step does not work

**Comment by tedchou12** [comment]
@lqin1 
Thank you! 
What part didn't work? You did not get the Email about the PIN or it shows up some errors?
Could you check if you have the Email correctly setup on your account?

**Comment by lqin1** [comment]
I tried get_mfa with both phone number and email address, but didn't get any pin.
I checked that the response from get_mfa has status_code 500 for both cases

**Comment by tedchou12** [comment]
discussed here:
https://github.com/tedchou12/webull/issues/53
