### ISSUE TITLE
Determine whether stock is 'shortable' or not?

### ISSUE THREAD

**Issue by immanuelx2** [tedchou12/webull#5]
Thank you for sharing this. Is it possible to determine whether a stock is shortable or not (little blue icon)?

![image](https://user-images.githubusercontent.com/53500318/62177334-872a7280-b312-11e9-970f-e89da55f11fe.png)

**Comment by tedchou12** [comment]
Thanks for the suggestion. sorry for my delayed response. I am trying to look up stock that is non-shortable.
Do you have one that I could test and see the response?

Ted

**Comment by immanuelx2** [comment]
Yes. Thank you for looking into this.

Shortable: MSFT (tickerId: 913323997)
Non-shortable: TBLT (tickerId: 950106773)

**Comment by tedchou12** [comment]
Thanks for the information.

Does the `print(webull.get_quote('MSFT'))` `print(webull.get_quote('TBLT'))`
```
{'tickerId': 913256135, 'derivativeSupport': 1, 'tradeTime': '2019-08-02T23:57:23.431+0000', 'status': 'A', 'close': '204.02', 'change': '-4.41', 'changeRatio': '-0.0212', 'pPrice': '204.50', 'pChange': '0.48', 'pChRatio': '0.0024', 'marketValue': '922003103600.00', 'timeZone': 'America/New_York', 'tzName': 'EDT', 'preClose': '208.43', 'open': '205.53', 'high': '206.43', 'low': '201.63', 'vibrateRatio': '0.0230', 'avgVol10D': '39310603', 'avgVol3M': '27042575', 'volume': '40862122', 'turnoverRate': '0.0090', 'negMarketValue': '915250255821.00', 'pe': '16.71', 'forwardPe': '17.62', 'indicatedPe': '23.37', 'peTtm': '17.72', 'eps': '12.21', 'epsTtm': '11.51', 'pb': '9.58', 'totalShares': '4519180000', 'outstandingShares': '4486081050', 'fiftyTwoWkHigh': '233.47', 'fiftyTwoWkLow': '142.00', 'dividend': '3.080', 'yield': '0.0148', 'baSize': 0, 'ntvSize': 0, 'currencyCode': 'USD', 'lotSize': '1', 'limitUp': '0.0000', 'limitDown': '0.0000', 'latestDividendDate': '2019-08-09', 'latestSplitDate': '2014-06-09', 'latestEarningsDate': '2019-07-30', 'ps': '3.726', 'bps': '21.29'}
```
derivativeSupport match what you want? It seems like TBLT is missing this variable.

Ted

**Comment by immanuelx2** [comment]
Doesn't seem to be.

Check out EXP (tickerId: 913255278) -- looks to be shortable in Webull but it does not have that flag.

**Comment by tedchou12** [comment]
sorry for getting back late. Could you guide me how to see the shortable icon on the PC version? (Did you get the screenshot from the phone app?)

Thanks~

**Comment by immanuelx2** [comment]
No problem. It's available in both phone and desktop in the top right corner when viewing a commodity:

![image](https://user-images.githubusercontent.com/53500318/62546313-3e524c80-b831-11e9-9f5f-204efe81a229.png)

**Comment by tedchou12** [comment]
@immanuelx2 
Thanks for the info~
I will investigate it later today.

**Comment by tedchou12** [comment]
Sorry for the long wait. I added the `get_tradable()` endpoint.
MSFT
`'tradeType':'both_long_short',`
TBLT
`'tradeType':'no_long_short',`

Have a try and let me know.

Ted

**Comment by immanuelx2** [comment]
This is perfect... Thank you!
