### ISSUE TITLE
unable to login even with MFA

### ISSUE THREAD

**Issue by lqin1** [tedchou12/webull#53]
1. The default one is phone number, instead of email address. I tried wb.get_mfa('+65-XXXXXXXX') but msg saying number invalid.
2. after input verification code, got a page to input more info to verify
![wb2](https://user-images.githubusercontent.com/20535567/83866032-be02bd80-a759-11ea-8025-0be9ca647835.PNG)
![wb1](https://user-images.githubusercontent.com/20535567/83866035-bf33ea80-a759-11ea-81e7-691dfc2da9ad.PNG)

**Comment by tedchou12** [comment]
Thanks for the feedback!

**Comment by aaissleepy123** [comment]
how did you figure out the msg saying number invalid problem?
