### ISSUE TITLE
when call wb.get_mfa(), error indicates no this function

### ISSUE THREAD

**Issue by appleTree2017** [tedchou12/webull#54]
when call wb.get_mfa(), error indicates no this function

**Comment by tedchou12** [comment]
If you are using pip to install webull, the 0.0.8 version doesn't have the updated MFA yet.
Temporarily you will have to use the package from github.
@Calrider 
I took a look at pypi, but I am not sure how to update the package for the newest MFA update.
If you could give me a hand on that one..

Thanks!

**Comment by Calrider** [comment]
Hi Ted,

I updated the pip package to 0.0.9 with the master branch of tchou12/webull.
If you ever need to do it yourself, please read the following instructions
from PyPI (how to package PyPI modules
<https://packaging.python.org/tutorials/packaging-projects/>)

Christian

**Comment by tedchou12** [comment]
Thank you!! I will give it a try!
