### ISSUE TITLE
MFA Doesn't seem to work

### ISSUE THREAD

**Issue by prague2020** [tedchou12/webull#56]
I receive the following error when I try to obtain an MFA

from webull import webull, paper_webull

wb = webull()
wb.get_mfa('myemail@gmail.com')
wb.login('myemail@gmail.com', 'MyPass!, mfa') 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-3c6525dbfce0> in <module>
      5 
      6 wb = webull()
----> 7 wb.get_mfa('aug088705@gmail.com')

AttributeError: 'webull' object has no attribute 'get_mfa'

**Comment by tedchou12** [comment]
Hi There! 
The MFA was implemented a few weeks ago, have you updated your package?

**Comment by tedchou12** [comment]
May be the package was imported properly perhaps, do other functions work fine?

**Comment by prague2020** [comment]
Hi Techdou. Thank you for the response I really appreciate it. I did update the package...

This is what I see when I run the update

Requirement already satisfied: webull in c:\anaconda\lib\site-packages (0.0.8)
Requirement already satisfied: update in c:\anaconda\lib\site-packages (0.0.1)
Requirement already satisfied: certifi>=2020.4.5.1 in c:\anaconda\lib\site-packages (from webull) (2020.4.5.1)
Requirement already satisfied: pytz>=2020.1 in c:\anaconda\lib\site-packages (from webull) (2020.1)
Requirement already satisfied: chardet>=3.0.4 in c:\anaconda\lib\site-packages (from webull) (3.0.4)
Requirement already satisfied: six>=1.14.0 in c:\anaconda\lib\site-packages (from webull) (1.15.0)
Requirement already satisfied: numpy>=1.18.4 in c:\anaconda\lib\site-packages (from webull) (1.18.4)
Requirement already satisfied: pandas>=0.25.3 in c:\anaconda\lib\site-packages (from webull) (1.0.3)
Requirement already satisfied: urllib3>=1.25.9 in c:\anaconda\lib\site-packages (from webull) (1.25.9)
Requirement already satisfied: email-validator>=1.1.0 in c:\anaconda\lib\site-packages (from webull) (1.1.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\anaconda\lib\site-packages (from webull) (2.8.1)
Requirement already satisfied: idna>=2.9 in c:\anaconda\lib\site-packages (from webull) (2.9)
Requirement already satisfied: requests>=2.23.0 in c:\anaconda\lib\site-packages (from webull) (2.23.0)
Requirement already satisfied: style==1.1.0 in c:\anaconda\lib\site-packages (from update) (1.1.0)
Requirement already satisfied: dnspython>=1.15.0 in c:\anaconda\lib\site-packages (from email-validator>=1.1.0->webull) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

I still receive the error 
AttributeError: 'webull' object has no attribute 'get_mfa'

Any ideas?

**Comment by prague2020** [comment]
Should i maybe uninstall and reinstall?

**Comment by tedchou12** [comment]
@prague2020 
Sorry for the delay:
https://pypi.org/project/webull/#history

The latest version should be `0.0.9`. 

but 
```
Requirement already satisfied: webull in c:\anaconda\lib\site-packages (0.0.8)
```
Seems like is not updated. May be trying to uninstall and reinstall again?

**Comment by NathanHRich** [comment]
Reinstalling the python library will fix this
`pip uninstall webull && pip install webull`

**Comment by prague2020** [comment]
Good eye. Thank you that worked.
