### ISSUE TITLE
API for VWAP data ?

### ISSUE THREAD

**Issue by nkaliape** [tedchou12/webull#6]
Is there api for VWAP of a quote?

**Comment by tedchou12** [comment]
Sorry for the delay.
May be I will take some time to look into it.
But personally, I don't recommend using the API to grab a lot of data, since is not official, if there is large amounts of traffic, it may be disabled by Webull.

**Comment by gamesover** [comment]
@tedchou12 I agree. We can get a lot of public financial data from yahoo financial api.

https://stackoverflow.com/a/47505102/2251303

**Comment by saviornt** [comment]
I would highly recommend using either IEX or Alpha Vantage, both have python libraries. Yahoo Finance tends to be a little slow on the take.
