### ISSUE TITLE
KeyError: 'secAccountId'

### ISSUE THREAD

**Issue by JYDUSK** [tedchou12/webull#60]
I'm trying to get account details via .get_account_id():

from webull import webull

wb = webull()
pw = "MY PASSWORD"
un = 'MY USERNAME'
wb.login(un, pw,"Max's Python", '423251')
print(wb.get_account_id())
wb.logout()

I keep getting the following response:

Traceback (most recent call last):
  File "D:/Trading Bots/Webull Trading.py", line 7, in <module>
{'success': True, 'data': [{'brokerId': 8, 'brokerName': 'Individual', 'status': 'unopen', 'registerTradeUrl': '/mgt/redirect/tradeh5', 'openAccountUrl': 'https://tradeh5.webull.com/register/ib/continue.html', 'supportOutsideRth': True, 'userTradePermissionVOs': [{'type': 'stock', 'hasPermission': False, 'brokerId': 8}, {'type': 'crypto', 'hasPermission': False, 'brokerId': 8}], 'supportClickIPO': True, 'isDefaultChecked': False, 'supportOpenOption': True}]}
    print(wb.get_account_id())
  File "D:\Trading Bots\venv\lib\site-packages\webull\webull.py", line 188, in get_account_id
    id = str(result['data'][0]['secAccountId'])
KeyError: 'secAccountId'

I was trying to troubleshoot the code by putting a print statement into project. It keeps saying that my account status is unopen. However, when I request the mfa I can get it using the same password and username. I'm not sure what to do at this point.

Any advice is much appreciated. Fairly new to coding.

**Comment by pushap2020** [comment]
This works fine for me:
```
if first_login:
  self.wb.get_mfa(self.webull_email)
  # Check email for 6 digit access code. Enter it below
  access_code = '123456'
  wb.login(webull_email, webull_password,'windows', access_code)
else:
  # Get login token for session
  self.wb.refresh_login()
  wb.login(self.webull_email, self.webull_password)
  print(self.wb.get_account_id())
```
Hope this helps!

**Comment by JYDUSK** [comment]
> 
> 
> This works fine for me:
> 
> ```
> if first_login:
>   self.wb.get_mfa(webull_email)
>   # Check email for 6 digit access code. Enter it below
>   access_code = '123456'
>   wb.login(webull_email, webull_password,'windows', access_code)
> else:
>   # Get login token for session
>   wb.refresh_login()
>   wb.login(webull_email, webull_password)
>   print(wb.get_account_id())
> ```
> 
> Hope this helps!

Still having the same issue.

**Comment by NathanHRich** [comment]
I was having this same issue. It's an issue with the library. This is how I fixed it.
https://github.com/tedchou12/webull/issues/55#issuecomment-643690582
