### ISSUE TITLE
A way to pull all tickers available on WeBull and the correct TickerID/#

### ISSUE THREAD

**Issue by McKlayne** [tedchou12/webull#62]
It would be really nice to have a way to see all tickers that are on webull to then loop through other functions.

**Comment by alexonab** [comment]
The get_active_gainer_loser function defaults to 20 records but it can return all active tickers if you set the count high enough.

> len(wb.get_active_gainer_loser('active', 9999))
5124

**Comment by NathanHRich** [comment]
You could also use `wb.run_screener` with very broad filters.

**Comment by imvinaypatil** [comment]
Is there any api to query watchlists and belonging tickers?

**Comment by McKlayne** [comment]
@alexonab That is a great idea. However, I am getting the following error when I paste in the line of code you wrote. 

TypeError: get_active_gainer_loser() takes from 1 to 2 positional arguments but 3 were given

**Comment by tarek-vader** [comment]
> ?

is there a way to pull tickers from watchlist?

**Comment by imvinaypatil** [comment]
> > Is there any api to query watchlists and belonging tickers?
> 
> > 
> 
> 
> 
> 
> 
> is there a way to pull tickers from watchlist?

Yes. You can find it in recent commit

**Comment by prashanth742** [comment]
It asking to pass a 'regional_id' as a parameter. How can we get this?

**Comment by amitmahesh99** [comment]
I am a Year late . lol . I have just started to use webull and found it useful.
Here is url that can be used to pull list of all stocks

https://securitiesapi.webullfintech.com/api/securities/market/v5/card/stockActivityPc.advanced/list?regionId=12&userRegionId=1&hasNum=0&pageSize=9999

region id:1		"China"
region id:2		"Hong Kong"
region id:3		"Canada"
region id:4		"United Kingdom"
region id:5		"Japan"
region id:6		"United States"
region id:8		"Italy"
region id:12		"India"
region id:13		"Singapore"
region id:14		"Germany"
region id:50		"Denmark"
region id:59		"Finland"
region id:77		"Iceland"
region id:83		"Israel"
region id:105		"Malaysia"
region id:144		"Russia"
region id:166		"Sweden"
region id:169		"Taiwan"

**Comment by prashanth742** [comment]
Thanks you it's still helpful

**Comment by tedchou12** [comment]
#341
