### ISSUE TITLE
Indicators feed

### ISSUE THREAD

**Issue by qnguye** [tedchou12/webull#65]
Can we stream/get macd, rsi, ema data?

**Comment by alexonab** [comment]
The indicators are calculated clientside either in the app/web interface via charting libraries.  You can do the same with the get_bars function which returns an ohlc pandas dataframe.  This can be used with indicator libraries like finta, pandas-ta, talib, etc.

Charting can be implemented with matplotlib.

**Comment by qnguye** [comment]
Awesome pandas-ta. Thank you much!
