### ISSUE TITLE
get_ticker('DSS') returning error -->'msg': 'Could not find a healthy node to handle the request.', 'traceId': 'b0f00b095e154f37963c8e690996b9b9', 'code': '500'}

### ISSUE THREAD

**Issue by xeicoco** [tedchou12/webull#68]
get_ticker('DSS') returning error -->'msg': 'Could not find a healthy node to handle the request.', 'traceId': 'b0f00b095e154f37963c8e690996b9b9', 'code': '500'}

did the API endpoint changed?

**Comment by xeicoco** [comment]
another example:

webull.get_ticker on MSFT:

'https://infoapi.webull.com/api/search/tickers5?keys=MSFT&queryNumber=1'

returns:
'{"msg":"Could not find a healthy node to handle the request.","traceId":"99e1e4b4951d4698b0f577d4f9636bb6","code":"500"}'

**Comment by timwelch** [comment]
This is Webull's fault, not the code. They need to fix their servers. lol :-)

**Comment by alexonab** [comment]
The request params and response has changed.  

> $ curl -k 'https://quotes-gw.webullbroker.com/api/search/pc/tickers?keyword=TSLA&pageIndex=1&pageSize=20'
{"data":[{"tickerId":913255598,"exchangeId":96,"type":2,"secType":[61],"regionId":6,"regionCode":"US","currencyId":247,"name":"TESLA","symbol":"TSLA","disSymbol":"TSLA","disExchangeCode":"NASDAQ","exchangeCode":"NSQ","listStatus":1,"template":"stock","derivativeSupport":1,"tinyName":"TESLA"},{"tickerId":913258506,"exchangeId":56,"type":3,"secType":[1,12],"regionId":6,"regionCode":"US","currencyId":247,"name":"Transamerica Small Cap Value A","symbol":"TSLAX","disSymbol":"TSLAX","disExchangeCode":"MUTF_US","exchangeCode":"MUTF","listStatus":1,"template":"mutf","exchangeTrade":false,"tinyName":"Transamerica Small Cap Value A"},{"tickerId":913268983,"exchangeId":56,"type":3,"secType":[1,12],"regionId":6,"regionCode":"US","currencyId":247,"name":"Transamerica Small Cap Value A LW","symbol":"TSLAX.lw","disSymbol":"TSLAX.lw","disExchangeCode":"MUTF_US","exchangeCode":"MUTF","listStatus":3,"template":"mutf","exchangeTrade":false,"tinyName":"Transamerica Small Cap Value A LW"}],"hasMore":false}

There are likely other changes as well... it looks like the get_bars response has changed also.

**Comment by jhuang364** [comment]
Seems to be the case for all tickers

**Comment by alexonab** [comment]
@tedchou12  I have added fixes for this in PR #63

**Comment by tradinginaction** [comment]
tested fix working

**Comment by xeicoco** [comment]
verified fix working on my setup thanks again @alexonab 
btw, how where you able to quickly identify the changes in the webull endpoints/api ? wanted to learn so that next time I can also contribute

**Comment by alexonab** [comment]
@xeicoco I used developer tools (F12) in chrome and the network profiler tab to see the requests sent from the browser to webull.

**Comment by xeicoco** [comment]
thanks @alexonab
