### ISSUE TITLE
'hasMore' error when using get_quote()

### ISSUE THREAD

**Issue by spencerrojahn** [tedchou12/webull#69]
The KeyError 'hasMore' is printed out everytime I try to get quote information from a stock. It had worked perfectly fine for 2 months up until now. I'm not sure what that error means so I have no idea what the problem is. Is there a reason why get_quote() is doing this?

**Comment by qnguye** [comment]
i'm having this same error with get_bars() too!! It was working 2 days ago and now every request stuck with this. Please help. Thanks

**Comment by cryptobull69** [comment]
Duplicate of #68 

It looks like a fix might be already merged to master branch now.
