### ISSUE TITLE
Option Support

### ISSUE THREAD

**Issue by alexonab** [tedchou12/webull#7]
With options trading being added on Webull it would be nice to see this supported.

**Comment by tedchou12** [comment]
sorry for the delayed reply!
Yes! I'd love to add that into the feature.

**Comment by tedchou12** [comment]
Thanks Mike for the commits.
I added `place_option_order()`
It seems that you have a few endpoints trying to fetch the option chains.
I don't have the positions myself to check if the option place order can work successfully or not.

If you have some time and your account allows you to give you a try, please do let me know.

Thanks!

**Comment by mrazum** [comment]
Webull doesn't support Options trading yet.

**Comment by hz2018tv** [comment]
I tried. got " {'msg': 'Inner server error', 'traceId': '06b358b7c9dc4be59e3a801c843e1548', 'code': 'trade.token.expire', 'data': {}, 'success': False}". can manually place option trade order from the web interface and can list the order from API.

**Comment by hz2018tv** [comment]
it works after post to https://tradeapi.webulltrade.com/api/trade/v2/option/placeOrder .
