### ISSUE TITLE
get_trade_token always return false

### ISSUE THREAD

**Issue by qnguye** [tedchou12/webull#72]
Did it break or just me? I'm sure that i used correct pin/pass

**Comment by RockStone** [comment]
I'm having the same issue. did you get it resolved? what's the solution?

**Comment by qnguye** [comment]
the pin should be a string, not numeric.

**Comment by RockStone** [comment]
I figured it's supposed to be the "trade pin" rather than the login password. the API named it "password" which was a bit misleading. Thanks anyways.
