### ISSUE TITLE
404 error on place order

### ISSUE THREAD

**Issue by qnguye** [tedchou12/webull#73]
Please help me. Thanks
>>> wb.place_order('SBUX', 913257472, 70, 'BUY', 'LMT', 'GTC', 1)
{'timestamp': '2020-07-14T18:02:17.598+0000', 'status': 404, 'error': 'Not Found', 'message': 'No message available', 'path': '/webull-paper-center/api/paper/1/acc//orderop/place/913257472'}

**Comment by qnguye** [comment]
I believe i found the issue. Please fix the URL

https://act.webullbroker.com/webull-paper-center/api/paper/1/acc/**[missing_account_id_here]**/orderop/place/913257472

**Comment by geoffrey7682** [comment]
Hey can you please tell me how you resolved the issue? I am struggling to see how to include the account id when importing my credentials. Thanks in advance.

**Comment by qnguye** [comment]
you should run wb.login_prompt()
after login successfully, you should have it. You can check it by run wb._account_id

**Comment by geoffrey7682** [comment]
Thank you, it is working now.
