### ISSUE TITLE
get_dividends() only returns one dividend payment, not history.

### ISSUE THREAD

**Issue by lianavalentino** [tedchou12/webull#74]
I assume it is supposed to return total dividend history? Unless I am misunderstanding the functionality. Is there a way to get the total history?

<img width="487" alt="Screen Shot 2020-07-15 at 9 51 15 AM" src="https://user-images.githubusercontent.com/17402174/87572736-d7642700-c680-11ea-9ba9-1d115c23fa35.png">

**Comment by knurts** [comment]
There is a separate endpoint for historical dividends paid. This endpoint is for dividends about to be paid in the future(8/3/2020 in this case). 

That's not really an issue with this function, just an unimplemented feature of this project.

I suppose documentation might need improved :)

**Comment by tedchou12** [comment]
The activities endpoint will allow you to view all activities history including past dividends.

```
'filterConditions':[
{
'groupKey':'date',
'groupName':'Time',
'items':[
{
'name':'All',
'value':'all'
},
{
'name':'Last 1 Month',
'value':'1M'
},
{
'name':'Last 3 Months',
'value':'3M'
}
],
'multiple':False
},
{
'groupKey':'category',
'groupName':'Type',
'items':[
{
'name':'All',
'value':'all'
},
{
'name':'Trade',
'value':'trade'
},
{
'name':'Cash Transfer',
'value':'cashTransfer'
},
{
'name':'Stock Transfer',
'value':'stockTransfer'
},
{
'name':'Dividends',
'value':'dividend'
},
{
'name':'Interests',
'value':'interest'
},
{
'name':'Corporate Actions',
'value':'corporateAction'
},
{
'name':'Fees',
'value':'fee'
},
{
'name':'Other',
'value':'other'
}
],
'multiple':True
}
```
