### ISSUE TITLE
Order's Don't Complete

### ISSUE THREAD

**Issue by prague2020** [tedchou12/webull#76]
Hi Tedchou12,

When the API places orders python shows success but they end up "failing" and showing up in Webull's fail bin.

Here is the code

import sys
stock=sys.argv[1]
print(stock)
qty=sys.argv[2]
from webull import webull
wb = webull()
result = wb.login('xxxxxx@gmail.com', 'xxxxxx','019895', '019895')
wb.get_trade_token('327327')
print(result)
x = wb.get_quote(stock)
if 'pPrice' not in x:
tempPrice = x["close"]
else:
tempPrice = x["pPrice"]
price = float(tempPrice) * 1.01
amt = int(int(qty)/price)
orderres = wb.place_order(tempPrice, x["tickerId"], price, action='BUY', orderType='LMT', enforce='GTC', qty=amt, outsideRegularTradingHour=True)
print(orderres)

This is the return objects

{'tickerId': 913256871, 'derivativeSupport': 1, 'tradeTime': '2020-07-21T21:03:22.273+0000', 'status': 'D', 'close': '16.93', 'change': '0.44', 'changeRatio': '0.0267', 'marketValue': '1205862088.57', 'volume': '1132890', 'turnoverRate': '0.0159', 'timeZone': 'America/New_York', 'tzName': 'EDT', 'preClose': '16.49', 'open': '16.55', 'high': '17.06', 'low': '16.41', 'vibrateRatio': '0.0394', 'avgVol10D': '1332626', 'avgVol3M': '1657557', 'negMarketValue': '1185000400.81', 'pe': '63.20', 'forwardPe': '-77.8391', 'indicatedPe': '-35.7701', 'peTtm': '83.77', 'eps': '0.2679', 'epsTtm': '0.2021', 'pb': '3.619', 'totalShares': '71226349', 'outstandingShares': '69994117', 'fiftyTwoWkHigh': '18.27', 'fiftyTwoWkLow': '5.23', 'yield': '0.0000', 'baSize': 0, 'ntvSize': 0, 'currencyCode': 'USD', 'lotSize': '1', 'limitUp': '0.0000', 'limitDown': '0.0000', 'latestDividendDate': '1998-01-08', 'latestEarningsDate': '2020-05-06', 'ps': '6.74', 'bps': '4.678', 'estimateEarningsDate': '08/04-08/10'}
{'success': True, 'data': {'orderId': 61969098}}

The order seems to be filled out correctly and shows success but doesn't actually purchase. This is after gathering the MFA and correctly logging on previously. There don't seem to be any login issues.

Any ideas?

Thank you.

**Comment by alexonab** [comment]
It looks like you are providing the price twice and in the wrong order.  The parameters for the place_order function are below.

> place_order(stock=None, tId=None, price=0, action='BUY', orderType='LMT', enforce='GTC', qty=0, outsideRegularTradingHour=True)

Try with these options.
> wb.place_order(tId=x["tickerId"], price=price, action='BUY', orderType='LMT', enforce='GTC', qty=amt, outsideRegularTradingHour=True)

**Comment by prague2020** [comment]
Thank you. I am sorry for missing something so evident. Thank you so much for your time and assistance. I really appreciate it,
