### ISSUE TITLE
Ticker ID Lookup Innaccurate

### ISSUE THREAD

**Issue by prague2020** [tedchou12/webull#77]
I know this may be out of your control but when a stock symbol is used to lookup tickerID it's only about 50% accurate which is actually a big problem. TickerID is needed to place an order and so failure to find the correct stock results in a lot of failed orders. For example RDHL and TSCO

raise ValueError("Could not find ticker for stock {}".format(stock))
ValueError: Could not find ticker for stock TSCO

Same goes for get_quote

**Comment by alexonab** [comment]
The tickerID lookup is working for those symbols.
> from webull import webull
wb = webull()
wb.get_ticker('RDHL')
913303936
wb.get_ticker('TSCO')
913323531

Try and update to make sure you are using the working version.

> python -m pip install git+https://github.com/tedchou12/webull.git -U

**Comment by imvinaypatil** [comment]
yes, I too feel that new version of ticker_id lookup is inaccurate in fact I don't get most of my tickers for IN region anymore. Whereas the previous version `/search/tickers5` works fine with little modification (discarding the hasMore==false check)

**Comment by alexonab** [comment]
The current lookup does not include a region and defaults to US.  I believe most of the region ID values are hardcoded to 6 for US.  This could be dynamically provided by pulling the region ID from the below endpoint.

> curl -k https://securitiesapi.webullbroker.com/api/securities/regions/getRegionId/v2
6

If you want to get non-US ID's you could update the code [here](https://github.com/tedchou12/webull/blob/b61cc70dafcb8bcc59a2e386e785f2b9958f4416/webull/endpoints.py#L128) to include a region parameter.  The webull lookup comes from the URL below.

> https://quotes-gw.webullbroker.com/api/search/pc/tickers?keyword=TSCO&regionId=6&pageIndex=1&pageSize=1

The above defaults to one result but you could return more if you increase the pagesize (assuming there is more than one match).  If you do want more than one result you need to filter the status (listStatus: 1) as some lookups will return inactive tickers.

**Comment by imvinaypatil** [comment]
Thanks @alexonab I will sure have a look at it.
