### ISSUE TITLE
can't place option order

### ISSUE THREAD

**Issue by qnguye** [tedchou12/webull#78]
Seem like it doesn't work. Can someone help me please?

>>> wb.place_option_order(optionId=1015778901, lmtPrice=1, action='SELL', orderType='LMT', enforce='DAY', quant=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\webull\webull.py", line 530, in place_option_order
    raise Exception('place_option_order failed', response.status_code, response.reason)
Exception: ('place_option_order failed', 500, '')

**Comment by qnguye** [comment]
very weird but i found the solution. Webull wants request params to exact order like this

{"lmtPrice":"1","auxPrice":null,"orderType":"LMT","timeInForce":"DAY","orders":[{"quantity":2,"action":"SELL","tickerId":1015778901,"tickerType":"OPTION"}],"serialId":"57a14473-6a9c-4fdf-8d05-b5ea09f603ca"}

**Comment by alexonab** [comment]
It's working here without changing the order of parameters.  Just make sure you pass in strings.

>wb.place_option_order(optionId='1015778901', lmtPrice='0.01', action='BUY', orderType='LMT', enforce='DAY', quant='1')
True
