### ISSUE TITLE
get_trade_token() always returns false

### ISSUE THREAD

**Issue by yashwa7** [tedchou12/webull#79]
Login with username and password credentials. Try using the 6 digit password you normally use before trades in wb.get_trade_token('6 digit password'). It always returns False no matter what. Even changed the trading password to a new one.

**Comment by RockStone** [comment]
same here. anyone?

**Comment by RockStone** [comment]
It worked for me after resetting a new trade pin. put it in a string though.

**Comment by hemangjoshi37a** [comment]
From where can we get the 6 digit PIN. I am new here.

**Comment by tedchou12** [comment]
@hemangjoshi37a 
on your webull app, 
settings > Account & Security > Trading Password > Change Trading Password.
