### ISSUE TITLE
How to make additions to project?

### ISSUE THREAD

**Issue by mrazum** [tedchou12/webull#8]
Hello.
I'm new on GitHub, how can I show you what I would like to add to your project?
I want to add shell.py by analogy with Robinhood samples and make some changes in your webull.py.
[config.py.txt](https://github.com/tedchou12/webull/files/4057432/config.py.txt)
[shell.py.txt](https://github.com/tedchou12/webull/files/4057433/shell.py.txt)

Best regards,
Mikhail.

**Comment by tedchou12** [comment]
Hi Mikhai~
Thank you for the suggestions! I will look into it too~
Actually, I only have experiences managing my own projects on GitHub, this is the first time I opened a public project with members in the community.
I am so glad that there are a lot of people interested in algo-trading too!

Ted

**Comment by mrazum** [comment]
May I get your email? Mine is doc2tif @ gmail

Thank you,
M.

**Comment by Calrider** [comment]
Hi Mikhail,
You can contribute to the project by first forking this repo. Once you git clone your fork to your local machine, you can make the changes you want and then commit back to your online repo. Finally, create a pull request on github so ted can review.

Christian
