### ISSUE TITLE
Receing error  raise JSONDecodeError("Expecting value", s, err.value) from None

### ISSUE THREAD

**Issue by rbalajiit1** [tedchou12/webull#80]
i have the following script and receiving error. Please help

import datetime, time
import openpyxl as xl
from webull import webull

wb = webull()
wb.login('xxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxx')
wb.get_trade_token('123456')
wb.place_order(stock='AAPL', price=90.0, qty=2)

Error is as follows

Traceback (most recent call last):
  File "supporting\webull_module.py", line 8, in <module>
    wb.place_order(stock='AAPL', price=90.0, qty=2)
  File "C:\ProgramData\Miniconda3\lib\site-packages\webull\webull.py", line 312, in place_order
    return response.json()
  File "C:\ProgramData\Miniconda3\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\ProgramData\Miniconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tedchou12** [comment]
@rbalajiit1 
Sorry for the delayed response.

Is a bit difficult to debug from the information.

Are you sure that you have logged in correctly? You can do so by checking : get_account(), to see you are seeing actual information related to your webull account.

**Comment by margarita26** [comment]
same here, what might be the reason someone wouldn't be able to login?
tried debugging login() function, getting 500 response from server, I'm using the phone # for login and it's in the format mentioned in readme

**Comment by tedchou12** [comment]
@margarita26 
sure! 
Did you do the get_mfa?
https://github.com/tedchou12/webull/wiki/MFA

**Comment by margarita26** [comment]
yeah i tried doing wb.get_mfa("+1-XXXXXXXXX") but get nothing

**Comment by margarita26** [comment]
omg nevermind, fixed it thanks
