### ISSUE TITLE
Cannot login to Webull

### ISSUE THREAD

**Issue by rbalajiit1** [tedchou12/webull#81]
i have the follwoing code and canot login to webull.

import datetime, time
import openpyxl as xl
from webull import webull

excel_input_path = 'MarketWatchInputs.xlsx'

wb = xl.load_workbook(filename = excel_input_path)
sheet_ranges = wb['WebullSetting']

i_username = str(sheet_ranges['B1'].value)
i_password = str(sheet_ranges['B2'].value)
i_token = str(sheet_ranges['B3'].value)
wb = webull()
print(wb.login(i_username, i_password))

Error is as follows
base) G:\WebullOrder>python supporting\webull_2.py
{'msg': 'deviceId=null', 'traceId': 'a522291dce38400fa1fb533aabefcf3e', 'code': '500'}

My version is as follows
webull                 0.0.8

**Comment by Abdallah-Aleies** [comment]
Same issue here
