### ISSUE TITLE
Any way to get float for specific stock?

### ISSUE THREAD

**Issue by Abdallah-Aleies** [tedchou12/webull#85]
I was looking through the code and I haven't found a way to get float of a specific stock. Has anyone figured a way how to do so?

**Comment by tedchou12** [comment]
@Abdallah-Aleies 
By float, do you mean the price?

**Comment by Abdallah-Aleies** [comment]
@tedchou12 it's the shares that company has issued to the public that are available for investors to trade. Shares can include restricted or authorized shares, but those are not part of float due to investors not able to buy/sell them.

**Comment by tedchou12** [comment]
I took a look on the app. There is no number of shares available for trade in the webull app. Since most of these endpoints are information from the webull app endpoints, if those are not available, is not possible to get them (unless there are some hidden endpoints).

**Comment by Abdallah-Aleies** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/50155287/90702652-c13a1f80-e259-11ea-9e6e-ce894af66952.png">

If you look at the photo above, it is under free float.

**Comment by tedchou12** [comment]
Just very quickley here it is:
https://quotes-gw.webullbroker.com/api/quotes/ticker/getTickerRealTime?tickerId=913256135
```
{"tickerId":913256135,"exchangeId":96,"type":2,"secType":[61],"regionId":6,"regionCode":"US","currencyId":247,"name":"Apple","symbol":"AAPL","disSymbol":"AAPL","disExchangeCode":"NASDAQ","exchangeCode":"NSQ","listStatus":1,"template":"stock","derivativeSupport":1,"tradeTime":"2020-08-20T17:04:38.906+0000","status":"T","close":"468.87","change":"6.04","changeRatio":"0.0130","marketValue":"2032217979775.00","volume":"17696470","turnoverRate":"0.0041","timeZone":"America/New_York","tzName":"EDT","preClose":"462.83","open":"463.00","high":"470.50","low":"462.93","vibrateRatio":"0.0163","avgVol10D":"40873663","avgVol3M":"36547200","negMarketValue":"2030824333888.57","pe":"39.45","forwardPe":"36.07","indicatedPe":"45.36","peTtm":"35.64","eps":"11.89","epsTtm":"13.16","pb":"27.79","totalShares":"4334335000","outstandingShares":"4331362618","fiftyTwoWkHigh":"470.50","fiftyTwoWkLow":"201.00","dividend":"3.280","yield":"0.0070","baSize":0,"ntvSize":0,"currencyCode":"USD","lotSize":"1","latestDividendDate":"2020-08-31","latestSplitDate":"2020-08-31","latestEarningsDate":"2020-04-30","ps":"7.59","bps":"16.87","estimateEarningsDate":"10/28-11/02"}
```
"marketValue":"2032217979775.00"
APPL just passed the 2T market cap yesterday.

Ted

**Comment by Abdallah-Aleies** [comment]
@tedchou12 Market value is different. If you look at the picture above. It has two values, Free Float (one I'm looking for) and Market cap, the one you have just linked.

**Comment by alexonab** [comment]
> <img alt="image" width="338" src="https://user-images.githubusercontent.com/50155287/90702652-c13a1f80-e259-11ea-9e6e-ce894af66952.png">
> 
> @tedchou12 If you look at the photo above, it is under free float. That's from the key statistics section in the Webull desktop app.

It looks like you can get that via the quote endpoint.  Its called outstandingShares.

> wb.get_quote('AAPL')['outstandingShares']
'4331362618'

**Comment by Abdallah-Aleies** [comment]
@alexonab Solved, Thank you!!

**Comment by Abdallah-Aleies** [comment]
@tedchou12 I would create another issue but I don't want to spam this repo with them. But is there a way to see current bid/asks?

**Comment by tedchou12** [comment]
@alexonab Thanks~!

**Comment by tedchou12** [comment]
If there is info in the app, I think it won't be hard.
You want the realtime bid/ask prices? If you are planning to pull those on short intervals, I would recommend something like alphavantage or iexcloud. Since these endpoints are not officially supported, if your account has a lot of unusual activity, theoretically, they could just block your account.
That said, if you want, I can take a look.

**Comment by Abdallah-Aleies** [comment]
@tedchou12 I wouldn't pull those intervals very often, only when placing an order. So maybe once every 45 mins to an hour. Don't think that should be an issue. If you can take a look or guide me to an endpoint that'd be much appreciated!

**Comment by tedchou12** [comment]
@Abdallah-Aleies 
this might solve the issue for you? #97
