### ISSUE TITLE
order history

### ISSUE THREAD

**Issue by hz2018tv** [tedchou12/webull#9]
could you add function to retrieve historical orders, including those filled or canceled, and including those closed positions? thanks

**Comment by knurts** [comment]
You can add in an &endTime= if you want to specify your own range    
def get_working_orders(self):
        """ Get open orders """
        headers = self.headers
        headers['did'] = self.did
        headers['access_token'] = self.access_token
        headers['t_token'] = self.trade_token
        headers['t_time'] = str(round(time.time() * 1000))
        response = requests.get(
            'https://tradeapi.webulltrade.com/api/trade/v2/option/list?secAccountId=' + self.account_id +
            '&startTime=' + str(1970-0-1) + '&dateType=ORDER&status=Working',
            headers=headers)
        return response.json()

    def get_order_cancel_history(self):
        """ Cancelled orders """
        headers = self.headers
        headers['did'] = self.did
        headers['access_token'] = self.access_token
        headers['t_token'] = self.trade_token
        headers['t_time'] = str(round(time.time() * 1000))
        response = requests.get(
            'https://tradeapi.webulltrade.com/api/trade/v2/option/list?secAccountId=' + self.account_id +
            '&startTime=' + str(1970-0-1) + '&dateType=ORDER&status=Cancelled',
            headers=headers)
        return response.json()

    def get_order_filled_history(self):
        """ Filled orders """
        headers = self.headers
        headers['did'] = self.did
        headers['access_token'] = self.access_token
        headers['t_token'] = self.trade_token
        headers['t_time'] = str(round(time.time() * 1000))
        response = requests.get(
            'https://tradeapi.webulltrade.com/api/trade/v2/option/list?secAccountId=' + self.account_id +
            '&startTime=' + str(1970-0-1) + '&dateType=ORDER&status=Filled',
            headers=headers)
        return response.json()

in main: print(webull.get_working_orders()) to see list of dictionaries returned

**Comment by knurts** [comment]
weird, not sure why that only formatted 2 out of the 3 functions...
P.S. - thanks @tedchou12 , this repo has been helpful and educational.

**Comment by hz2018tv** [comment]
Thanks! What about paper account retrievals? The above works with regular account.

**Comment by hz2018tv** [comment]
Thanks

**Comment by tedchou12** [comment]
@hz2018tv 
Thank you for the suggestion and question!
@knurts 
Thank you so much for the add!

**Comment by hz2018tv** [comment]
BTW, what is the status for partially filled orders? I personally have not had such orders, but I think they exist.

**Comment by tedchou12** [comment]
this one:
`print(webull.get_history_orders('Partially Filled'))`
