### ISSUE TITLE
Does any know how to use buy in market price?

### ISSUE THREAD

**Issue by llc1990** [tedchou12/webull#94]
I can see it from [here](https://github.com/tedchou12/webull/blob/776205264213bb2656d98d937548c2bd2447f3f4/webull/webull.py#L279) that there is `MKT` option for trade type. However, I was not able to place an order in market price. The way as follows didn't work

```
wb = webull()
wb.login('xxxx@gmail.com', 'MyPass')
wb.get_trade_token('123456')
wb.place_order(stock='AAPL', action='BUY', orderType='MKT', qty=1, outsideRegularTradingHour=False)
```

**Comment by llc1990** [comment]
all right, I figured it out myself:


```
wb = webull()
wb.login('xxxx@gmail.com', 'MyPass')
wb.get_trade_token('123456')
wb.place_order(stock='AAPL', action='BUY', orderType='MKT', enforce='DAY', qty=1, outsideRegularTradingHour=False)

```

this works for me

**Comment by RockStone** [comment]
does the hard-coded '123456' work for you?

**Comment by RockStone** [comment]
nvm. I figured it's the trade pin. thought it was the password, as the api named.
