### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by jsapar** [tedchou12/webull#96]
Sorry if this is an easy fix that I'm missing. 

I'm getting this error when trying to run

_pip install webull_

DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement webull (from versions: none)
ERROR: No matching distribution found for webull

Thanks for any help!

**Comment by hfacey** [comment]
try updating your python version. min requirements for the package is 3.6

**Comment by jsapar** [comment]
Thank you that worked. Seemed I had multiple versions of python and it was running 3.5.
