### ISSUE TITLE
Is there a way to get the bid and ask price or the ratio ?

### ISSUE THREAD

**Issue by xterminal01** [tedchou12/webull#97]
Not sure if this is already implemented, but I am looking for the "Ask" and "Bid" or Ratio of a particular stock. Thanks.

![bidAsk](https://user-images.githubusercontent.com/42123644/97708328-ff8c6000-1a8e-11eb-9ec2-3165bc333740.png)

**Comment by tedchou12** [comment]
@xterminal01 
Thanks for the question!
`3.35` seems like to be the bid-ask spread of the stock:
`1687.96-1684.61`.

I guess you just have to get the lowest ask price and the highest bid price and subtract them.
(use the `quotes` endpoint, to get 1687.96 and 1684.61.)

**Comment by xterminal01** [comment]
> 
> 
> @xterminal01
> Thanks for the question!
> `3.35` seems like to be the bid-ask spread of the stock:
> `1687.96-1684.61`.
> 
> I guess you just have to get the lowest ask price and the highest bid price and subtract them.
> (use the `quotes` endpoint, to get 1687.96 and 1684.61.)

Thanks for the answer,

Not sure where the "Quotes" endpoint is?
I checked the get_quote('GOOGL') function and don't see the ask/bid price?

**Comment by tedchou12** [comment]
@xterminal01 
Sorry, I think I might need to update the pip package again.

In the meanwhile, if you download directly from Github, you can get it to work too I think:
```{'tickerId': 913303964, 'exchangeId': 96, 'type': 2, 'secType': [61], 'regionId': 6, 'regionCode': 'US', 'currencyId': 247, 'name': 'Alphabet', 'symbol': 'GOOG', 'disSymbol': 'GOOG', 'disExchangeCode': 'NASDAQ', 'exchangeCode': 'NSQ', 'listStatus': 1, 'template': 'stock', 'derivativeSupport': 1, 'tradeTime': '2020-11-03T00:58:13.852+0000', 'status': 'A', 'close': '1626.03', 'change': '5.02', 'changeRatio': '0.0031', 'pPrice': '1633.70', 'pChange': '7.67', 'pChRatio': '0.0047', 'marketValue': '1105966475419.05', 'volume': '2535446', 'turnoverRate': '0.0037', 'timeZone': 'America/New_York', 'tzName': 'EST', 'preClose': '1621.01', 'open': '1628.16', 'high': '1660.77', 'low': '1616.03', 'vibrateRatio': '0.0275', 'avgVol10D': '2283293', 'avgVol3M': '1833772', 'negMarketValue': '995399354142.90', 'pe': '33.07', 'forwardPe': '36.76', 'indicatedPe': '42.84', 'peTtm': '36.77', 'eps': '49.16', 'epsTtm': '44.22', 'pb': '5.34', 'totalShares': '680163635', 'outstandingShares': '612165430', 'fiftyTwoWkHigh': '1733.18', 'fiftyTwoWkLow': '1013.54', 'yield': '0.0000', 'baSize': 0, 'ntvSize': 30, 'depth': {'ntvAggAskList': [{'price': '1647.47', 'volume': '10'}, {'price': '1650.00', 'volume': '10'}, {'price': '1651.56', 'volume': '10'}, {'price': '1652.00', 'volume': '6'}, {'price': '1654.00', 'volume': '2'}, {'price': '1654.71', 'volume': '10'}, {'price': '1654.87', 'volume': '10'}, {'price': '1654.98', 'volume': '5'}, {'price': '1655.00', 'volume': '21'}, {'price': '1656.94', 'volume': '10'}, {'price': '1659.99', 'volume': '14'}, {'price': '1660.00', 'volume': '13'}, {'price': '1663.91', 'volume': '10'}, {'price': '1665.00', 'volume': '17'}, {'price': '1666.00', 'volume': '510'}, {'price': '1667.00', 'volume': '1'}, {'price': '1668.00', 'volume': '4'}, {'price': '1668.57', 'volume': '1'}, {'price': '1670.00', 'volume': '28'}, {'price': '1672.65', 'volume': '1'}, {'price': '1674.00', 'volume': '32'}, {'price': '1674.44', 'volume': '20'}, {'price': '1675.00', 'volume': '11'}, {'price': '1677.00', 'volume': '5'}, {'price': '1679.00', 'volume': '2'}, {'price': '1679.66', 'volume': '1'}, {'price': '1680.00', 'volume': '13'}, {'price': '1680.05', 'volume': '2'}, {'price': '1685.00', 'volume': '8'}, {'price': '1686.00', 'volume': '5'}], 'ntvAggBidList': [{'price': '1633.70', 'volume': '1'}, {'price': '1632.50', 'volume': '25'}, {'price': '1629.33', 'volume': '10'}, {'price': '1629.00', 'volume': '10'}, {'price': '1628.01', 'volume': '10'}, {'price': '1628.00', 'volume': '1'}, {'price': '1626.04', 'volume': '200'}, {'price': '1619.00', 'volume': '100'}, {'price': '1615.00', 'volume': '103'}, {'price': '1614.92', 'volume': '4'}, {'price': '1614.14', 'volume': '1'}, {'price': '1613.00', 'volume': '1'}, {'price': '1611.00', 'volume': '3'}, {'price': '1610.01', 'volume': '2'}, {'price': '1610.00', 'volume': '1'}, {'price': '1605.47', 'volume': '6'}, {'price': '1605.00', 'volume': '1'}, {'price': '1603.00', 'volume': '50'}, {'price': '1600.00', 'volume': '58'}, {'price': '1599.12', 'volume': '1'}, {'price': '1596.00', 'volume': '2'}, {'price': '1595.00', 'volume': '2'}, {'price': '1591.41', 'volume': '1'}, {'price': '1590.00', 'volume': '2'}, {'price': '1588.03', 'volume': '1'}, {'price': '1588.00', 'volume': '1'}, {'price': '1584.73', 'volume': '2'}, {'price': '1582.00', 'volume': '2'}, {'price': '1580.00', 'volume': '25'}, {'price': '1579.61', 'volume': '1'}]}, 'currencyCode': 'USD', 'lotSize': '1', 'limitUp': '0.0000', 'limitDown': '0.0000', 'latestDividendDate': '2015-04-27', 'latestEarningsDate': '2020-10-29', 'ps': '7.02', 'bps': '304.34', 'estimateEarningsDate': '02/01-02/05', 'tradeStatus': 'D'}```

access in ['depth']['ntvAggAskList'] and ['depth']['ntvAggBidList'] and subtract the first (0) result to get the spread.

**Comment by xterminal01** [comment]
Cool, thanks it worked!
